/**
 * 25 destinos de backlinks de alta autoridad y bajo spam relacionados con
 * finanzas, inversión, fintech y software financiero (ES + EN).
 *
 * Criterios: dominios reales con tráfico, moderación editorial y spam score
 * bajo. Nada de granjas de enlaces ni PBNs: Google las trata como link spam.
 *
 * `da` = Domain Authority aproximada (estimación pública, orientativa).
 * `dofollow`: true cuando el enlace del perfil/publicación pasa autoridad.
 * `auto`: true cuando el envío se puede automatizar por feed/API desde la app.
 */

export type BacklinkTarget = {
  id: string;
  name: string;
  url: string;
  submitUrl: string;
  lang: "es" | "en" | "both";
  da: number;
  spam: "bajo" | "muy bajo";
  dofollow: boolean;
  auto: boolean;
  type: "Syndicación" | "Comunidad" | "Directorio" | "Foro finanzas" | "Medio finanzas";
  how: string;
};

export const backlinkTargets: BacklinkTarget[] = [
  /* ------------------------------ Syndicación ----------------------------- */
  {
    id: "medium",
    name: "Medium",
    url: "https://medium.com",
    submitUrl: "https://medium.com/new-story",
    lang: "both",
    da: 95,
    spam: "muy bajo",
    dofollow: false,
    auto: true,
    type: "Syndicación",
    how: "Republica el artículo con canonical a whatsyour-number.com. Enlace nofollow pero enorme tráfico de referencia y descubrimiento.",
  },
  {
    id: "substack",
    name: "Substack",
    url: "https://substack.com",
    submitUrl: "https://substack.com/publish",
    lang: "both",
    da: 91,
    spam: "muy bajo",
    dofollow: true,
    auto: true,
    type: "Syndicación",
    how: "Newsletter propia con extracto + enlace dofollow al artículo completo.",
  },
  {
    id: "devto",
    name: "Dev.to",
    url: "https://dev.to",
    submitUrl: "https://dev.to/new",
    lang: "en",
    da: 90,
    spam: "muy bajo",
    dofollow: true,
    auto: true,
    type: "Syndicación",
    how: "Artículos de producto/fintech con canonical_url. Enlaces dofollow en el cuerpo.",
  },
  {
    id: "hashnode",
    name: "Hashnode",
    url: "https://hashnode.com",
    submitUrl: "https://hashnode.com/create/story",
    lang: "en",
    da: 82,
    spam: "muy bajo",
    dofollow: true,
    auto: true,
    type: "Syndicación",
    how: "Blog con dominio propio y canonical al original. API pública para publicar.",
  },
  {
    id: "linkedin-pulse",
    name: "LinkedIn Pulse",
    url: "https://www.linkedin.com",
    submitUrl: "https://www.linkedin.com/article/new/",
    lang: "both",
    da: 99,
    spam: "muy bajo",
    dofollow: false,
    auto: true,
    type: "Syndicación",
    how: "Artículo en la página de empresa. Tráfico cualificado y señales de marca.",
  },

  /* ---------------------------- Foros finanzas ---------------------------- */
  {
    id: "rankia-es",
    name: "Rankia (España)",
    url: "https://www.rankia.com",
    submitUrl: "https://www.rankia.com/blog/nuevo",
    lang: "es",
    da: 74,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Foro finanzas",
    how: "La mayor comunidad financiera en español. Blog de usuario con enlaces dofollow en el contenido.",
  },
  {
    id: "rankia-mx",
    name: "Rankia México",
    url: "https://www.rankia.mx",
    submitUrl: "https://www.rankia.mx/foros",
    lang: "es",
    da: 62,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Foro finanzas",
    how: "Aporta en hilos de ahorro/inversión en México con enlace contextual.",
  },
  {
    id: "burbuja",
    name: "Burbuja.info",
    url: "https://www.burbuja.info",
    submitUrl: "https://www.burbuja.info/inmobiliaria/",
    lang: "es",
    da: 62,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Foro finanzas",
    how: "Foro económico español muy indexado. Enlaces dofollow en firma y posts útiles.",
  },
  {
    id: "invertirenbolsa",
    name: "Invertir en Bolsa (foro)",
    url: "https://www.invertirenbolsa.info",
    submitUrl: "https://www.invertirenbolsa.info/foro-inversiones/",
    lang: "es",
    da: 56,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Foro finanzas",
    how: "Comunidad de inversión a largo plazo. Muy afín al público objetivo.",
  },
  {
    id: "bogleheads",
    name: "Bogleheads",
    url: "https://www.bogleheads.org",
    submitUrl: "https://www.bogleheads.org/forum/",
    lang: "en",
    da: 75,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Foro finanzas",
    how: "Referencia mundial de inversión indexada. Aporta cálculos reales, no promoción.",
  },
  {
    id: "wallstreetoasis",
    name: "Wall Street Oasis",
    url: "https://www.wallstreetoasis.com",
    submitUrl: "https://www.wallstreetoasis.com/forum",
    lang: "en",
    da: 73,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Foro finanzas",
    how: "Foro de finanzas profesional. Enlaces dofollow en posts de valor.",
  },
  {
    id: "earlyretirement",
    name: "Early Retirement Forum",
    url: "https://www.early-retirement.org",
    submitUrl: "https://www.early-retirement.org/forums/",
    lang: "en",
    da: 60,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Foro finanzas",
    how: "Comunidad FIRE: encaja con el cálculo del número de libertad financiera.",
  },

  /* ---------------------------- Medios finanzas --------------------------- */
  {
    id: "tradingview",
    name: "TradingView (Ideas)",
    url: "https://www.tradingview.com",
    submitUrl: "https://www.tradingview.com/chart/",
    lang: "both",
    da: 92,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Medio finanzas",
    how: "Publica ideas/análisis con enlace en el perfil (dofollow) y en la descripción.",
  },
  {
    id: "seekingalpha",
    name: "Seeking Alpha",
    url: "https://seekingalpha.com",
    submitUrl: "https://seekingalpha.com/contributor-signup",
    lang: "en",
    da: 91,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Medio finanzas",
    how: "Programa de colaboradores. Enlace en bio del autor y en el artículo.",
  },
  {
    id: "finect",
    name: "Finect",
    url: "https://www.finect.com",
    submitUrl: "https://www.finect.com/registro",
    lang: "es",
    da: 58,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Medio finanzas",
    how: "Red social financiera española. Perfil de empresa + publicaciones con enlace.",
  },
  {
    id: "estrategias",
    name: "Estrategias de Inversión",
    url: "https://www.estrategiasdeinversion.com",
    submitUrl: "https://www.estrategiasdeinversion.com/contacto",
    lang: "es",
    da: 63,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Medio finanzas",
    how: "Colaboraciones editoriales. Pitch con un artículo de datos propios.",
  },
  {
    id: "elblogsalmon",
    name: "El Blog Salmón",
    url: "https://www.elblogsalmon.com",
    submitUrl: "https://www.elblogsalmon.com/contacto",
    lang: "es",
    da: 76,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Medio finanzas",
    how: "Medio económico de referencia en español. Aporta un estudio con datos agregados de la app.",
  },
  {
    id: "investing",
    name: "Investing.com (perfil)",
    url: "https://www.investing.com",
    submitUrl: "https://www.investing.com/members-admin/",
    lang: "both",
    da: 92,
    spam: "bajo",
    dofollow: false,
    auto: false,
    type: "Medio finanzas",
    how: "Perfil de autor y comentarios de análisis. Señal de marca y tráfico.",
  },

  /* ------------------------------ Comunidades ----------------------------- */
  {
    id: "indiehackers",
    name: "Indie Hackers",
    url: "https://www.indiehackers.com",
    submitUrl: "https://www.indiehackers.com/new-post",
    lang: "en",
    da: 79,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Comunidad",
    how: "Comparte métricas del producto. Enlace dofollow en el perfil y en los posts.",
  },
  {
    id: "quora",
    name: "Quora (ES + EN)",
    url: "https://www.quora.com",
    submitUrl: "https://www.quora.com",
    lang: "both",
    da: 92,
    spam: "bajo",
    dofollow: false,
    auto: false,
    type: "Comunidad",
    how: "Responde preguntas de jubilación/ahorro citando el artículo. Tráfico constante.",
  },
  {
    id: "reddit",
    name: "Reddit (r/personalfinance, r/dinero)",
    url: "https://www.reddit.com",
    submitUrl: "https://www.reddit.com/r/personalfinance/",
    lang: "both",
    da: 94,
    spam: "bajo",
    dofollow: false,
    auto: false,
    type: "Comunidad",
    how: "Aporta primero; el enlace solo cuando responde a la pregunta. Alto tráfico.",
  },

  /* ------------------------------ Directorios ----------------------------- */
  {
    id: "producthunt",
    name: "Product Hunt",
    url: "https://www.producthunt.com",
    submitUrl: "https://www.producthunt.com/posts/new",
    lang: "en",
    da: 91,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Directorio",
    how: "Lanzamiento del producto. Enlace dofollow en la ficha una vez destacado.",
  },
  {
    id: "crunchbase",
    name: "Crunchbase",
    url: "https://www.crunchbase.com",
    submitUrl: "https://www.crunchbase.com/add-new",
    lang: "en",
    da: 92,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Directorio",
    how: "Perfil de empresa fintech con web oficial. Enlace de marca muy limpio.",
  },
  {
    id: "g2",
    name: "G2",
    url: "https://www.g2.com",
    submitUrl: "https://www.g2.com/products/new",
    lang: "en",
    da: 91,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Directorio",
    how: "Ficha en la categoría Personal Finance Software. Enlace dofollow a la web.",
  },
  {
    id: "capterra",
    name: "Capterra",
    url: "https://www.capterra.es",
    submitUrl: "https://www.capterra.es/vendors",
    lang: "both",
    da: 89,
    spam: "muy bajo",
    dofollow: true,
    auto: false,
    type: "Directorio",
    how: "Versión española e inglesa del directorio. Categoría de finanzas personales.",
  },
  {
    id: "saashub",
    name: "SaaSHub",
    url: "https://www.saashub.com",
    submitUrl: "https://www.saashub.com/submit",
    lang: "en",
    da: 66,
    spam: "bajo",
    dofollow: true,
    auto: false,
    type: "Directorio",
    how: "Alta gratuita con enlace dofollow y categoría finanzas.",
  },
];

export const backlinkStats = {
  total: backlinkTargets.length,
  dofollow: backlinkTargets.filter((target) => target.dofollow).length,
  es: backlinkTargets.filter((target) => target.lang !== "en").length,
  en: backlinkTargets.filter((target) => target.lang !== "es").length,
  avgDa: Math.round(
    backlinkTargets.reduce((sum, target) => sum + target.da, 0) / backlinkTargets.length,
  ),
};
