/**
 * Ciudades adicionales del Lifestyle Simulator.
 * Mismas fuentes y criterios que `lifestyle-cities.ts`.
 */
import type { CityData } from "./lifestyle-cities";
const PHOTO = {
  hamburg: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Elbphilharmonie_2025.jpg",
  zagreb: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Zagreb_%2829255640143%29.jpg/1920px-Zagreb_%2829255640143%29.jpg",
  ljubljana: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Ljubljana_Old_Town%2C_Slovenia_%28Old_Camera%29_%2833286165680%29.jpg/1920px-Ljubljana_Old_Town%2C_Slovenia_%28Old_Camera%29_%2833286165680%29.jpg",
  tallinn: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Raekoja_plats_at_night.jpg/1920px-Raekoja_plats_at_night.jpg",
  riga: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Riga_%2833844464828%29.jpg/1920px-Riga_%2833844464828%29.jpg",
  vilnius: "https://upload.wikimedia.org/wikipedia/en/8/84/The_White_Bridge_and_%C5%A0nipi%C5%A1k%C4%97s_district_in_Vilnius_in_2023_by_Augustas_Did%C5%BEgalvis.jpg",
  bucharest: "https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Bucharest_-_Palace_of_the_Parliament_%282024%29_%282%29.jpg/1920px-Bucharest_-_Palace_of_the_Parliament_%282024%29_%282%29.jpg",
  sofia: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Catedral_de_Alejandro_Nevski_--_2019_--_Sof%C3%ADa%2C_Bulgaria.jpg/1920px-Catedral_de_Alejandro_Nevski_--_2019_--_Sof%C3%ADa%2C_Bulgaria.jpg",
  malaga: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Da_Gibralfaro_%28cropped%292.jpg/1920px-Da_Gibralfaro_%28cropped%292.jpg",
  seville: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Plaza_de_Espa%C3%B1a_%28Sevilla%29_-_01.jpg/1920px-Plaza_de_Espa%C3%B1a_%28Sevilla%29_-_01.jpg",
  nice: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/CollineDuChateau_NiceFrance2022.png/1920px-CollineDuChateau_NiceFrance2022.png",
  florence: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Cattedrale_di_Santa_Maria_del_Fiore_%E2%80%93_Il_Duomo_di_Firenze.jpg/1920px-Cattedrale_di_Santa_Maria_del_Fiore_%E2%80%93_Il_Duomo_di_Firenze.jpg",
  calgary: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Downtown_Calgary_2020-4.jpg",
  nashville: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nashville%2C_TN_skyline.jpg/1920px-Nashville%2C_TN_skyline.jpg",
  phoenix: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Downtown_Phoenix_Aerial_Looking_Northeast.jpg",
  raleigh: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Raleigh_Skyline.jpg/1920px-Raleigh_Skyline.jpg",
  monterrey: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/View_of_Monterrey_%282015%29.jpg/1920px-View_of_Monterrey_%282015%29.jpg",
  cancun: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Cancun_Strand_Luftbild_%2822143397586%29.jpg/1920px-Cancun_Strand_Luftbild_%2822143397586%29.jpg",
  florianopolis: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Morro_da_Cruz%2C_Florian%C3%B3polis_-_SC%2C_Brazil_-_panoramio_%28cropped%29.jpg/1920px-Morro_da_Cruz%2C_Florian%C3%B3polis_-_SC%2C_Brazil_-_panoramio_%28cropped%29.jpg",
  cordoba_ar: "https://upload.wikimedia.org/wikipedia/commons/2/26/Cathedral_Main_Square.jpg",
  laspaz: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Vista_del_centro_de_La_Paz.jpg/1920px-Vista_del_centro_de_La_Paz.jpg",
  punta: "https://upload.wikimedia.org/wikipedia/commons/4/47/%D0%9F%D1%83%D0%BD%D1%82%D0%B0-%D0%B4%D0%B5%D0%BB%D1%8C-%D0%AD%D1%81%D1%82%D0%B5.jpg",
  shanghai: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Bund_2.jpg/1920px-The_Bund_2.jpg",
  phuket: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Phuket_Aerial.jpg/1920px-Phuket_Aerial.jpg",
  danang: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Dragon_Bridge%2C_Da_Nang_during_day_-_20230819_%28cropped%29.jpg",
  tbilisi: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/View_of_Tbilisi_from_Tabori_Church_2023-10-08-2.jpg/1920px-View_of_Tbilisi_from_Tabori_Church_2023-10-08-2.jpg",
  istanbul: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Hagia_Sophia_%28228968325%29.jpeg",
  doha: "https://upload.wikimedia.org/wikipedia/commons/2/26/The_Pearl_Marina_in_Nov_2013.jpg",
  perth: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Perth_CBD_skyline_from_State_War_Memorial_Lookout%2C_2023%2C_04_b.jpg/1920px-Perth_CBD_skyline_from_State_War_Memorial_Lookout%2C_2023%2C_04_b.jpg",
  dakar: "https://upload.wikimedia.org/wikipedia/commons/4/46/Dakar-Ind%C3%A9pendance.jpg",
  zanzibar: "https://upload.wikimedia.org/wikipedia/commons/7/73/Zanzibar_sultan_palace.jpg",
  hongkong: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/960px-Flag_of_Hong_Kong.svg.png",
  wellington: "https://upload.wikimedia.org/wikipedia/commons/3/32/Seddon_Statue_in_Parliament_Grounds.jpg",
  durban: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Durban_from_the_Balcony_%28Dennis_Sylvester_Hurd%29_1.jpg/3840px-Durban_from_the_Balcony_%28Dennis_Sylvester_Hurd%29_1.jpg",
  vienna: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Wien_-_Schloss_Sch%C3%B6nbrunn.JPG/1920px-Wien_-_Schloss_Sch%C3%B6nbrunn.JPG",
  munich: "https://upload.wikimedia.org/wikipedia/commons/7/73/Rathaus_and_Marienplatz_from_Peterskirche_-_August_2006.jpg",
  stockholm: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Gamla_stan_September_2014_01.jpg/1920px-Gamla_stan_September_2014_01.jpg",
  oslo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Oslo_Opera_House_-_2025.jpg/1920px-Oslo_Opera_House_-_2025.jpg",
  dublin: "https://upload.wikimedia.org/wikipedia/commons/5/53/HalfPennyBridge.jpg",
  budapest: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Hungarian_Parliament_Building_from_across_the_Danube%2C_2025-01-11.jpg/1920px-Hungarian_Parliament_Building_from_across_the_Danube%2C_2025-01-11.jpg",
  brussels: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Grand-Place%2C_Brussels_-_panorama%2C_June_2018.jpg/1920px-Grand-Place%2C_Brussels_-_panorama%2C_June_2018.jpg",
  edinburgh: "https://upload.wikimedia.org/wikipedia/commons/5/59/City_of_Edinburgh_-_Edinburgh_Castle_-_20140421004403.jpg",
  helsinki: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Kirkko3.png",
  geneva: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Jet_d%27eau_de_Gen%C3%A8ve_%28swiss%29.jpg/1920px-Jet_d%27eau_de_Gen%C3%A8ve_%28swiss%29.jpg",
  seattle: "https://upload.wikimedia.org/wikipedia/commons/2/23/Space_Needle_2011-07-04.jpg",
  boston: "https://upload.wikimedia.org/wikipedia/commons/9/96/ISH_WC_Boston4.jpg",
  sandiego: "https://upload.wikimedia.org/wikipedia/commons/e/ea/La_Jolla_Shores_view_%28cropped%29.jpg",
  montreal: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Montreal%2C_Quebec_skyline.jpg/1920px-Montreal%2C_Quebec_skyline.jpg",
  losangeles: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hollywood_sign_%288485145044%29.jpg/1920px-Hollywood_sign_%288485145044%29.jpg",
  denver: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Denver%2C_Colorado_skyline_%28cropped%29.jpg/1920px-Denver%2C_Colorado_skyline_%28cropped%29.jpg",
  guadalajara: "https://upload.wikimedia.org/wikipedia/commons/3/38/Panor%C3%A1mica_Guadalajara_desde_edificio_Bansi_hacia_norte_%28cropped%29.jpg",
  sanjose_cr: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Ciudad_de_San_Jos%C3%A9.png",
  cartagena: "https://upload.wikimedia.org/wikipedia/commons/3/30/Museo_Naval_del_Caribe.JPG",
  quito: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/FACHADA_ASAMBLEA_NACIONAL._QUITO%2C_20_DE_FEBRERO_2020._01.jpg/1920px-FACHADA_ASAMBLEA_NACIONAL._QUITO%2C_20_DE_FEBRERO_2020._01.jpg",
  asuncion: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Palacio_de_Gobierno2.jpg",
  osaka: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Osaka_Castle_03bs3200.jpg",
  hanoi: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Hanoi_skyline_with_Ba_Vi_Mountain.jpg",
  manila: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cityscape_of_Manila%2C_2025_%2801%29.jpg/1920px-Cityscape_of_Manila%2C_2025_%2801%29.jpg",
  telaviv: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Sarona_CBD_01_%28cropped%29.jpg/1920px-Sarona_CBD_01_%28cropped%29.jpg",
  abudhabi: "https://upload.wikimedia.org/wikipedia/en/7/7d/Sheikh_Zayed_Mosque_view.jpg",
  bengaluru: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/View_from_Visvesvaraya_Industrial_and_Technological_Museum_%282025%29_02.jpg/1920px-View_from_Visvesvaraya_Industrial_and_Technological_Museum_%282025%29_02.jpg",
  chiangmai: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/0020-%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%AA%E0%B8%B4%E0%B8%87%E0%B8%AB%E0%B9%8C%E0%B8%A7%E0%B8%A3%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A7%E0%B8%B4%E0%B8%AB%E0%B8%B2%E0%B8%A3.jpg/1920px-0020-%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%AA%E0%B8%B4%E0%B8%87%E0%B8%AB%E0%B9%8C%E0%B8%A7%E0%B8%A3%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A7%E0%B8%B4%E0%B8%AB%E0%B8%B2%E0%B8%A3.jpg",
  brisbane: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Brisbane_CBD_seen_from_Kangaroo_Point%2C_2024%2C_01_%282%29.jpg/1920px-Brisbane_CBD_seen_from_Kangaroo_Point%2C_2024%2C_01_%282%29.jpg",
  accra: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Acca.jpg",
  lagos: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Tafa_Balewa_Square_%28Onikan%29_in_Lagos._Nigeria.jpg",
  kigali: "https://upload.wikimedia.org/wikipedia/commons/2/2d/High_Angle_View_Of_Kigali_City_Street_on_November_29%2C_2018._Emmanuel_Kwizera.jpg",
  casablanca: "https://upload.wikimedia.org/wikipedia/en/c/ce/Hassan_II_mosque%2C_Casablanca_2.jpg",
};
export const extraCities: CityData[] = [
  {
    id: "vienna", name: "Viena", country: "Austria", photo: PHOTO.vienna, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 1150, food: 470, transport: 45, healthcare: 90, education: 300, internet: 35, entertainment: 340,
    avgSalary: 2700, taxRate: 34,
    safety: 88, healthcareScore: 90, qualityOfLife: 92, purchasingPower: 66, walkability: 90, publicTransport: 96,
    airQuality: 78, greenSpaces: 86, internetSpeed: 180, englishFriendly: 78, remoteWork: 88, nightlife: 80,
    schools: 88, jobMarket: 78, beachKm: 300, intlAirport: true,
  },
  {
    id: "munich", name: "Múnich", country: "Alemania", photo: PHOTO.munich, region: "europe",
    climate: "cold", climateLabelEs: "Continental alpino", climateLabelEn: "Alpine continental",
    housing: 1600, food: 520, transport: 60, healthcare: 120, education: 350, internet: 40, entertainment: 380,
    avgSalary: 3300, taxRate: 38,
    safety: 86, healthcareScore: 88, qualityOfLife: 90, purchasingPower: 68, walkability: 86, publicTransport: 92,
    airQuality: 76, greenSpaces: 82, internetSpeed: 150, englishFriendly: 80, remoteWork: 86, nightlife: 78,
    schools: 86, jobMarket: 88, beachKm: 450, intlAirport: true,
  },
  {
    id: "stockholm", name: "Estocolmo", country: "Suecia", photo: PHOTO.stockholm, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1500, food: 540, transport: 80, healthcare: 60, education: 200, internet: 40, entertainment: 400,
    avgSalary: 3100, taxRate: 33,
    safety: 82, healthcareScore: 88, qualityOfLife: 88, purchasingPower: 66, walkability: 88, publicTransport: 92,
    airQuality: 88, greenSpaces: 84, internetSpeed: 220, englishFriendly: 92, remoteWork: 88, nightlife: 74,
    schools: 86, jobMarket: 82, beachKm: 1, intlAirport: true,
  },
  {
    id: "oslo", name: "Oslo", country: "Noruega", photo: PHOTO.oslo, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1700, food: 650, transport: 85, healthcare: 70, education: 180, internet: 45, entertainment: 450,
    avgSalary: 3900, taxRate: 32,
    safety: 86, healthcareScore: 90, qualityOfLife: 90, purchasingPower: 70, walkability: 84, publicTransport: 88,
    airQuality: 90, greenSpaces: 88, internetSpeed: 230, englishFriendly: 92, remoteWork: 86, nightlife: 70,
    schools: 86, jobMarket: 84, beachKm: 1, intlAirport: true,
  },
  {
    id: "dublin", name: "Dublín", country: "Irlanda", photo: PHOTO.dublin, region: "europe",
    climate: "temperate", climateLabelEs: "Oceánico lluvioso", climateLabelEn: "Rainy oceanic",
    housing: 2000, food: 560, transport: 90, healthcare: 110, education: 450, internet: 45, entertainment: 420,
    avgSalary: 3300, taxRate: 30,
    safety: 72, healthcareScore: 76, qualityOfLife: 80, purchasingPower: 64, walkability: 84, publicTransport: 72,
    airQuality: 80, greenSpaces: 74, internetSpeed: 150, englishFriendly: 100, remoteWork: 88, nightlife: 86,
    schools: 80, jobMarket: 88, beachKm: 5, intlAirport: true,
  },
  {
    id: "budapest", name: "Budapest", country: "Hungría", photo: PHOTO.budapest, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 750, food: 340, transport: 30, healthcare: 70, education: 220, internet: 20, entertainment: 240,
    avgSalary: 1350, taxRate: 28,
    safety: 80, healthcareScore: 72, qualityOfLife: 78, purchasingPower: 48, walkability: 88, publicTransport: 90,
    airQuality: 62, greenSpaces: 72, internetSpeed: 220, englishFriendly: 68, remoteWork: 88, nightlife: 88,
    schools: 74, jobMarket: 64, beachKm: 300, intlAirport: true,
  },
  {
    id: "brussels", name: "Bruselas", country: "Bélgica", photo: PHOTO.brussels, region: "europe",
    climate: "temperate", climateLabelEs: "Oceánico fresco", climateLabelEn: "Cool oceanic",
    housing: 1100, food: 470, transport: 55, healthcare: 90, education: 320, internet: 40, entertainment: 340,
    avgSalary: 2800, taxRate: 40,
    safety: 66, healthcareScore: 86, qualityOfLife: 80, purchasingPower: 62, walkability: 84, publicTransport: 86,
    airQuality: 70, greenSpaces: 76, internetSpeed: 160, englishFriendly: 84, remoteWork: 84, nightlife: 76,
    schools: 82, jobMarket: 80, beachKm: 110, intlAirport: true,
  },
  {
    id: "edinburgh", name: "Edimburgo", country: "Reino Unido", photo: PHOTO.edinburgh, region: "europe",
    climate: "cold", climateLabelEs: "Oceánico frío", climateLabelEn: "Cold oceanic",
    housing: 1250, food: 470, transport: 70, healthcare: 60, education: 380, internet: 35, entertainment: 340,
    avgSalary: 2600, taxRate: 32,
    safety: 84, healthcareScore: 82, qualityOfLife: 86, purchasingPower: 60, walkability: 90, publicTransport: 80,
    airQuality: 84, greenSpaces: 84, internetSpeed: 140, englishFriendly: 100, remoteWork: 84, nightlife: 80,
    schools: 84, jobMarket: 74, beachKm: 3, intlAirport: true,
  },
  {
    id: "helsinki", name: "Helsinki", country: "Finlandia", photo: PHOTO.helsinki, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1300, food: 500, transport: 70, healthcare: 60, education: 150, internet: 35, entertainment: 350,
    avgSalary: 2900, taxRate: 32,
    safety: 90, healthcareScore: 90, qualityOfLife: 90, purchasingPower: 66, walkability: 86, publicTransport: 90,
    airQuality: 92, greenSpaces: 86, internetSpeed: 200, englishFriendly: 90, remoteWork: 86, nightlife: 68,
    schools: 92, jobMarket: 78, beachKm: 1, intlAirport: true,
  },
  {
    id: "geneva", name: "Ginebra", country: "Suiza", photo: PHOTO.geneva, region: "europe",
    climate: "temperate", climateLabelEs: "Alpino templado", climateLabelEn: "Temperate alpine",
    housing: 2400, food: 750, transport: 80, healthcare: 420, education: 900, internet: 55, entertainment: 520,
    avgSalary: 6200, taxRate: 22,
    safety: 90, healthcareScore: 94, qualityOfLife: 90, purchasingPower: 84, walkability: 86, publicTransport: 92,
    airQuality: 86, greenSpaces: 88, internetSpeed: 220, englishFriendly: 86, remoteWork: 86, nightlife: 62,
    schools: 90, jobMarket: 86, beachKm: 300, intlAirport: true,
  },
  {
    id: "seattle", name: "Seattle", country: "Estados Unidos", photo: PHOTO.seattle, region: "northamerica",
    climate: "temperate", climateLabelEs: "Oceánico lluvioso", climateLabelEn: "Rainy oceanic",
    housing: 2200, food: 620, transport: 110, healthcare: 430, education: 900, internet: 70, entertainment: 450,
    avgSalary: 5600, taxRate: 28,
    safety: 58, healthcareScore: 80, qualityOfLife: 80, purchasingPower: 84, walkability: 80, publicTransport: 72,
    airQuality: 82, greenSpaces: 84, internetSpeed: 260, englishFriendly: 100, remoteWork: 90, nightlife: 80,
    schools: 82, jobMarket: 92, beachKm: 1, intlAirport: true,
  },
  {
    id: "boston", name: "Boston", country: "Estados Unidos", photo: PHOTO.boston, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental frío", climateLabelEn: "Cold continental",
    housing: 2600, food: 640, transport: 100, healthcare: 450, education: 1000, internet: 70, entertainment: 460,
    avgSalary: 5400, taxRate: 32,
    safety: 72, healthcareScore: 90, qualityOfLife: 82, purchasingPower: 80, walkability: 88, publicTransport: 82,
    airQuality: 80, greenSpaces: 74, internetSpeed: 250, englishFriendly: 100, remoteWork: 86, nightlife: 84,
    schools: 92, jobMarket: 90, beachKm: 2, intlAirport: true,
  },
  {
    id: "sandiego", name: "San Diego", country: "Estados Unidos", photo: PHOTO.sandiego, region: "northamerica",
    climate: "beach", climateLabelEs: "Mediterráneo costero", climateLabelEn: "Coastal Mediterranean",
    housing: 2400, food: 600, transport: 180, healthcare: 430, education: 900, internet: 70, entertainment: 440,
    avgSalary: 4900, taxRate: 30,
    safety: 72, healthcareScore: 80, qualityOfLife: 86, purchasingPower: 80, walkability: 66, publicTransport: 52,
    airQuality: 82, greenSpaces: 76, internetSpeed: 240, englishFriendly: 100, remoteWork: 88, nightlife: 78,
    schools: 82, jobMarket: 80, beachKm: 0, intlAirport: true,
  },
  {
    id: "montreal", name: "Montreal", country: "Canadá", photo: PHOTO.montreal, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental frío", climateLabelEn: "Cold continental",
    housing: 1250, food: 480, transport: 90, healthcare: 80, education: 400, internet: 55, entertainment: 340,
    avgSalary: 2800, taxRate: 31,
    safety: 80, healthcareScore: 84, qualityOfLife: 84, purchasingPower: 62, walkability: 88, publicTransport: 86,
    airQuality: 80, greenSpaces: 78, internetSpeed: 190, englishFriendly: 80, remoteWork: 86, nightlife: 86,
    schools: 84, jobMarket: 78, beachKm: 1, intlAirport: true,
  },
  {
    id: "losangeles", name: "Los Ángeles", country: "Estados Unidos", photo: PHOTO.losangeles, region: "northamerica",
    climate: "warm", climateLabelEs: "Mediterráneo seco", climateLabelEn: "Dry Mediterranean",
    housing: 2500, food: 640, transport: 220, healthcare: 440, education: 950, internet: 70, entertainment: 520,
    avgSalary: 5200, taxRate: 32,
    safety: 52, healthcareScore: 78, qualityOfLife: 74, purchasingPower: 78, walkability: 58, publicTransport: 48,
    airQuality: 50, greenSpaces: 66, internetSpeed: 240, englishFriendly: 100, remoteWork: 86, nightlife: 90,
    schools: 74, jobMarket: 88, beachKm: 0, intlAirport: true,
  },
  {
    id: "denver", name: "Denver", country: "Estados Unidos", photo: PHOTO.denver, region: "northamerica",
    climate: "cold", climateLabelEs: "Semiárido de montaña", climateLabelEn: "Mountain semi-arid",
    housing: 1700, food: 540, transport: 180, healthcare: 410, education: 820, internet: 65, entertainment: 400,
    avgSalary: 4600, taxRate: 26,
    safety: 66, healthcareScore: 80, qualityOfLife: 82, purchasingPower: 82, walkability: 64, publicTransport: 58,
    airQuality: 76, greenSpaces: 84, internetSpeed: 250, englishFriendly: 100, remoteWork: 88, nightlife: 76,
    schools: 80, jobMarket: 84, beachKm: 1500, intlAirport: true,
  },
  {
    id: "guadalajara", name: "Guadalajara", country: "México", photo: PHOTO.guadalajara, region: "latam",
    climate: "warm", climateLabelEs: "Subtropical templado", climateLabelEn: "Mild subtropical",
    housing: 620, food: 300, transport: 45, healthcare: 90, education: 320, internet: 25, entertainment: 230,
    avgSalary: 780, taxRate: 22,
    safety: 50, healthcareScore: 62, qualityOfLife: 70, purchasingPower: 32, walkability: 68, publicTransport: 60,
    airQuality: 54, greenSpaces: 62, internetSpeed: 140, englishFriendly: 42, remoteWork: 80, nightlife: 84,
    schools: 66, jobMarket: 64, beachKm: 300, intlAirport: true,
  },
  {
    id: "sanjose_cr", name: "San José", country: "Costa Rica", photo: PHOTO.sanjose_cr, region: "latam",
    climate: "warm", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 780, food: 340, transport: 60, healthcare: 100, education: 420, internet: 35, entertainment: 260,
    avgSalary: 950, taxRate: 20,
    safety: 58, healthcareScore: 74, qualityOfLife: 78, purchasingPower: 36, walkability: 62, publicTransport: 56,
    airQuality: 72, greenSpaces: 86, internetSpeed: 90, englishFriendly: 58, remoteWork: 82, nightlife: 68,
    schools: 72, jobMarket: 58, beachKm: 90, intlAirport: true,
  },
  {
    id: "cartagena", name: "Cartagena", country: "Colombia", photo: PHOTO.cartagena, region: "latam",
    climate: "beach", climateLabelEs: "Tropical caribeño", climateLabelEn: "Caribbean tropical",
    housing: 600, food: 300, transport: 40, healthcare: 80, education: 300, internet: 25, entertainment: 240,
    avgSalary: 620, taxRate: 19,
    safety: 52, healthcareScore: 64, qualityOfLife: 70, purchasingPower: 28, walkability: 66, publicTransport: 48,
    airQuality: 70, greenSpaces: 58, internetSpeed: 90, englishFriendly: 44, remoteWork: 74, nightlife: 84,
    schools: 60, jobMarket: 50, beachKm: 0, intlAirport: true,
  },
  {
    id: "quito", name: "Quito", country: "Ecuador", photo: PHOTO.quito, region: "latam",
    climate: "temperate", climateLabelEs: "Andino templado", climateLabelEn: "Temperate Andean",
    housing: 520, food: 260, transport: 35, healthcare: 80, education: 280, internet: 25, entertainment: 200,
    avgSalary: 650, taxRate: 20,
    safety: 50, healthcareScore: 66, qualityOfLife: 68, purchasingPower: 28, walkability: 68, publicTransport: 62,
    airQuality: 60, greenSpaces: 72, internetSpeed: 80, englishFriendly: 40, remoteWork: 76, nightlife: 66,
    schools: 64, jobMarket: 50, beachKm: 200, intlAirport: true,
  },
  {
    id: "asuncion", name: "Asunción", country: "Paraguay", photo: PHOTO.asuncion, region: "latam",
    climate: "warm", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 480, food: 260, transport: 35, healthcare: 70, education: 260, internet: 25, entertainment: 190,
    avgSalary: 700, taxRate: 15,
    safety: 56, healthcareScore: 60, qualityOfLife: 66, purchasingPower: 32, walkability: 58, publicTransport: 48,
    airQuality: 64, greenSpaces: 60, internetSpeed: 90, englishFriendly: 36, remoteWork: 74, nightlife: 64,
    schools: 58, jobMarket: 52, beachKm: 1000, intlAirport: true,
  },
  {
    id: "osaka", name: "Osaka", country: "Japón", photo: PHOTO.osaka, region: "asia",
    climate: "temperate", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 900, food: 420, transport: 60, healthcare: 90, education: 350, internet: 35, entertainment: 320,
    avgSalary: 2300, taxRate: 26,
    safety: 94, healthcareScore: 90, qualityOfLife: 86, purchasingPower: 58, walkability: 88, publicTransport: 96,
    airQuality: 74, greenSpaces: 64, internetSpeed: 240, englishFriendly: 40, remoteWork: 78, nightlife: 88,
    schools: 84, jobMarket: 80, beachKm: 20, intlAirport: true,
  },
  {
    id: "hanoi", name: "Hanói", country: "Vietnam", photo: PHOTO.hanoi, region: "asia",
    climate: "warm", climateLabelEs: "Tropical monzónico", climateLabelEn: "Monsoon tropical",
    housing: 480, food: 250, transport: 40, healthcare: 70, education: 400, internet: 20, entertainment: 190,
    avgSalary: 520, taxRate: 14,
    safety: 72, healthcareScore: 58, qualityOfLife: 62, purchasingPower: 28, walkability: 66, publicTransport: 50,
    airQuality: 32, greenSpaces: 54, internetSpeed: 120, englishFriendly: 42, remoteWork: 86, nightlife: 78,
    schools: 58, jobMarket: 54, beachKm: 120, intlAirport: true,
  },
  {
    id: "manila", name: "Manila", country: "Filipinas", photo: PHOTO.manila, region: "asia",
    climate: "warm", climateLabelEs: "Tropical húmedo", climateLabelEn: "Humid tropical",
    housing: 620, food: 300, transport: 60, healthcare: 80, education: 450, internet: 35, entertainment: 230,
    avgSalary: 480, taxRate: 20,
    safety: 44, healthcareScore: 56, qualityOfLife: 56, purchasingPower: 24, walkability: 52, publicTransport: 44,
    airQuality: 38, greenSpaces: 42, internetSpeed: 90, englishFriendly: 86, remoteWork: 80, nightlife: 80,
    schools: 60, jobMarket: 54, beachKm: 5, intlAirport: true,
  },
  {
    id: "telaviv", name: "Tel Aviv", country: "Israel", photo: PHOTO.telaviv, region: "asia",
    climate: "beach", climateLabelEs: "Mediterráneo cálido", climateLabelEn: "Warm Mediterranean",
    housing: 2200, food: 620, transport: 70, healthcare: 110, education: 600, internet: 35, entertainment: 460,
    avgSalary: 3300, taxRate: 28,
    safety: 62, healthcareScore: 84, qualityOfLife: 80, purchasingPower: 58, walkability: 88, publicTransport: 74,
    airQuality: 66, greenSpaces: 64, internetSpeed: 180, englishFriendly: 88, remoteWork: 88, nightlife: 92,
    schools: 80, jobMarket: 86, beachKm: 0, intlAirport: true,
  },
  {
    id: "abudhabi", name: "Abu Dabi", country: "Emiratos Árabes", photo: PHOTO.abudhabi, region: "asia",
    climate: "warm", climateLabelEs: "Desértico", climateLabelEn: "Desert",
    housing: 1700, food: 500, transport: 150, healthcare: 150, education: 700, internet: 60, entertainment: 400,
    avgSalary: 4200, taxRate: 0,
    safety: 90, healthcareScore: 82, qualityOfLife: 82, purchasingPower: 80, walkability: 50, publicTransport: 52,
    airQuality: 58, greenSpaces: 54, internetSpeed: 220, englishFriendly: 90, remoteWork: 86, nightlife: 60,
    schools: 80, jobMarket: 82, beachKm: 1, intlAirport: true,
  },
  {
    id: "bengaluru", name: "Bengaluru", country: "India", photo: PHOTO.bengaluru, region: "asia",
    climate: "warm", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 450, food: 220, transport: 45, healthcare: 60, education: 400, internet: 20, entertainment: 190,
    avgSalary: 600, taxRate: 20,
    safety: 58, healthcareScore: 60, qualityOfLife: 60, purchasingPower: 30, walkability: 54, publicTransport: 52,
    airQuality: 40, greenSpaces: 66, internetSpeed: 100, englishFriendly: 86, remoteWork: 84, nightlife: 78,
    schools: 72, jobMarket: 86, beachKm: 300, intlAirport: true,
  },
  {
    id: "chiangmai", name: "Chiang Mai", country: "Tailandia", photo: PHOTO.chiangmai, region: "asia",
    climate: "warm", climateLabelEs: "Tropical de montaña", climateLabelEn: "Mountain tropical",
    housing: 380, food: 240, transport: 40, healthcare: 70, education: 350, internet: 20, entertainment: 190,
    avgSalary: 450, taxRate: 10,
    safety: 74, healthcareScore: 66, qualityOfLife: 74, purchasingPower: 26, walkability: 62, publicTransport: 42,
    airQuality: 34, greenSpaces: 78, internetSpeed: 120, englishFriendly: 58, remoteWork: 94, nightlife: 68,
    schools: 58, jobMarket: 40, beachKm: 650, intlAirport: true,
  },
  {
    id: "brisbane", name: "Brisbane", country: "Australia", photo: PHOTO.brisbane, region: "asia",
    climate: "warm", climateLabelEs: "Subtropical soleado", climateLabelEn: "Sunny subtropical",
    housing: 1750, food: 560, transport: 120, healthcare: 120, education: 700, internet: 55, entertainment: 420,
    avgSalary: 3900, taxRate: 28,
    safety: 80, healthcareScore: 86, qualityOfLife: 86, purchasingPower: 70, walkability: 72, publicTransport: 70,
    airQuality: 86, greenSpaces: 82, internetSpeed: 120, englishFriendly: 100, remoteWork: 84, nightlife: 74,
    schools: 84, jobMarket: 80, beachKm: 20, intlAirport: true,
  },
  {
    id: "accra", name: "Accra", country: "Ghana", photo: PHOTO.accra, region: "africa",
    climate: "warm", climateLabelEs: "Tropical costero", climateLabelEn: "Coastal tropical",
    housing: 700, food: 280, transport: 50, healthcare: 80, education: 450, internet: 40, entertainment: 200,
    avgSalary: 400, taxRate: 20,
    safety: 58, healthcareScore: 50, qualityOfLife: 58, purchasingPower: 20, walkability: 50, publicTransport: 40,
    airQuality: 44, greenSpaces: 48, internetSpeed: 60, englishFriendly: 96, remoteWork: 72, nightlife: 76,
    schools: 52, jobMarket: 48, beachKm: 0, intlAirport: true,
  },
  {
    id: "lagos", name: "Lagos", country: "Nigeria", photo: PHOTO.lagos, region: "africa",
    climate: "warm", climateLabelEs: "Tropical húmedo", climateLabelEn: "Humid tropical",
    housing: 800, food: 300, transport: 60, healthcare: 90, education: 500, internet: 50, entertainment: 220,
    avgSalary: 380, taxRate: 21,
    safety: 32, healthcareScore: 44, qualityOfLife: 48, purchasingPower: 18, walkability: 44, publicTransport: 34,
    airQuality: 32, greenSpaces: 40, internetSpeed: 50, englishFriendly: 96, remoteWork: 64, nightlife: 84,
    schools: 48, jobMarket: 56, beachKm: 0, intlAirport: true,
  },
  {
    id: "kigali", name: "Kigali", country: "Ruanda", photo: PHOTO.kigali, region: "africa",
    climate: "temperate", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 450, food: 220, transport: 35, healthcare: 60, education: 380, internet: 35, entertainment: 160,
    avgSalary: 320, taxRate: 25,
    safety: 78, healthcareScore: 54, qualityOfLife: 66, purchasingPower: 18, walkability: 56, publicTransport: 46,
    airQuality: 66, greenSpaces: 72, internetSpeed: 60, englishFriendly: 80, remoteWork: 74, nightlife: 52,
    schools: 54, jobMarket: 44, beachKm: 1200, intlAirport: true,
  },
  {
    id: "casablanca", name: "Casablanca", country: "Marruecos", photo: PHOTO.casablanca, region: "africa",
    climate: "beach", climateLabelEs: "Mediterráneo atlántico", climateLabelEn: "Atlantic Mediterranean",
    housing: 520, food: 260, transport: 35, healthcare: 60, education: 320, internet: 25, entertainment: 190,
    avgSalary: 480, taxRate: 22,
    safety: 60, healthcareScore: 58, qualityOfLife: 64, purchasingPower: 24, walkability: 66, publicTransport: 58,
    airQuality: 52, greenSpaces: 50, internetSpeed: 70, englishFriendly: 52, remoteWork: 74, nightlife: 62,
    schools: 58, jobMarket: 54, beachKm: 0, intlAirport: true,
  },
  {
    id: "hamburg", name: "Hamburgo", country: "Alemania", photo: PHOTO.hamburg, region: "europe",
    climate: "cold", climateLabelEs: "Oceánico frío", climateLabelEn: "Cold oceanic",
    housing: 1250, food: 470, transport: 60, healthcare: 110, education: 320, internet: 40, entertainment: 340,
    avgSalary: 3000, taxRate: 38,
    safety: 84, healthcareScore: 88, qualityOfLife: 88, purchasingPower: 68, walkability: 86, publicTransport: 90,
    airQuality: 78, greenSpaces: 82, internetSpeed: 160, englishFriendly: 78, remoteWork: 84, nightlife: 84,
    schools: 84, jobMarket: 84, beachKm: 90, intlAirport: true,
  },
  {
    id: "zagreb", name: "Zagreb", country: "Croacia", photo: PHOTO.zagreb, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 620, food: 320, transport: 30, healthcare: 70, education: 220, internet: 25, entertainment: 220,
    avgSalary: 1200, taxRate: 26,
    safety: 84, healthcareScore: 74, qualityOfLife: 78, purchasingPower: 44, walkability: 84, publicTransport: 78,
    airQuality: 66, greenSpaces: 76, internetSpeed: 140, englishFriendly: 70, remoteWork: 86, nightlife: 74,
    schools: 74, jobMarket: 58, beachKm: 120, intlAirport: true,
  },
  {
    id: "ljubljana", name: "Liubliana", country: "Eslovenia", photo: PHOTO.ljubljana, region: "europe",
    climate: "cold", climateLabelEs: "Alpino continental", climateLabelEn: "Continental alpine",
    housing: 750, food: 350, transport: 30, healthcare: 70, education: 240, internet: 30, entertainment: 240,
    avgSalary: 1500, taxRate: 30,
    safety: 90, healthcareScore: 80, qualityOfLife: 86, purchasingPower: 50, walkability: 88, publicTransport: 76,
    airQuality: 72, greenSpaces: 90, internetSpeed: 150, englishFriendly: 78, remoteWork: 84, nightlife: 68,
    schools: 80, jobMarket: 62, beachKm: 90, intlAirport: true,
  },
  {
    id: "tallinn", name: "Tallin", country: "Estonia", photo: PHOTO.tallinn, region: "europe",
    climate: "cold", climateLabelEs: "Báltico frío", climateLabelEn: "Cold Baltic",
    housing: 800, food: 360, transport: 30, healthcare: 60, education: 200, internet: 20, entertainment: 240,
    avgSalary: 1700, taxRate: 25,
    safety: 86, healthcareScore: 78, qualityOfLife: 84, purchasingPower: 54, walkability: 86, publicTransport: 82,
    airQuality: 84, greenSpaces: 80, internetSpeed: 240, englishFriendly: 80, remoteWork: 92, nightlife: 70,
    schools: 82, jobMarket: 70, beachKm: 1, intlAirport: true,
  },
  {
    id: "riga", name: "Riga", country: "Letonia", photo: PHOTO.riga, region: "europe",
    climate: "cold", climateLabelEs: "Báltico frío", climateLabelEn: "Cold Baltic",
    housing: 650, food: 330, transport: 25, healthcare: 60, education: 200, internet: 20, entertainment: 210,
    avgSalary: 1350, taxRate: 26,
    safety: 80, healthcareScore: 74, qualityOfLife: 78, purchasingPower: 46, walkability: 86, publicTransport: 84,
    airQuality: 80, greenSpaces: 80, internetSpeed: 220, englishFriendly: 76, remoteWork: 88, nightlife: 76,
    schools: 76, jobMarket: 60, beachKm: 10, intlAirport: true,
  },
  {
    id: "vilnius", name: "Vilna", country: "Lituania", photo: PHOTO.vilnius, region: "europe",
    climate: "cold", climateLabelEs: "Báltico frío", climateLabelEn: "Cold Baltic",
    housing: 700, food: 330, transport: 25, healthcare: 60, education: 200, internet: 20, entertainment: 210,
    avgSalary: 1450, taxRate: 26,
    safety: 84, healthcareScore: 76, qualityOfLife: 80, purchasingPower: 50, walkability: 84, publicTransport: 80,
    airQuality: 78, greenSpaces: 84, internetSpeed: 230, englishFriendly: 74, remoteWork: 90, nightlife: 74,
    schools: 78, jobMarket: 66, beachKm: 300, intlAirport: true,
  },
  {
    id: "bucharest", name: "Bucarest", country: "Rumanía", photo: PHOTO.bucharest, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 550, food: 300, transport: 25, healthcare: 60, education: 220, internet: 15, entertainment: 210,
    avgSalary: 1150, taxRate: 20,
    safety: 74, healthcareScore: 70, qualityOfLife: 72, purchasingPower: 44, walkability: 78, publicTransport: 80,
    airQuality: 58, greenSpaces: 66, internetSpeed: 300, englishFriendly: 70, remoteWork: 88, nightlife: 84,
    schools: 72, jobMarket: 64, beachKm: 220, intlAirport: true,
  },
  {
    id: "sofia", name: "Sofía", country: "Bulgaria", photo: PHOTO.sofia, region: "europe",
    climate: "cold", climateLabelEs: "Continental de montaña", climateLabelEn: "Mountain continental",
    housing: 500, food: 280, transport: 25, healthcare: 55, education: 200, internet: 15, entertainment: 190,
    avgSalary: 1050, taxRate: 20,
    safety: 74, healthcareScore: 68, qualityOfLife: 72, purchasingPower: 42, walkability: 80, publicTransport: 78,
    airQuality: 54, greenSpaces: 74, internetSpeed: 220, englishFriendly: 66, remoteWork: 88, nightlife: 78,
    schools: 70, jobMarket: 58, beachKm: 300, intlAirport: true,
  },
  {
    id: "malaga", name: "Málaga", country: "España", photo: PHOTO.malaga, region: "europe",
    climate: "beach", climateLabelEs: "Mediterráneo cálido", climateLabelEn: "Warm Mediterranean",
    housing: 1100, food: 420, transport: 45, healthcare: 80, education: 240, internet: 32, entertainment: 300,
    avgSalary: 1900, taxRate: 30,
    safety: 80, healthcareScore: 86, qualityOfLife: 86, purchasingPower: 58, walkability: 86, publicTransport: 74,
    airQuality: 78, greenSpaces: 72, internetSpeed: 180, englishFriendly: 66, remoteWork: 90, nightlife: 82,
    schools: 78, jobMarket: 60, beachKm: 0, intlAirport: true,
  },
  {
    id: "seville", name: "Sevilla", country: "España", photo: PHOTO.seville, region: "europe",
    climate: "warm", climateLabelEs: "Mediterráneo seco", climateLabelEn: "Dry Mediterranean",
    housing: 850, food: 390, transport: 40, healthcare: 80, education: 230, internet: 30, entertainment: 280,
    avgSalary: 1750, taxRate: 30,
    safety: 80, healthcareScore: 86, qualityOfLife: 84, purchasingPower: 56, walkability: 88, publicTransport: 76,
    airQuality: 76, greenSpaces: 70, internetSpeed: 170, englishFriendly: 58, remoteWork: 86, nightlife: 86,
    schools: 76, jobMarket: 56, beachKm: 90, intlAirport: true,
  },
  {
    id: "nice", name: "Niza", country: "Francia", photo: PHOTO.nice, region: "europe",
    climate: "beach", climateLabelEs: "Mediterráneo", climateLabelEn: "Mediterranean",
    housing: 1500, food: 500, transport: 50, healthcare: 90, education: 320, internet: 35, entertainment: 360,
    avgSalary: 2400, taxRate: 33,
    safety: 74, healthcareScore: 88, qualityOfLife: 84, purchasingPower: 58, walkability: 86, publicTransport: 78,
    airQuality: 80, greenSpaces: 74, internetSpeed: 160, englishFriendly: 66, remoteWork: 84, nightlife: 74,
    schools: 80, jobMarket: 64, beachKm: 0, intlAirport: true,
  },
  {
    id: "florence", name: "Florencia", country: "Italia", photo: PHOTO.florence, region: "europe",
    climate: "temperate", climateLabelEs: "Mediterráneo interior", climateLabelEn: "Inland Mediterranean",
    housing: 1200, food: 450, transport: 45, healthcare: 80, education: 300, internet: 32, entertainment: 320,
    avgSalary: 1900, taxRate: 36,
    safety: 80, healthcareScore: 84, qualityOfLife: 84, purchasingPower: 52, walkability: 90, publicTransport: 74,
    airQuality: 68, greenSpaces: 70, internetSpeed: 140, englishFriendly: 64, remoteWork: 82, nightlife: 74,
    schools: 78, jobMarket: 58, beachKm: 80, intlAirport: true,
  },
  {
    id: "calgary", name: "Calgary", country: "Canadá", photo: PHOTO.calgary, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental seco", climateLabelEn: "Dry continental",
    housing: 1350, food: 500, transport: 100, healthcare: 80, education: 420, internet: 60, entertainment: 340,
    avgSalary: 3200, taxRate: 29,
    safety: 80, healthcareScore: 84, qualityOfLife: 84, purchasingPower: 66, walkability: 64, publicTransport: 64,
    airQuality: 84, greenSpaces: 80, internetSpeed: 190, englishFriendly: 96, remoteWork: 84, nightlife: 70,
    schools: 84, jobMarket: 78, beachKm: 1000, intlAirport: true,
  },
  {
    id: "nashville", name: "Nashville", country: "Estados Unidos", photo: PHOTO.nashville, region: "northamerica",
    climate: "warm", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 1600, food: 540, transport: 180, healthcare: 400, education: 780, internet: 65, entertainment: 420,
    avgSalary: 4200, taxRate: 24,
    safety: 60, healthcareScore: 76, qualityOfLife: 78, purchasingPower: 78, walkability: 58, publicTransport: 44,
    airQuality: 76, greenSpaces: 74, internetSpeed: 240, englishFriendly: 100, remoteWork: 86, nightlife: 92,
    schools: 76, jobMarket: 84, beachKm: 600, intlAirport: true,
  },
  {
    id: "phoenix", name: "Phoenix", country: "Estados Unidos", photo: PHOTO.phoenix, region: "northamerica",
    climate: "warm", climateLabelEs: "Desértico", climateLabelEn: "Desert",
    housing: 1550, food: 520, transport: 190, healthcare: 400, education: 760, internet: 65, entertainment: 400,
    avgSalary: 4300, taxRate: 26,
    safety: 58, healthcareScore: 76, qualityOfLife: 74, purchasingPower: 78, walkability: 50, publicTransport: 40,
    airQuality: 62, greenSpaces: 58, internetSpeed: 240, englishFriendly: 100, remoteWork: 84, nightlife: 74,
    schools: 74, jobMarket: 82, beachKm: 500, intlAirport: true,
  },
  {
    id: "raleigh", name: "Raleigh", country: "Estados Unidos", photo: PHOTO.raleigh, region: "northamerica",
    climate: "warm", climateLabelEs: "Subtropical templado", climateLabelEn: "Mild subtropical",
    housing: 1500, food: 520, transport: 180, healthcare: 400, education: 780, internet: 65, entertainment: 380,
    avgSalary: 4400, taxRate: 26,
    safety: 72, healthcareScore: 80, qualityOfLife: 82, purchasingPower: 80, walkability: 54, publicTransport: 44,
    airQuality: 80, greenSpaces: 84, internetSpeed: 250, englishFriendly: 100, remoteWork: 88, nightlife: 68,
    schools: 86, jobMarket: 86, beachKm: 200, intlAirport: true,
  },
  {
    id: "monterrey", name: "Monterrey", country: "México", photo: PHOTO.monterrey, region: "latam",
    climate: "warm", climateLabelEs: "Semiárido cálido", climateLabelEn: "Warm semi-arid",
    housing: 680, food: 320, transport: 60, healthcare: 90, education: 380, internet: 30, entertainment: 250,
    avgSalary: 950, taxRate: 22,
    safety: 48, healthcareScore: 66, qualityOfLife: 70, purchasingPower: 36, walkability: 58, publicTransport: 54,
    airQuality: 48, greenSpaces: 58, internetSpeed: 150, englishFriendly: 48, remoteWork: 80, nightlife: 80,
    schools: 70, jobMarket: 76, beachKm: 300, intlAirport: true,
  },
  {
    id: "cancun", name: "Cancún", country: "México", photo: PHOTO.cancun, region: "latam",
    climate: "beach", climateLabelEs: "Tropical caribeño", climateLabelEn: "Caribbean tropical",
    housing: 750, food: 340, transport: 50, healthcare: 90, education: 350, internet: 30, entertainment: 280,
    avgSalary: 750, taxRate: 20,
    safety: 54, healthcareScore: 62, qualityOfLife: 72, purchasingPower: 30, walkability: 60, publicTransport: 48,
    airQuality: 74, greenSpaces: 64, internetSpeed: 120, englishFriendly: 60, remoteWork: 84, nightlife: 90,
    schools: 62, jobMarket: 58, beachKm: 0, intlAirport: true,
  },
  {
    id: "florianopolis", name: "Florianópolis", country: "Brasil", photo: PHOTO.florianopolis, region: "latam",
    climate: "beach", climateLabelEs: "Subtropical costero", climateLabelEn: "Coastal subtropical",
    housing: 750, food: 350, transport: 55, healthcare: 100, education: 400, internet: 30, entertainment: 270,
    avgSalary: 900, taxRate: 23,
    safety: 60, healthcareScore: 70, qualityOfLife: 78, purchasingPower: 32, walkability: 66, publicTransport: 52,
    airQuality: 80, greenSpaces: 80, internetSpeed: 150, englishFriendly: 42, remoteWork: 84, nightlife: 78,
    schools: 70, jobMarket: 58, beachKm: 0, intlAirport: true,
  },
  {
    id: "cordoba_ar", name: "Córdoba", country: "Argentina", photo: PHOTO.cordoba_ar, region: "latam",
    climate: "temperate", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 420, food: 260, transport: 35, healthcare: 70, education: 260, internet: 25, entertainment: 200,
    avgSalary: 600, taxRate: 25,
    safety: 56, healthcareScore: 72, qualityOfLife: 70, purchasingPower: 30, walkability: 74, publicTransport: 64,
    airQuality: 64, greenSpaces: 70, internetSpeed: 130, englishFriendly: 40, remoteWork: 80, nightlife: 84,
    schools: 70, jobMarket: 54, beachKm: 700, intlAirport: true,
  },
  {
    id: "laspaz", name: "La Paz", country: "Bolivia", photo: PHOTO.laspaz, region: "latam",
    climate: "cold", climateLabelEs: "Andino de altura", climateLabelEn: "High Andean",
    housing: 380, food: 220, transport: 30, healthcare: 60, education: 240, internet: 25, entertainment: 170,
    avgSalary: 450, taxRate: 15,
    safety: 52, healthcareScore: 56, qualityOfLife: 62, purchasingPower: 24, walkability: 66, publicTransport: 62,
    airQuality: 58, greenSpaces: 54, internetSpeed: 70, englishFriendly: 34, remoteWork: 72, nightlife: 62,
    schools: 56, jobMarket: 44, beachKm: 1000, intlAirport: true,
  },
  {
    id: "punta", name: "Punta del Este", country: "Uruguay", photo: PHOTO.punta, region: "latam",
    climate: "beach", climateLabelEs: "Atlántico templado", climateLabelEn: "Temperate Atlantic",
    housing: 900, food: 380, transport: 45, healthcare: 110, education: 360, internet: 35, entertainment: 300,
    avgSalary: 1100, taxRate: 26,
    safety: 74, healthcareScore: 76, qualityOfLife: 80, purchasingPower: 36, walkability: 72, publicTransport: 50,
    airQuality: 88, greenSpaces: 80, internetSpeed: 120, englishFriendly: 52, remoteWork: 80, nightlife: 72,
    schools: 72, jobMarket: 46, beachKm: 0, intlAirport: true,
  },
  {
    id: "hongkong", name: "Hong Kong", country: "China", photo: PHOTO.hongkong, region: "asia",
    climate: "warm", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 2400, food: 620, transport: 60, healthcare: 150, education: 900, internet: 45, entertainment: 460,
    avgSalary: 3600, taxRate: 15,
    safety: 88, healthcareScore: 86, qualityOfLife: 80, purchasingPower: 62, walkability: 92, publicTransport: 98,
    airQuality: 58, greenSpaces: 72, internetSpeed: 260, englishFriendly: 84, remoteWork: 84, nightlife: 86,
    schools: 86, jobMarket: 90, beachKm: 2, intlAirport: true,
  },
  {
    id: "shanghai", name: "Shanghái", country: "China", photo: PHOTO.shanghai, region: "asia",
    climate: "temperate", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 1200, food: 420, transport: 45, healthcare: 110, education: 700, internet: 20, entertainment: 320,
    avgSalary: 1900, taxRate: 20,
    safety: 86, healthcareScore: 76, qualityOfLife: 74, purchasingPower: 50, walkability: 84, publicTransport: 96,
    airQuality: 44, greenSpaces: 64, internetSpeed: 220, englishFriendly: 42, remoteWork: 72, nightlife: 84,
    schools: 78, jobMarket: 86, beachKm: 30, intlAirport: true,
  },
  {
    id: "phuket", name: "Phuket", country: "Tailandia", photo: PHOTO.phuket, region: "asia",
    climate: "beach", climateLabelEs: "Tropical isleño", climateLabelEn: "Island tropical",
    housing: 600, food: 280, transport: 60, healthcare: 80, education: 500, internet: 25, entertainment: 250,
    avgSalary: 500, taxRate: 10,
    safety: 72, healthcareScore: 64, qualityOfLife: 74, purchasingPower: 26, walkability: 48, publicTransport: 36,
    airQuality: 72, greenSpaces: 74, internetSpeed: 110, englishFriendly: 62, remoteWork: 90, nightlife: 86,
    schools: 54, jobMarket: 42, beachKm: 0, intlAirport: true,
  },
  {
    id: "danang", name: "Da Nang", country: "Vietnam", photo: PHOTO.danang, region: "asia",
    climate: "beach", climateLabelEs: "Tropical costero", climateLabelEn: "Coastal tropical",
    housing: 420, food: 240, transport: 40, healthcare: 70, education: 400, internet: 20, entertainment: 180,
    avgSalary: 480, taxRate: 14,
    safety: 76, healthcareScore: 58, qualityOfLife: 70, purchasingPower: 26, walkability: 60, publicTransport: 42,
    airQuality: 58, greenSpaces: 66, internetSpeed: 140, englishFriendly: 44, remoteWork: 90, nightlife: 72,
    schools: 56, jobMarket: 50, beachKm: 0, intlAirport: true,
  },
  {
    id: "tbilisi", name: "Tiflis", country: "Georgia", photo: PHOTO.tbilisi, region: "asia",
    climate: "temperate", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 520, food: 280, transport: 25, healthcare: 60, education: 300, internet: 20, entertainment: 200,
    avgSalary: 600, taxRate: 20,
    safety: 76, healthcareScore: 60, qualityOfLife: 70, purchasingPower: 34, walkability: 76, publicTransport: 64,
    airQuality: 56, greenSpaces: 66, internetSpeed: 120, englishFriendly: 56, remoteWork: 88, nightlife: 80,
    schools: 62, jobMarket: 52, beachKm: 300, intlAirport: true,
  },
  {
    id: "istanbul", name: "Estambul", country: "Turquía", photo: PHOTO.istanbul, region: "asia",
    climate: "temperate", climateLabelEs: "Mediterráneo templado", climateLabelEn: "Mild Mediterranean",
    housing: 600, food: 300, transport: 35, healthcare: 70, education: 400, internet: 20, entertainment: 240,
    avgSalary: 700, taxRate: 25,
    safety: 58, healthcareScore: 68, qualityOfLife: 68, purchasingPower: 34, walkability: 80, publicTransport: 84,
    airQuality: 48, greenSpaces: 60, internetSpeed: 90, englishFriendly: 44, remoteWork: 80, nightlife: 86,
    schools: 68, jobMarket: 66, beachKm: 1, intlAirport: true,
  },
  {
    id: "doha", name: "Doha", country: "Catar", photo: PHOTO.doha, region: "asia",
    climate: "warm", climateLabelEs: "Desértico", climateLabelEn: "Desert",
    housing: 1600, food: 480, transport: 140, healthcare: 140, education: 750, internet: 60, entertainment: 380,
    avgSalary: 4500, taxRate: 0,
    safety: 90, healthcareScore: 80, qualityOfLife: 80, purchasingPower: 80, walkability: 46, publicTransport: 50,
    airQuality: 54, greenSpaces: 50, internetSpeed: 200, englishFriendly: 86, remoteWork: 82, nightlife: 54,
    schools: 80, jobMarket: 84, beachKm: 1, intlAirport: true,
  },
  {
    id: "perth", name: "Perth", country: "Australia", photo: PHOTO.perth, region: "asia",
    climate: "beach", climateLabelEs: "Mediterráneo cálido", climateLabelEn: "Warm Mediterranean",
    housing: 1650, food: 560, transport: 120, healthcare: 120, education: 700, internet: 55, entertainment: 400,
    avgSalary: 3800, taxRate: 28,
    safety: 82, healthcareScore: 86, qualityOfLife: 86, purchasingPower: 70, walkability: 68, publicTransport: 64,
    airQuality: 92, greenSpaces: 84, internetSpeed: 110, englishFriendly: 100, remoteWork: 80, nightlife: 70,
    schools: 84, jobMarket: 78, beachKm: 0, intlAirport: true,
  },
  {
    id: "wellington", name: "Wellington", country: "Nueva Zelanda", photo: PHOTO.wellington, region: "asia",
    climate: "temperate", climateLabelEs: "Oceánico ventoso", climateLabelEn: "Windy oceanic",
    housing: 1400, food: 520, transport: 90, healthcare: 90, education: 500, internet: 50, entertainment: 340,
    avgSalary: 3000, taxRate: 30,
    safety: 86, healthcareScore: 84, qualityOfLife: 86, purchasingPower: 64, walkability: 86, publicTransport: 76,
    airQuality: 96, greenSpaces: 88, internetSpeed: 140, englishFriendly: 100, remoteWork: 84, nightlife: 70,
    schools: 86, jobMarket: 72, beachKm: 0, intlAirport: true,
  },
  {
    id: "durban", name: "Durban", country: "Sudáfrica", photo: PHOTO.durban, region: "africa",
    climate: "beach", climateLabelEs: "Subtropical costero", climateLabelEn: "Coastal subtropical",
    housing: 600, food: 300, transport: 60, healthcare: 120, education: 400, internet: 40, entertainment: 220,
    avgSalary: 700, taxRate: 26,
    safety: 38, healthcareScore: 62, qualityOfLife: 64, purchasingPower: 26, walkability: 54, publicTransport: 42,
    airQuality: 66, greenSpaces: 66, internetSpeed: 60, englishFriendly: 92, remoteWork: 74, nightlife: 72,
    schools: 62, jobMarket: 52, beachKm: 0, intlAirport: true,
  },
  {
    id: "dakar", name: "Dakar", country: "Senegal", photo: PHOTO.dakar, region: "africa",
    climate: "beach", climateLabelEs: "Sahariano costero", climateLabelEn: "Coastal Sahel",
    housing: 620, food: 280, transport: 50, healthcare: 80, education: 420, internet: 45, entertainment: 200,
    avgSalary: 420, taxRate: 20,
    safety: 58, healthcareScore: 50, qualityOfLife: 58, purchasingPower: 20, walkability: 56, publicTransport: 42,
    airQuality: 56, greenSpaces: 50, internetSpeed: 50, englishFriendly: 40, remoteWork: 70, nightlife: 70,
    schools: 52, jobMarket: 46, beachKm: 0, intlAirport: true,
  },
  {
    id: "zanzibar", name: "Zanzíbar", country: "Tanzania", photo: PHOTO.zanzibar, region: "africa",
    climate: "beach", climateLabelEs: "Tropical isleño", climateLabelEn: "Island tropical",
    housing: 480, food: 250, transport: 40, healthcare: 70, education: 380, internet: 45, entertainment: 200,
    avgSalary: 350, taxRate: 18,
    safety: 66, healthcareScore: 48, qualityOfLife: 64, purchasingPower: 18, walkability: 58, publicTransport: 36,
    airQuality: 76, greenSpaces: 72, internetSpeed: 40, englishFriendly: 72, remoteWork: 76, nightlife: 60,
    schools: 48, jobMarket: 40, beachKm: 0, intlAirport: true,
  },
];
