/**
 * Ciudades adicionales del Lifestyle Simulator.
 * Mismas fuentes y criterios que `lifestyle-cities.ts`.
 */
import type { CityData } from "./lifestyle-cities";
const PHOTO = {
  hamburg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/HH_Alsterarkaden_pano1.jpg/1920px-HH_Alsterarkaden_pano1.jpg",
  zagreb: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Zagreb_2015_-_Zagreba%C4%8Dka_katedrala_-_pogled_s_Gornjeg_Grada_%28Zagreb_Cathedral_-_view_from_Upper_Town%29_-_panoramio.jpg/1920px-Zagreb_2015_-_Zagreba%C4%8Dka_katedrala_-_pogled_s_Gornjeg_Grada_%28Zagreb_Cathedral_-_view_from_Upper_Town%29_-_panoramio.jpg",
  ljubljana: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Edificio_de_administraci%C3%B3n_de_la_Rep%C3%BAblica_de_Eslovenia%2C_Liubliana%2C_Eslovenia%2C_2017-04-14%2C_DD_32-34_HDR.jpg/1920px-Edificio_de_administraci%C3%B3n_de_la_Rep%C3%BAblica_de_Eslovenia%2C_Liubliana%2C_Eslovenia%2C_2017-04-14%2C_DD_32-34_HDR.jpg",
  tallinn: "https://upload.wikimedia.org/wikipedia/commons/1/12/Frozen_Capital_%2846042776311%29.jpg",
  riga: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Gogojo_iela_and_Riga_skyline_from_Latvian_Academy_of_Sciences_Observation_deck.jpg/1920px-Gogojo_iela_and_Riga_skyline_from_Latvian_Academy_of_Sciences_Observation_deck.jpg",
  vilnius: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Vilnius_Modern_Skyline_At_Dusk%2C_Lithuania_-_Diliff.jpg/1920px-Vilnius_Modern_Skyline_At_Dusk%2C_Lithuania_-_Diliff.jpg",
  bucharest: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Palacio_CEC%2C_Bucarest%2C_Ruman%C3%ADa%2C_2016-05-29%2C_DD_65.jpg/1920px-Palacio_CEC%2C_Bucarest%2C_Ruman%C3%ADa%2C_2016-05-29%2C_DD_65.jpg",
  sofia: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Dallas_llanuras_americanas_%28cropped%29.jpg/1920px-Dallas_llanuras_americanas_%28cropped%29.jpg",
  malaga: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/M%C3%A1laga_skyline.jpg/1920px-M%C3%A1laga_skyline.jpg",
  seville: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/19060879124_a5eac59dea_o_feria_abril_sevilla_2013.jpg/1920px-19060879124_a5eac59dea_o_feria_abril_sevilla_2013.jpg",
  nice: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Caux_-_Belv%C3%A9d%C3%A8re_Route_de_Nizas.jpg/1920px-Caux_-_Belv%C3%A9d%C3%A8re_Route_de_Nizas.jpg",
  florence: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Florencia_skyline%282017%29.jpg/1920px-Florencia_skyline%282017%29.jpg",
  calgary: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/1978_Skyline_of_Calgary_01.jpg/1920px-1978_Skyline_of_Calgary_01.jpg",
  nashville: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/City_of_Nashville_skyline_from_Gulch_-_Oct_2019.jpg/1920px-City_of_Nashville_skyline_from_Gulch_-_Oct_2019.jpg",
  phoenix: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Dortmund_-_PO-Phoenix-See_%2B_H%C3%B6rde_01_ies.jpg/1920px-Dortmund_-_PO-Phoenix-See_%2B_H%C3%B6rde_01_ies.jpg",
  raleigh: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Raleigh%2C_NC.jpg/1920px-Raleigh%2C_NC.jpg",
  monterrey: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Monterrey_Rascacielos.jpg/1920px-Monterrey_Rascacielos.jpg",
  cancun: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Cancun_Skyline%2C_view_from_Isla_Mujeres_south_coast_-_Quintana_Roo_Mexico_March_2020.jpg/1920px-Cancun_Skyline%2C_view_from_Isla_Mujeres_south_coast_-_Quintana_Roo_Mexico_March_2020.jpg",
  florianopolis: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Sunrise_city.jpg/1920px-Sunrise_city.jpg",
  cordoba_ar: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Avenida_C%C3%B3rdoba_y_Esmeralda%2C_Buenos_Aires%2C_bajo_la_neblina.jpg/1920px-Avenida_C%C3%B3rdoba_y_Esmeralda%2C_Buenos_Aires%2C_bajo_la_neblina.jpg",
  laspaz: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Centro_de_La_Paz_sobre_la_Avenida_Arce.jpg/1920px-Centro_de_La_Paz_sobre_la_Avenida_Arce.jpg",
  punta: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Skyline_view_of_Punta_del_Este.jpg/1920px-Skyline_view_of_Punta_del_Este.jpg",
  shanghai: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Pudong_Shanghai_November_2017_panorama.jpg/1920px-Pudong_Shanghai_November_2017_panorama.jpg",
  phuket: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Phuket_Thailand_Big-Buddha-of-Phuket-05.jpg/1920px-Phuket_Thailand_Big-Buddha-of-Phuket-05.jpg",
  danang: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Bright_Da_Nang_skyline_%28Unsplash%29.jpg/1920px-Bright_Da_Nang_skyline_%28Unsplash%29.jpg",
  tbilisi: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Vista_de_Tiflis%2C_Georgia%2C_2016-09-29%2C_DD_37.jpg/1920px-Vista_de_Tiflis%2C_Georgia%2C_2016-09-29%2C_DD_37.jpg",
  istanbul: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Galata_Tower_-_Turkey_-_Istanbul_City_-_Tourist_attractions_-_Monument_01.jpg/1920px-Galata_Tower_-_Turkey_-_Istanbul_City_-_Tourist_attractions_-_Monument_01.jpg",
  doha: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Doha_Corniche_Skyline_View_1.jpg/1920px-Doha_Corniche_Skyline_View_1.jpg",
  perth: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Central_Perth_skyline_from_south_perth_at_sunset.jpg/1920px-Central_Perth_skyline_from_south_perth_at_sunset.jpg",
  dakar: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Dakar%2C_Senegal_-_Left_Half_%285662420768%29.jpg/1920px-Dakar%2C_Senegal_-_Left_Half_%285662420768%29.jpg",
  zanzibar: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Old_Fort_of_Zanzibar.jpg/1920px-Old_Fort_of_Zanzibar.jpg",
  hongkong: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Duck_ling_ship_hong_kong.jpg/1920px-Duck_ling_ship_hong_kong.jpg",
  wellington: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Spectra_%26_Full_Moon_from_Mt_Wellington_%289105305933%29.jpg/1920px-Spectra_%26_Full_Moon_from_Mt_Wellington_%289105305933%29.jpg",
  durban: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Durban_from_the_Balcony_%28Dennis_Sylvester_Hurd%29_1.jpg/1920px-Durban_from_the_Balcony_%28Dennis_Sylvester_Hurd%29_1.jpg",
  vienna: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Riesenrad%2C_Prater_14.jpg/1920px-Riesenrad%2C_Prater_14.jpg",
  munich: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Vista_panor%C3%A1mica_desde_Olympiapark%2C_M%C3%BAnich%2C_Alemania_2012-04-28%2C_DD_03.JPG/1920px-Vista_panor%C3%A1mica_desde_Olympiapark%2C_M%C3%BAnich%2C_Alemania_2012-04-28%2C_DD_03.JPG",
  stockholm: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Riksdagen_September_2014_02.jpg/1920px-Riksdagen_September_2014_02.jpg",
  oslo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/OSLO_Norway_2026-06-10_Rooftop_cityscape_view_from_Odd_Fellow_%28Stortingsg_28%29_Munkedamsv._Torstedg%C3%A5rden_Medicus_Slottsparken_Abelhaugen_Henrik_Ibsens_g_roundabout_Frederiks_g_Nationalth._J_Dybwad_University_bus_Distorted_panorama_IMG.jpg/1920px-thumbnail.jpg",
  dublin: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Aviva_Stadium_skyline%29.jpg/1920px-Aviva_Stadium_skyline%29.jpg",
  budapest: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Budapest_nighttime_skyline_%2817051894051%29.jpg/1920px-Budapest_nighttime_skyline_%2817051894051%29.jpg",
  brussels: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Bruselas%2C_Bot%C3%A1nico_01.jpg/1920px-Bruselas%2C_Bot%C3%A1nico_01.jpg",
  edinburgh: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Edimburgo%2C_Escocia_13.jpg/1920px-Edimburgo%2C_Escocia_13.jpg",
  helsinki: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Helsinki_Skyline_%2852432702085%29.jpg/1920px-Helsinki_Skyline_%2852432702085%29.jpg",
  geneva: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Geneve_2005_001_Ork.ch.jpg/1920px-Geneve_2005_001_Ork.ch.jpg",
  seattle: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/SeattleI5Skyline.jpg/1920px-SeattleI5Skyline.jpg",
  boston: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Boston_Skyline_at_Sunset_from_Deer_Island_Lookout.jpg/1920px-Boston_Skyline_at_Sunset_from_Deer_Island_Lookout.jpg",
  sandiego: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Downtown_San_Diego_Skyline_from_Coronado.jpg/1920px-Downtown_San_Diego_Skyline_from_Coronado.jpg",
  montreal: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Kondiaronk_Belvedere%2C_Montreal_city%2C_Canada.jpg/1920px-Kondiaronk_Belvedere%2C_Montreal_city%2C_Canada.jpg",
  losangeles: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Consulate_General_Los_Angeles_Skyline.jpg/1920px-Consulate_General_Los_Angeles_Skyline.jpg",
  denver: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Denver%2C_Colorado_skyline_%28cropped%29.jpg/1920px-Denver%2C_Colorado_skyline_%28cropped%29.jpg",
  guadalajara: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Skyline_Guadalajara_Americas_IMG_20210910_185500.jpg/1920px-Skyline_Guadalajara_Americas_IMG_20210910_185500.jpg",
  sanjose_cr: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Hazy_San_Jose_%2842987234361%29.jpg/1920px-Hazy_San_Jose_%2842987234361%29.jpg",
  cartagena: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Buildings_in_Cartagena%2C_Colombia_01.jpg/1920px-Buildings_in_Cartagena%2C_Colombia_01.jpg",
  quito: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/50_-_Quito_-_D%C3%A9cembre_2008.jpg/1920px-50_-_Quito_-_D%C3%A9cembre_2008.jpg",
  asuncion: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Asunci%C3%B3n_09-06-18.jpg/1920px-Asunci%C3%B3n_09-06-18.jpg",
  osaka: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/20190121_Skyline_from_Osaka_Castle-1.jpg/1920px-20190121_Skyline_from_Osaka_Castle-1.jpg",
  hanoi: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Hanoi_Panoramic.jpg/1920px-Hanoi_Panoramic.jpg",
  manila: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/MANILA_SKYLINE_01.JPG/1920px-MANILA_SKYLINE_01.JPG",
  telaviv: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Skyline_of_Tel_Aviv_%2834324506705%29.jpg/1920px-Skyline_of_Tel_Aviv_%2834324506705%29.jpg",
  abudhabi: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Latvijas_un_AAE_l%C4%ABguma_parakst%C4%AB%C5%A1ana_%286826538444%29.jpg/1920px-Latvijas_un_AAE_l%C4%ABguma_parakst%C4%AB%C5%A1ana_%286826538444%29.jpg",
  bengaluru: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/South_Bengaluru_Skyline_as_seen_from_ISKCON%2C_Banashankari.jpg/1920px-South_Bengaluru_Skyline_as_seen_from_ISKCON%2C_Banashankari.jpg",
  chiangmai: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Chiang_Mai_-_Chiang_Mai_City_Art_and_Cultural_Center_-_0001.jpg/1920px-Chiang_Mai_-_Chiang_Mai_City_Art_and_Cultural_Center_-_0001.jpg",
  brisbane: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Brisbane_Skyline_At_Night.jpg/1920px-Brisbane_Skyline_At_Night.jpg",
  accra: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Accra_Skyline.jpg/1920px-Accra_Skyline.jpg",
  lagos: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Lagos_Island_City_Scape.jpg/1920px-Lagos_Island_City_Scape.jpg",
  kigali: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Kigali2018.jpg/1920px-Kigali2018.jpg",
  casablanca: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Casablanca_%28203660919%29.jpeg/1920px-Casablanca_%28203660919%29.jpeg",
  rotterdam: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/0_8546_Rotterdam_-_Ausblick.jpg/1920px-0_8546_Rotterdam_-_Ausblick.jpg",
  antwerp: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/A_ship_and_a_skyline_in_Antwerp_%2834759978251%29.jpg/1920px-A_ship_and_a_skyline_in_Antwerp_%2834759978251%29.jpg",
  gothenburg: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/View_over_Gothenburg_skyline_from_Skansen_Kronan.jpg/1920px-View_over_Gothenburg_skyline_from_Skansen_Kronan.jpg",
  bratislava: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/The_view_of_the_skyline_from_the_middle_level_of_the_Bratislava_castle_hill.jpg/1920px-The_view_of_the_skyline_from_the_middle_level_of_the_Bratislava_castle_hill.jpg",
  krakow: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/20120923_Krakow_Wawel_0451.jpg/1920px-20120923_Krakow_Wawel_0451.jpg",
  valletta: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Epic_Day_In_Valletta_Harbor.jpg/1920px-Epic_Day_In_Valletta_Harbor.jpg",
  palma: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Mallorca_-_Kathedrale_von_Palma5.jpg/1920px-Mallorca_-_Kathedrale_von_Palma5.jpg",
  bilbao: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bilbao_city_skyline_from_Etxebarria_Park_%2826779657642%29.jpg/1920px-Bilbao_city_skyline_from_Etxebarria_Park_%2826779657642%29.jpg",
  bologna: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Bologna%2C_Italia.jpg/1920px-Bologna%2C_Italia.jpg",
  naples: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Naples_Skyline_at_Venetian_Village_%2837063813004%29.jpg/1920px-Naples_Skyline_at_Venetian_Village_%2837063813004%29.jpg",
  manchester: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Manchester_City_Centre_-_geograph.org.uk_-_4255184.jpg/1920px-Manchester_City_Centre_-_geograph.org.uk_-_4255184.jpg",
  lyon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Lyon%2C_evening_skyline_%2826317247530%29.jpg/1920px-Lyon%2C_evening_skyline_%2826317247530%29.jpg",
  atlanta: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Atlanta_Skyline_-_Illustration.jpg/1920px-Atlanta_Skyline_-_Illustration.jpg",
  dallas: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Dallas_Skyline_-_Illustration.jpg/1920px-Dallas_Skyline_-_Illustration.jpg",
  portland: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Portland%2C_Oregon_Skyline_Sunset_%2822767146885%29.jpg/1920px-Portland%2C_Oregon_Skyline_Sunset_%2822767146885%29.jpg",
  ottawa: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Ottawa_skyline_2018.jpg/1920px-Ottawa_skyline_2018.jpg",
  saltlakecity: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Salt_Lake_City%2C_Utah%2C_United_States_skyline.jpg/1920px-Salt_Lake_City%2C_Utah%2C_United_States_skyline.jpg",
  charlotte: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Timelapse_of_Charlotte_Skyline.jpg/1920px-Timelapse_of_Charlotte_Skyline.jpg",
  curitiba: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Curitiba_Skyline%2C_Parana.jpg/1920px-Curitiba_Skyline%2C_Parana.jpg",
  belohorizonte: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Oblique_side_view_of_S%C3%A3o_Jos%C3%A9_Sanctuary_and_Acaiaca%2C_Belo_Horizonte_Minas_Gerais_Brasil_-_Igreja_S%C3%A3o_Jose_Saint_Joseph_Church_Belo_Horizonte_Minas_Gerais_Brasil_-_Daniel_Guimaraes_Rego_Dan_Rego_Daniel_G.Rego_Daniel_Rego.jpg/1920px-thumbnail.jpg",
  rosario: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Skyline_Rosario.jpg/1920px-Skyline_Rosario.jpg",
  merida: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Merida_Colonnade.jpg/1920px-Merida_Colonnade.jpg",
  santodomingo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Espa%C3%B1a_-_Santo_Domingo_de_Silos_-_Cloister_-_Panorama.jpg/1920px-Espa%C3%B1a_-_Santo_Domingo_de_Silos_-_Cloister_-_Panorama.jpg",
  fukuoka: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/20100718_Fukuoka_2870.jpg/1920px-20100718_Fukuoka_2870.jpg",
  busan: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Busan%2C_KR%2C_October_2019_19.jpg/1920px-Busan%2C_KR%2C_October_2019_19.jpg",
  jakarta: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/City_activity_Jakarta_%28Unsplash%29.jpg/1920px-City_activity_Jakarta_%28Unsplash%29.jpg",
  colombo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/A_view_of_Colombo%27s_dramatic_skyline_at_dusk.jpg/1920px-A_view_of_Colombo%27s_dramatic_skyline_at_dusk.jpg",
  almaty: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Almaty_K%C3%B6k_T%C3%B6be.jpg/1920px-Almaty_K%C3%B6k_T%C3%B6be.jpg",
  goldcoast: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Clouds_over_the_Gold_Coast_skyline.jpg/1920px-Clouds_over_the_Gold_Coast_skyline.jpg",
  adelaide: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Adelaide_%2816205578880%29.jpg/1920px-Adelaide_%2816205578880%29.jpg",
  windhoek: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Christ_Church_in_Windhoek%2C_Namibia.jpg/1920px-Christ_Church_in_Windhoek%2C_Namibia.jpg",
  gaborone: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Gaborone_skyline.JPG/1920px-Gaborone_skyline.JPG",
  addis: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Addis_Ababa_%2816314616596%29.jpg/1920px-Addis_Ababa_%2816314616596%29.jpg",
  alexandria: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Egypt%E2%80%99s_Mediterranean_Coast_%28154431%29.jpg/1920px-Egypt%E2%80%99s_Mediterranean_Coast_%28154431%29.jpg",
};
export const extraCities: CityData[] = [
  {
    id: "rotterdam", name: "Róterdam", country: "Países Bajos", photo: PHOTO.rotterdam, region: "europe",
    climate: "temperate", climateLabelEs: "Marítimo templado", climateLabelEn: "Mild maritime",
    housing: 1500, food: 520, transport: 70, healthcare: 110, education: 320, internet: 40, entertainment: 340,
    avgSalary: 3100, taxRate: 37,
    safety: 78, healthcareScore: 88, qualityOfLife: 84, purchasingPower: 70, walkability: 88, publicTransport: 90,
    airQuality: 72, greenSpaces: 72, internetSpeed: 220, englishFriendly: 88, remoteWork: 88, nightlife: 76,
    schools: 84, jobMarket: 80, beachKm: 25, intlAirport: true,
  },
  {
    id: "antwerp", name: "Amberes", country: "Bélgica", photo: PHOTO.antwerp, region: "europe",
    climate: "temperate", climateLabelEs: "Marítimo templado", climateLabelEn: "Mild maritime",
    housing: 1150, food: 480, transport: 60, healthcare: 100, education: 300, internet: 38, entertainment: 320,
    avgSalary: 2850, taxRate: 40,
    safety: 76, healthcareScore: 86, qualityOfLife: 83, purchasingPower: 68, walkability: 86, publicTransport: 84,
    airQuality: 68, greenSpaces: 70, internetSpeed: 190, englishFriendly: 80, remoteWork: 84, nightlife: 74,
    schools: 82, jobMarket: 74, beachKm: 60, intlAirport: true,
  },
  {
    id: "gothenburg", name: "Gotemburgo", country: "Suecia", photo: PHOTO.gothenburg, region: "europe",
    climate: "cold", climateLabelEs: "Frío costero", climateLabelEn: "Cold coastal",
    housing: 1250, food: 540, transport: 75, healthcare: 60, education: 60, internet: 38, entertainment: 330,
    avgSalary: 3050, taxRate: 33,
    safety: 82, healthcareScore: 88, qualityOfLife: 86, purchasingPower: 72, walkability: 84, publicTransport: 86,
    airQuality: 84, greenSpaces: 88, internetSpeed: 210, englishFriendly: 90, remoteWork: 88, nightlife: 68,
    schools: 88, jobMarket: 76, beachKm: 10, intlAirport: true,
  },
  {
    id: "bratislava", name: "Bratislava", country: "Eslovaquia", photo: PHOTO.bratislava, region: "europe",
    climate: "temperate", climateLabelEs: "Continental", climateLabelEn: "Continental",
    housing: 850, food: 400, transport: 35, healthcare: 55, education: 220, internet: 25, entertainment: 240,
    avgSalary: 1550, taxRate: 29,
    safety: 80, healthcareScore: 76, qualityOfLife: 76, purchasingPower: 54, walkability: 82, publicTransport: 80,
    airQuality: 64, greenSpaces: 70, internetSpeed: 140, englishFriendly: 68, remoteWork: 78, nightlife: 70,
    schools: 74, jobMarket: 64, beachKm: 300, intlAirport: true,
  },
  {
    id: "krakow", name: "Cracovia", country: "Polonia", photo: PHOTO.krakow, region: "europe",
    climate: "cold", climateLabelEs: "Continental frío", climateLabelEn: "Cold continental",
    housing: 800, food: 380, transport: 30, healthcare: 50, education: 240, internet: 22, entertainment: 230,
    avgSalary: 1600, taxRate: 26,
    safety: 82, healthcareScore: 78, qualityOfLife: 80, purchasingPower: 58, walkability: 88, publicTransport: 84,
    airQuality: 54, greenSpaces: 72, internetSpeed: 180, englishFriendly: 66, remoteWork: 84, nightlife: 82,
    schools: 78, jobMarket: 72, beachKm: 450, intlAirport: true,
  },
  {
    id: "valletta", name: "La Valeta", country: "Malta", photo: PHOTO.valletta, region: "europe",
    climate: "beach", climateLabelEs: "Mediterráneo", climateLabelEn: "Mediterranean",
    housing: 1250, food: 470, transport: 45, healthcare: 85, education: 320, internet: 35, entertainment: 300,
    avgSalary: 1750, taxRate: 28,
    safety: 84, healthcareScore: 80, qualityOfLife: 82, purchasingPower: 52, walkability: 86, publicTransport: 66,
    airQuality: 70, greenSpaces: 52, internetSpeed: 120, englishFriendly: 86, remoteWork: 80, nightlife: 68,
    schools: 74, jobMarket: 58, beachKm: 0, intlAirport: true,
  },
  {
    id: "palma", name: "Palma de Mallorca", country: "España", photo: PHOTO.palma, region: "europe",
    climate: "beach", climateLabelEs: "Mediterráneo", climateLabelEn: "Mediterranean",
    housing: 1300, food: 470, transport: 45, healthcare: 85, education: 250, internet: 32, entertainment: 320,
    avgSalary: 1900, taxRate: 30,
    safety: 84, healthcareScore: 85, qualityOfLife: 88, purchasingPower: 56, walkability: 88, publicTransport: 72,
    airQuality: 80, greenSpaces: 74, internetSpeed: 180, englishFriendly: 68, remoteWork: 82, nightlife: 76,
    schools: 76, jobMarket: 56, beachKm: 0, intlAirport: true,
  },
  {
    id: "bilbao", name: "Bilbao", country: "España", photo: PHOTO.bilbao, region: "europe",
    climate: "temperate", climateLabelEs: "Atlántico verde", climateLabelEn: "Green Atlantic",
    housing: 1000, food: 440, transport: 45, healthcare: 80, education: 230, internet: 30, entertainment: 290,
    avgSalary: 2200, taxRate: 31,
    safety: 84, healthcareScore: 88, qualityOfLife: 86, purchasingPower: 62, walkability: 90, publicTransport: 86,
    airQuality: 78, greenSpaces: 82, internetSpeed: 200, englishFriendly: 56, remoteWork: 82, nightlife: 72,
    schools: 80, jobMarket: 64, beachKm: 15, intlAirport: true,
  },
  {
    id: "bologna", name: "Bolonia", country: "Italia", photo: PHOTO.bologna, region: "europe",
    climate: "temperate", climateLabelEs: "Continental húmedo", climateLabelEn: "Humid continental",
    housing: 1050, food: 460, transport: 45, healthcare: 85, education: 260, internet: 30, entertainment: 300,
    avgSalary: 2050, taxRate: 36,
    safety: 78, healthcareScore: 84, qualityOfLife: 82, purchasingPower: 56, walkability: 90, publicTransport: 80,
    airQuality: 58, greenSpaces: 66, internetSpeed: 150, englishFriendly: 58, remoteWork: 78, nightlife: 80,
    schools: 80, jobMarket: 64, beachKm: 120, intlAirport: true,
  },
  {
    id: "naples", name: "Nápoles", country: "Italia", photo: PHOTO.naples, region: "europe",
    climate: "beach", climateLabelEs: "Mediterráneo", climateLabelEn: "Mediterranean",
    housing: 800, food: 400, transport: 40, healthcare: 80, education: 230, internet: 28, entertainment: 260,
    avgSalary: 1650, taxRate: 36,
    safety: 60, healthcareScore: 76, qualityOfLife: 74, purchasingPower: 48, walkability: 86, publicTransport: 68,
    airQuality: 56, greenSpaces: 58, internetSpeed: 130, englishFriendly: 50, remoteWork: 72, nightlife: 84,
    schools: 68, jobMarket: 52, beachKm: 0, intlAirport: true,
  },
  {
    id: "manchester", name: "Mánchester", country: "Reino Unido", photo: PHOTO.manchester, region: "europe",
    climate: "temperate", climateLabelEs: "Lluvioso templado", climateLabelEn: "Mild rainy",
    housing: 1250, food: 520, transport: 90, healthcare: 60, education: 340, internet: 38, entertainment: 340,
    avgSalary: 2900, taxRate: 32,
    safety: 66, healthcareScore: 80, qualityOfLife: 78, purchasingPower: 62, walkability: 84, publicTransport: 80,
    airQuality: 66, greenSpaces: 68, internetSpeed: 190, englishFriendly: 98, remoteWork: 86, nightlife: 86,
    schools: 80, jobMarket: 82, beachKm: 80, intlAirport: true,
  },
  {
    id: "lyon", name: "Lyon", country: "Francia", photo: PHOTO.lyon, region: "europe",
    climate: "temperate", climateLabelEs: "Continental suave", climateLabelEn: "Mild continental",
    housing: 1050, food: 480, transport: 55, healthcare: 90, education: 260, internet: 32, entertainment: 310,
    avgSalary: 2600, taxRate: 34,
    safety: 74, healthcareScore: 88, qualityOfLife: 84, purchasingPower: 62, walkability: 88, publicTransport: 86,
    airQuality: 64, greenSpaces: 72, internetSpeed: 200, englishFriendly: 58, remoteWork: 82, nightlife: 80,
    schools: 84, jobMarket: 74, beachKm: 280, intlAirport: true,
  },
  {
    id: "atlanta", name: "Atlanta", country: "Estados Unidos", photo: PHOTO.atlanta, region: "northamerica",
    climate: "warm", climateLabelEs: "Subtropical", climateLabelEn: "Subtropical",
    housing: 1650, food: 600, transport: 90, healthcare: 420, education: 900, internet: 70, entertainment: 420,
    avgSalary: 4600, taxRate: 27,
    safety: 58, healthcareScore: 74, qualityOfLife: 74, purchasingPower: 72, walkability: 50, publicTransport: 52,
    airQuality: 62, greenSpaces: 70, internetSpeed: 220, englishFriendly: 100, remoteWork: 88, nightlife: 80,
    schools: 76, jobMarket: 88, beachKm: 400, intlAirport: true,
  },
  {
    id: "dallas", name: "Dallas", country: "Estados Unidos", photo: PHOTO.dallas, region: "northamerica",
    climate: "warm", climateLabelEs: "Cálido seco", climateLabelEn: "Warm dry",
    housing: 1550, food: 580, transport: 95, healthcare: 420, education: 880, internet: 70, entertainment: 410,
    avgSalary: 4800, taxRate: 24,
    safety: 60, healthcareScore: 74, qualityOfLife: 74, purchasingPower: 76, walkability: 44, publicTransport: 42,
    airQuality: 60, greenSpaces: 60, internetSpeed: 230, englishFriendly: 100, remoteWork: 88, nightlife: 78,
    schools: 76, jobMarket: 90, beachKm: 450, intlAirport: true,
  },
  {
    id: "portland", name: "Portland", country: "Estados Unidos", photo: PHOTO.portland, region: "northamerica",
    climate: "temperate", climateLabelEs: "Lluvioso templado", climateLabelEn: "Mild rainy",
    housing: 1600, food: 600, transport: 80, healthcare: 430, education: 850, internet: 70, entertainment: 400,
    avgSalary: 4500, taxRate: 29,
    safety: 58, healthcareScore: 76, qualityOfLife: 80, purchasingPower: 70, walkability: 76, publicTransport: 68,
    airQuality: 74, greenSpaces: 86, internetSpeed: 230, englishFriendly: 100, remoteWork: 88, nightlife: 74,
    schools: 78, jobMarket: 78, beachKm: 120, intlAirport: true,
  },
  {
    id: "ottawa", name: "Ottawa", country: "Canadá", photo: PHOTO.ottawa, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental frío", climateLabelEn: "Cold continental",
    housing: 1400, food: 560, transport: 80, healthcare: 60, education: 320, internet: 60, entertainment: 340,
    avgSalary: 3900, taxRate: 30,
    safety: 84, healthcareScore: 84, qualityOfLife: 84, purchasingPower: 70, walkability: 72, publicTransport: 72,
    airQuality: 82, greenSpaces: 86, internetSpeed: 180, englishFriendly: 96, remoteWork: 86, nightlife: 60,
    schools: 86, jobMarket: 78, beachKm: 400, intlAirport: true,
  },
  {
    id: "saltlakecity", name: "Salt Lake City", country: "Estados Unidos", photo: PHOTO.saltlakecity, region: "northamerica",
    climate: "cold", climateLabelEs: "Semiárido frío", climateLabelEn: "Cold semi-arid",
    housing: 1450, food: 560, transport: 70, healthcare: 410, education: 820, internet: 65, entertainment: 360,
    avgSalary: 4400, taxRate: 26,
    safety: 72, healthcareScore: 74, qualityOfLife: 80, purchasingPower: 72, walkability: 58, publicTransport: 56,
    airQuality: 54, greenSpaces: 80, internetSpeed: 220, englishFriendly: 100, remoteWork: 86, nightlife: 62,
    schools: 78, jobMarket: 82, beachKm: 900, intlAirport: true,
  },
  {
    id: "charlotte", name: "Charlotte", country: "Estados Unidos", photo: PHOTO.charlotte, region: "northamerica",
    climate: "warm", climateLabelEs: "Subtropical", climateLabelEn: "Subtropical",
    housing: 1500, food: 570, transport: 85, healthcare: 420, education: 860, internet: 68, entertainment: 390,
    avgSalary: 4500, taxRate: 25,
    safety: 62, healthcareScore: 74, qualityOfLife: 76, purchasingPower: 74, walkability: 48, publicTransport: 44,
    airQuality: 66, greenSpaces: 74, internetSpeed: 230, englishFriendly: 100, remoteWork: 86, nightlife: 70,
    schools: 78, jobMarket: 86, beachKm: 320, intlAirport: true,
  },
  {
    id: "curitiba", name: "Curitiba", country: "Brasil", photo: PHOTO.curitiba, region: "latam",
    climate: "temperate", climateLabelEs: "Subtropical fresco", climateLabelEn: "Cool subtropical",
    housing: 520, food: 300, transport: 40, healthcare: 90, education: 280, internet: 25, entertainment: 190,
    avgSalary: 900, taxRate: 27,
    safety: 66, healthcareScore: 70, qualityOfLife: 74, purchasingPower: 42, walkability: 76, publicTransport: 84,
    airQuality: 78, greenSpaces: 88, internetSpeed: 150, englishFriendly: 34, remoteWork: 70, nightlife: 68,
    schools: 72, jobMarket: 58, beachKm: 100, intlAirport: true,
  },
  {
    id: "belohorizonte", name: "Belo Horizonte", country: "Brasil", photo: PHOTO.belohorizonte, region: "latam",
    climate: "warm", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 480, food: 290, transport: 40, healthcare: 85, education: 260, internet: 25, entertainment: 190,
    avgSalary: 850, taxRate: 27,
    safety: 58, healthcareScore: 68, qualityOfLife: 70, purchasingPower: 40, walkability: 70, publicTransport: 68,
    airQuality: 70, greenSpaces: 76, internetSpeed: 140, englishFriendly: 32, remoteWork: 68, nightlife: 78,
    schools: 70, jobMarket: 58, beachKm: 380, intlAirport: true,
  },
  {
    id: "rosario", name: "Rosario", country: "Argentina", photo: PHOTO.rosario, region: "latam",
    climate: "temperate", climateLabelEs: "Templado húmedo", climateLabelEn: "Humid temperate",
    housing: 380, food: 280, transport: 25, healthcare: 70, education: 220, internet: 20, entertainment: 170,
    avgSalary: 700, taxRate: 30,
    safety: 62, healthcareScore: 72, qualityOfLife: 72, purchasingPower: 38, walkability: 80, publicTransport: 70,
    airQuality: 70, greenSpaces: 76, internetSpeed: 110, englishFriendly: 36, remoteWork: 66, nightlife: 80,
    schools: 72, jobMarket: 52, beachKm: 300, intlAirport: true,
  },
  {
    id: "merida", name: "Mérida", country: "México", photo: PHOTO.merida, region: "latam",
    climate: "warm", climateLabelEs: "Tropical seco", climateLabelEn: "Dry tropical",
    housing: 520, food: 300, transport: 35, healthcare: 80, education: 300, internet: 25, entertainment: 200,
    avgSalary: 880, taxRate: 26,
    safety: 84, healthcareScore: 68, qualityOfLife: 78, purchasingPower: 44, walkability: 66, publicTransport: 56,
    airQuality: 74, greenSpaces: 66, internetSpeed: 120, englishFriendly: 44, remoteWork: 74, nightlife: 64,
    schools: 70, jobMarket: 56, beachKm: 35, intlAirport: true,
  },
  {
    id: "santodomingo", name: "Santo Domingo", country: "Rep. Dominicana", photo: PHOTO.santodomingo, region: "latam",
    climate: "beach", climateLabelEs: "Tropical caribeño", climateLabelEn: "Caribbean tropical",
    housing: 620, food: 330, transport: 40, healthcare: 90, education: 320, internet: 35, entertainment: 210,
    avgSalary: 780, taxRate: 22,
    safety: 52, healthcareScore: 60, qualityOfLife: 66, purchasingPower: 36, walkability: 62, publicTransport: 50,
    airQuality: 62, greenSpaces: 58, internetSpeed: 100, englishFriendly: 52, remoteWork: 66, nightlife: 84,
    schools: 60, jobMarket: 54, beachKm: 0, intlAirport: true,
  },
  {
    id: "fukuoka", name: "Fukuoka", country: "Japón", photo: PHOTO.fukuoka, region: "asia",
    climate: "temperate", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 800, food: 430, transport: 45, healthcare: 90, education: 260, internet: 35, entertainment: 280,
    avgSalary: 2450, taxRate: 26,
    safety: 92, healthcareScore: 90, qualityOfLife: 86, purchasingPower: 60, walkability: 88, publicTransport: 88,
    airQuality: 76, greenSpaces: 74, internetSpeed: 240, englishFriendly: 32, remoteWork: 74, nightlife: 78,
    schools: 84, jobMarket: 72, beachKm: 10, intlAirport: true,
  },
  {
    id: "busan", name: "Busan", country: "Corea del Sur", photo: PHOTO.busan, region: "asia",
    climate: "temperate", climateLabelEs: "Subtropical costero", climateLabelEn: "Coastal subtropical",
    housing: 750, food: 420, transport: 40, healthcare: 80, education: 320, internet: 25, entertainment: 270,
    avgSalary: 2500, taxRate: 23,
    safety: 88, healthcareScore: 88, qualityOfLife: 82, purchasingPower: 60, walkability: 84, publicTransport: 88,
    airQuality: 64, greenSpaces: 70, internetSpeed: 260, englishFriendly: 36, remoteWork: 76, nightlife: 84,
    schools: 84, jobMarket: 72, beachKm: 0, intlAirport: true,
  },
  {
    id: "jakarta", name: "Yakarta", country: "Indonesia", photo: PHOTO.jakarta, region: "asia",
    climate: "warm", climateLabelEs: "Tropical húmedo", climateLabelEn: "Humid tropical",
    housing: 520, food: 280, transport: 45, healthcare: 70, education: 420, internet: 30, entertainment: 220,
    avgSalary: 650, taxRate: 25,
    safety: 52, healthcareScore: 58, qualityOfLife: 58, purchasingPower: 32, walkability: 42, publicTransport: 52,
    airQuality: 34, greenSpaces: 44, internetSpeed: 90, englishFriendly: 48, remoteWork: 66, nightlife: 74,
    schools: 58, jobMarket: 60, beachKm: 25, intlAirport: true,
  },
  {
    id: "colombo", name: "Colombo", country: "Sri Lanka", photo: PHOTO.colombo, region: "asia",
    climate: "beach", climateLabelEs: "Tropical costero", climateLabelEn: "Coastal tropical",
    housing: 420, food: 240, transport: 30, healthcare: 60, education: 300, internet: 25, entertainment: 180,
    avgSalary: 480, taxRate: 20,
    safety: 62, healthcareScore: 58, qualityOfLife: 62, purchasingPower: 28, walkability: 56, publicTransport: 50,
    airQuality: 52, greenSpaces: 54, internetSpeed: 80, englishFriendly: 66, remoteWork: 62, nightlife: 60,
    schools: 58, jobMarket: 46, beachKm: 0, intlAirport: true,
  },
  {
    id: "almaty", name: "Almaty", country: "Kazajistán", photo: PHOTO.almaty, region: "asia",
    climate: "cold", climateLabelEs: "Continental", climateLabelEn: "Continental",
    housing: 480, food: 280, transport: 25, healthcare: 55, education: 240, internet: 20, entertainment: 180,
    avgSalary: 720, taxRate: 15,
    safety: 66, healthcareScore: 62, qualityOfLife: 68, purchasingPower: 36, walkability: 70, publicTransport: 72,
    airQuality: 44, greenSpaces: 74, internetSpeed: 120, englishFriendly: 34, remoteWork: 66, nightlife: 68,
    schools: 66, jobMarket: 56, beachKm: 900, intlAirport: true,
  },
  {
    id: "goldcoast", name: "Gold Coast", country: "Australia", photo: PHOTO.goldcoast, region: "asia",
    climate: "beach", climateLabelEs: "Subtropical playero", climateLabelEn: "Beach subtropical",
    housing: 1650, food: 600, transport: 80, healthcare: 120, education: 700, internet: 60, entertainment: 380,
    avgSalary: 3600, taxRate: 27,
    safety: 80, healthcareScore: 86, qualityOfLife: 90, purchasingPower: 64, walkability: 72, publicTransport: 64,
    airQuality: 88, greenSpaces: 84, internetSpeed: 180, englishFriendly: 100, remoteWork: 86, nightlife: 76,
    schools: 82, jobMarket: 70, beachKm: 0, intlAirport: true,
  },
  {
    id: "adelaide", name: "Adelaida", country: "Australia", photo: PHOTO.adelaide, region: "asia",
    climate: "temperate", climateLabelEs: "Mediterráneo seco", climateLabelEn: "Dry Mediterranean",
    housing: 1250, food: 540, transport: 75, healthcare: 110, education: 650, internet: 55, entertainment: 340,
    avgSalary: 3500, taxRate: 27,
    safety: 84, healthcareScore: 86, qualityOfLife: 88, purchasingPower: 66, walkability: 74, publicTransport: 70,
    airQuality: 88, greenSpaces: 84, internetSpeed: 170, englishFriendly: 100, remoteWork: 84, nightlife: 66,
    schools: 84, jobMarket: 70, beachKm: 20, intlAirport: true,
  },
  {
    id: "windhoek", name: "Windhoek", country: "Namibia", photo: PHOTO.windhoek, region: "africa",
    climate: "warm", climateLabelEs: "Semiárido cálido", climateLabelEn: "Warm semi-arid",
    housing: 550, food: 300, transport: 35, healthcare: 70, education: 320, internet: 45, entertainment: 180,
    avgSalary: 780, taxRate: 22,
    safety: 54, healthcareScore: 56, qualityOfLife: 62, purchasingPower: 34, walkability: 50, publicTransport: 42,
    airQuality: 78, greenSpaces: 60, internetSpeed: 50, englishFriendly: 80, remoteWork: 58, nightlife: 52,
    schools: 58, jobMarket: 44, beachKm: 350, intlAirport: true,
  },
  {
    id: "gaborone", name: "Gaborone", country: "Botsuana", photo: PHOTO.gaborone, region: "africa",
    climate: "warm", climateLabelEs: "Semiárido", climateLabelEn: "Semi-arid",
    housing: 520, food: 290, transport: 35, healthcare: 65, education: 300, internet: 45, entertainment: 170,
    avgSalary: 820, taxRate: 20,
    safety: 60, healthcareScore: 58, qualityOfLife: 62, purchasingPower: 36, walkability: 48, publicTransport: 44,
    airQuality: 74, greenSpaces: 58, internetSpeed: 55, englishFriendly: 82, remoteWork: 56, nightlife: 50,
    schools: 58, jobMarket: 46, beachKm: 600, intlAirport: true,
  },
  {
    id: "addis", name: "Adís Abeba", country: "Etiopía", photo: PHOTO.addis, region: "africa",
    climate: "temperate", climateLabelEs: "Altiplano templado", climateLabelEn: "Mild highland",
    housing: 380, food: 220, transport: 25, healthcare: 50, education: 280, internet: 40, entertainment: 140,
    avgSalary: 320, taxRate: 25,
    safety: 52, healthcareScore: 48, qualityOfLife: 52, purchasingPower: 22, walkability: 52, publicTransport: 46,
    airQuality: 52, greenSpaces: 58, internetSpeed: 40, englishFriendly: 60, remoteWork: 50, nightlife: 54,
    schools: 50, jobMarket: 40, beachKm: 700, intlAirport: true,
  },
  {
    id: "alexandria", name: "Alejandría", country: "Egipto", photo: PHOTO.alexandria, region: "africa",
    climate: "beach", climateLabelEs: "Mediterráneo", climateLabelEn: "Mediterranean",
    housing: 330, food: 210, transport: 20, healthcare: 45, education: 240, internet: 25, entertainment: 130,
    avgSalary: 340, taxRate: 18,
    safety: 58, healthcareScore: 52, qualityOfLife: 58, purchasingPower: 24, walkability: 66, publicTransport: 52,
    airQuality: 50, greenSpaces: 44, internetSpeed: 60, englishFriendly: 44, remoteWork: 54, nightlife: 58,
    schools: 52, jobMarket: 42, beachKm: 0, intlAirport: true,
  },
  {
    id: "vienna", name: "Viena", country: "Austria", photo: PHOTO.vienna, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 1150, food: 470, transport: 45, healthcare: 90, education: 300, internet: 35, entertainment: 340,
    avgSalary: 2700, taxRate: 34,
    safety: 88, healthcareScore: 90, qualityOfLife: 92, purchasingPower: 66, walkability: 90, publicTransport: 96,
    airQuality: 78, greenSpaces: 86, internetSpeed: 180, englishFriendly: 78, remoteWork: 88, nightlife: 80,
    schools: 88, jobMarket: 78, beachKm: 300, intlAirport: true,
  },
  {
    id: "munich", name: "Múnich", country: "Alemania", photo: PHOTO.munich, region: "europe",
    climate: "cold", climateLabelEs: "Continental alpino", climateLabelEn: "Alpine continental",
    housing: 1600, food: 520, transport: 60, healthcare: 120, education: 350, internet: 40, entertainment: 380,
    avgSalary: 3300, taxRate: 38,
    safety: 86, healthcareScore: 88, qualityOfLife: 90, purchasingPower: 68, walkability: 86, publicTransport: 92,
    airQuality: 76, greenSpaces: 82, internetSpeed: 150, englishFriendly: 80, remoteWork: 86, nightlife: 78,
    schools: 86, jobMarket: 88, beachKm: 450, intlAirport: true,
  },
  {
    id: "stockholm", name: "Estocolmo", country: "Suecia", photo: PHOTO.stockholm, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1500, food: 540, transport: 80, healthcare: 60, education: 200, internet: 40, entertainment: 400,
    avgSalary: 3100, taxRate: 33,
    safety: 82, healthcareScore: 88, qualityOfLife: 88, purchasingPower: 66, walkability: 88, publicTransport: 92,
    airQuality: 88, greenSpaces: 84, internetSpeed: 220, englishFriendly: 92, remoteWork: 88, nightlife: 74,
    schools: 86, jobMarket: 82, beachKm: 1, intlAirport: true,
  },
  {
    id: "oslo", name: "Oslo", country: "Noruega", photo: PHOTO.oslo, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1700, food: 650, transport: 85, healthcare: 70, education: 180, internet: 45, entertainment: 450,
    avgSalary: 3900, taxRate: 32,
    safety: 86, healthcareScore: 90, qualityOfLife: 90, purchasingPower: 70, walkability: 84, publicTransport: 88,
    airQuality: 90, greenSpaces: 88, internetSpeed: 230, englishFriendly: 92, remoteWork: 86, nightlife: 70,
    schools: 86, jobMarket: 84, beachKm: 1, intlAirport: true,
  },
  {
    id: "dublin", name: "Dublín", country: "Irlanda", photo: PHOTO.dublin, region: "europe",
    climate: "temperate", climateLabelEs: "Oceánico lluvioso", climateLabelEn: "Rainy oceanic",
    housing: 2000, food: 560, transport: 90, healthcare: 110, education: 450, internet: 45, entertainment: 420,
    avgSalary: 3300, taxRate: 30,
    safety: 72, healthcareScore: 76, qualityOfLife: 80, purchasingPower: 64, walkability: 84, publicTransport: 72,
    airQuality: 80, greenSpaces: 74, internetSpeed: 150, englishFriendly: 100, remoteWork: 88, nightlife: 86,
    schools: 80, jobMarket: 88, beachKm: 5, intlAirport: true,
  },
  {
    id: "budapest", name: "Budapest", country: "Hungría", photo: PHOTO.budapest, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 750, food: 340, transport: 30, healthcare: 70, education: 220, internet: 20, entertainment: 240,
    avgSalary: 1350, taxRate: 28,
    safety: 80, healthcareScore: 72, qualityOfLife: 78, purchasingPower: 48, walkability: 88, publicTransport: 90,
    airQuality: 62, greenSpaces: 72, internetSpeed: 220, englishFriendly: 68, remoteWork: 88, nightlife: 88,
    schools: 74, jobMarket: 64, beachKm: 300, intlAirport: true,
  },
  {
    id: "brussels", name: "Bruselas", country: "Bélgica", photo: PHOTO.brussels, region: "europe",
    climate: "temperate", climateLabelEs: "Oceánico fresco", climateLabelEn: "Cool oceanic",
    housing: 1100, food: 470, transport: 55, healthcare: 90, education: 320, internet: 40, entertainment: 340,
    avgSalary: 2800, taxRate: 40,
    safety: 66, healthcareScore: 86, qualityOfLife: 80, purchasingPower: 62, walkability: 84, publicTransport: 86,
    airQuality: 70, greenSpaces: 76, internetSpeed: 160, englishFriendly: 84, remoteWork: 84, nightlife: 76,
    schools: 82, jobMarket: 80, beachKm: 110, intlAirport: true,
  },
  {
    id: "edinburgh", name: "Edimburgo", country: "Reino Unido", photo: PHOTO.edinburgh, region: "europe",
    climate: "cold", climateLabelEs: "Oceánico frío", climateLabelEn: "Cold oceanic",
    housing: 1250, food: 470, transport: 70, healthcare: 60, education: 380, internet: 35, entertainment: 340,
    avgSalary: 2600, taxRate: 32,
    safety: 84, healthcareScore: 82, qualityOfLife: 86, purchasingPower: 60, walkability: 90, publicTransport: 80,
    airQuality: 84, greenSpaces: 84, internetSpeed: 140, englishFriendly: 100, remoteWork: 84, nightlife: 80,
    schools: 84, jobMarket: 74, beachKm: 3, intlAirport: true,
  },
  {
    id: "helsinki", name: "Helsinki", country: "Finlandia", photo: PHOTO.helsinki, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1300, food: 500, transport: 70, healthcare: 60, education: 150, internet: 35, entertainment: 350,
    avgSalary: 2900, taxRate: 32,
    safety: 90, healthcareScore: 90, qualityOfLife: 90, purchasingPower: 66, walkability: 86, publicTransport: 90,
    airQuality: 92, greenSpaces: 86, internetSpeed: 200, englishFriendly: 90, remoteWork: 86, nightlife: 68,
    schools: 92, jobMarket: 78, beachKm: 1, intlAirport: true,
  },
  {
    id: "geneva", name: "Ginebra", country: "Suiza", photo: PHOTO.geneva, region: "europe",
    climate: "temperate", climateLabelEs: "Alpino templado", climateLabelEn: "Temperate alpine",
    housing: 2400, food: 750, transport: 80, healthcare: 420, education: 900, internet: 55, entertainment: 520,
    avgSalary: 6200, taxRate: 22,
    safety: 90, healthcareScore: 94, qualityOfLife: 90, purchasingPower: 84, walkability: 86, publicTransport: 92,
    airQuality: 86, greenSpaces: 88, internetSpeed: 220, englishFriendly: 86, remoteWork: 86, nightlife: 62,
    schools: 90, jobMarket: 86, beachKm: 300, intlAirport: true,
  },
  {
    id: "seattle", name: "Seattle", country: "Estados Unidos", photo: PHOTO.seattle, region: "northamerica",
    climate: "temperate", climateLabelEs: "Oceánico lluvioso", climateLabelEn: "Rainy oceanic",
    housing: 2200, food: 620, transport: 110, healthcare: 430, education: 900, internet: 70, entertainment: 450,
    avgSalary: 5600, taxRate: 28,
    safety: 58, healthcareScore: 80, qualityOfLife: 80, purchasingPower: 84, walkability: 80, publicTransport: 72,
    airQuality: 82, greenSpaces: 84, internetSpeed: 260, englishFriendly: 100, remoteWork: 90, nightlife: 80,
    schools: 82, jobMarket: 92, beachKm: 1, intlAirport: true,
  },
  {
    id: "boston", name: "Boston", country: "Estados Unidos", photo: PHOTO.boston, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental frío", climateLabelEn: "Cold continental",
    housing: 2600, food: 640, transport: 100, healthcare: 450, education: 1000, internet: 70, entertainment: 460,
    avgSalary: 5400, taxRate: 32,
    safety: 72, healthcareScore: 90, qualityOfLife: 82, purchasingPower: 80, walkability: 88, publicTransport: 82,
    airQuality: 80, greenSpaces: 74, internetSpeed: 250, englishFriendly: 100, remoteWork: 86, nightlife: 84,
    schools: 92, jobMarket: 90, beachKm: 2, intlAirport: true,
  },
  {
    id: "sandiego", name: "San Diego", country: "Estados Unidos", photo: PHOTO.sandiego, region: "northamerica",
    climate: "beach", climateLabelEs: "Mediterráneo costero", climateLabelEn: "Coastal Mediterranean",
    housing: 2400, food: 600, transport: 180, healthcare: 430, education: 900, internet: 70, entertainment: 440,
    avgSalary: 4900, taxRate: 30,
    safety: 72, healthcareScore: 80, qualityOfLife: 86, purchasingPower: 80, walkability: 66, publicTransport: 52,
    airQuality: 82, greenSpaces: 76, internetSpeed: 240, englishFriendly: 100, remoteWork: 88, nightlife: 78,
    schools: 82, jobMarket: 80, beachKm: 0, intlAirport: true,
  },
  {
    id: "montreal", name: "Montreal", country: "Canadá", photo: PHOTO.montreal, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental frío", climateLabelEn: "Cold continental",
    housing: 1250, food: 480, transport: 90, healthcare: 80, education: 400, internet: 55, entertainment: 340,
    avgSalary: 2800, taxRate: 31,
    safety: 80, healthcareScore: 84, qualityOfLife: 84, purchasingPower: 62, walkability: 88, publicTransport: 86,
    airQuality: 80, greenSpaces: 78, internetSpeed: 190, englishFriendly: 80, remoteWork: 86, nightlife: 86,
    schools: 84, jobMarket: 78, beachKm: 1, intlAirport: true,
  },
  {
    id: "losangeles", name: "Los Ángeles", country: "Estados Unidos", photo: PHOTO.losangeles, region: "northamerica",
    climate: "warm", climateLabelEs: "Mediterráneo seco", climateLabelEn: "Dry Mediterranean",
    housing: 2500, food: 640, transport: 220, healthcare: 440, education: 950, internet: 70, entertainment: 520,
    avgSalary: 5200, taxRate: 32,
    safety: 52, healthcareScore: 78, qualityOfLife: 74, purchasingPower: 78, walkability: 58, publicTransport: 48,
    airQuality: 50, greenSpaces: 66, internetSpeed: 240, englishFriendly: 100, remoteWork: 86, nightlife: 90,
    schools: 74, jobMarket: 88, beachKm: 0, intlAirport: true,
  },
  {
    id: "denver", name: "Denver", country: "Estados Unidos", photo: PHOTO.denver, region: "northamerica",
    climate: "cold", climateLabelEs: "Semiárido de montaña", climateLabelEn: "Mountain semi-arid",
    housing: 1700, food: 540, transport: 180, healthcare: 410, education: 820, internet: 65, entertainment: 400,
    avgSalary: 4600, taxRate: 26,
    safety: 66, healthcareScore: 80, qualityOfLife: 82, purchasingPower: 82, walkability: 64, publicTransport: 58,
    airQuality: 76, greenSpaces: 84, internetSpeed: 250, englishFriendly: 100, remoteWork: 88, nightlife: 76,
    schools: 80, jobMarket: 84, beachKm: 1500, intlAirport: true,
  },
  {
    id: "guadalajara", name: "Guadalajara", country: "México", photo: PHOTO.guadalajara, region: "latam",
    climate: "warm", climateLabelEs: "Subtropical templado", climateLabelEn: "Mild subtropical",
    housing: 620, food: 300, transport: 45, healthcare: 90, education: 320, internet: 25, entertainment: 230,
    avgSalary: 780, taxRate: 22,
    safety: 50, healthcareScore: 62, qualityOfLife: 70, purchasingPower: 32, walkability: 68, publicTransport: 60,
    airQuality: 54, greenSpaces: 62, internetSpeed: 140, englishFriendly: 42, remoteWork: 80, nightlife: 84,
    schools: 66, jobMarket: 64, beachKm: 300, intlAirport: true,
  },
  {
    id: "sanjose_cr", name: "San José", country: "Costa Rica", photo: PHOTO.sanjose_cr, region: "latam",
    climate: "warm", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 780, food: 340, transport: 60, healthcare: 100, education: 420, internet: 35, entertainment: 260,
    avgSalary: 950, taxRate: 20,
    safety: 58, healthcareScore: 74, qualityOfLife: 78, purchasingPower: 36, walkability: 62, publicTransport: 56,
    airQuality: 72, greenSpaces: 86, internetSpeed: 90, englishFriendly: 58, remoteWork: 82, nightlife: 68,
    schools: 72, jobMarket: 58, beachKm: 90, intlAirport: true,
  },
  {
    id: "cartagena", name: "Cartagena", country: "Colombia", photo: PHOTO.cartagena, region: "latam",
    climate: "beach", climateLabelEs: "Tropical caribeño", climateLabelEn: "Caribbean tropical",
    housing: 600, food: 300, transport: 40, healthcare: 80, education: 300, internet: 25, entertainment: 240,
    avgSalary: 620, taxRate: 19,
    safety: 52, healthcareScore: 64, qualityOfLife: 70, purchasingPower: 28, walkability: 66, publicTransport: 48,
    airQuality: 70, greenSpaces: 58, internetSpeed: 90, englishFriendly: 44, remoteWork: 74, nightlife: 84,
    schools: 60, jobMarket: 50, beachKm: 0, intlAirport: true,
  },
  {
    id: "quito", name: "Quito", country: "Ecuador", photo: PHOTO.quito, region: "latam",
    climate: "temperate", climateLabelEs: "Andino templado", climateLabelEn: "Temperate Andean",
    housing: 520, food: 260, transport: 35, healthcare: 80, education: 280, internet: 25, entertainment: 200,
    avgSalary: 650, taxRate: 20,
    safety: 50, healthcareScore: 66, qualityOfLife: 68, purchasingPower: 28, walkability: 68, publicTransport: 62,
    airQuality: 60, greenSpaces: 72, internetSpeed: 80, englishFriendly: 40, remoteWork: 76, nightlife: 66,
    schools: 64, jobMarket: 50, beachKm: 200, intlAirport: true,
  },
  {
    id: "asuncion", name: "Asunción", country: "Paraguay", photo: PHOTO.asuncion, region: "latam",
    climate: "warm", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 480, food: 260, transport: 35, healthcare: 70, education: 260, internet: 25, entertainment: 190,
    avgSalary: 700, taxRate: 15,
    safety: 56, healthcareScore: 60, qualityOfLife: 66, purchasingPower: 32, walkability: 58, publicTransport: 48,
    airQuality: 64, greenSpaces: 60, internetSpeed: 90, englishFriendly: 36, remoteWork: 74, nightlife: 64,
    schools: 58, jobMarket: 52, beachKm: 1000, intlAirport: true,
  },
  {
    id: "osaka", name: "Osaka", country: "Japón", photo: PHOTO.osaka, region: "asia",
    climate: "temperate", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 900, food: 420, transport: 60, healthcare: 90, education: 350, internet: 35, entertainment: 320,
    avgSalary: 2300, taxRate: 26,
    safety: 94, healthcareScore: 90, qualityOfLife: 86, purchasingPower: 58, walkability: 88, publicTransport: 96,
    airQuality: 74, greenSpaces: 64, internetSpeed: 240, englishFriendly: 40, remoteWork: 78, nightlife: 88,
    schools: 84, jobMarket: 80, beachKm: 20, intlAirport: true,
  },
  {
    id: "hanoi", name: "Hanói", country: "Vietnam", photo: PHOTO.hanoi, region: "asia",
    climate: "warm", climateLabelEs: "Tropical monzónico", climateLabelEn: "Monsoon tropical",
    housing: 480, food: 250, transport: 40, healthcare: 70, education: 400, internet: 20, entertainment: 190,
    avgSalary: 520, taxRate: 14,
    safety: 72, healthcareScore: 58, qualityOfLife: 62, purchasingPower: 28, walkability: 66, publicTransport: 50,
    airQuality: 32, greenSpaces: 54, internetSpeed: 120, englishFriendly: 42, remoteWork: 86, nightlife: 78,
    schools: 58, jobMarket: 54, beachKm: 120, intlAirport: true,
  },
  {
    id: "manila", name: "Manila", country: "Filipinas", photo: PHOTO.manila, region: "asia",
    climate: "warm", climateLabelEs: "Tropical húmedo", climateLabelEn: "Humid tropical",
    housing: 620, food: 300, transport: 60, healthcare: 80, education: 450, internet: 35, entertainment: 230,
    avgSalary: 480, taxRate: 20,
    safety: 44, healthcareScore: 56, qualityOfLife: 56, purchasingPower: 24, walkability: 52, publicTransport: 44,
    airQuality: 38, greenSpaces: 42, internetSpeed: 90, englishFriendly: 86, remoteWork: 80, nightlife: 80,
    schools: 60, jobMarket: 54, beachKm: 5, intlAirport: true,
  },
  {
    id: "telaviv", name: "Tel Aviv", country: "Israel", photo: PHOTO.telaviv, region: "asia",
    climate: "beach", climateLabelEs: "Mediterráneo cálido", climateLabelEn: "Warm Mediterranean",
    housing: 2200, food: 620, transport: 70, healthcare: 110, education: 600, internet: 35, entertainment: 460,
    avgSalary: 3300, taxRate: 28,
    safety: 62, healthcareScore: 84, qualityOfLife: 80, purchasingPower: 58, walkability: 88, publicTransport: 74,
    airQuality: 66, greenSpaces: 64, internetSpeed: 180, englishFriendly: 88, remoteWork: 88, nightlife: 92,
    schools: 80, jobMarket: 86, beachKm: 0, intlAirport: true,
  },
  {
    id: "abudhabi", name: "Abu Dabi", country: "Emiratos Árabes", photo: PHOTO.abudhabi, region: "asia",
    climate: "warm", climateLabelEs: "Desértico", climateLabelEn: "Desert",
    housing: 1700, food: 500, transport: 150, healthcare: 150, education: 700, internet: 60, entertainment: 400,
    avgSalary: 4200, taxRate: 0,
    safety: 90, healthcareScore: 82, qualityOfLife: 82, purchasingPower: 80, walkability: 50, publicTransport: 52,
    airQuality: 58, greenSpaces: 54, internetSpeed: 220, englishFriendly: 90, remoteWork: 86, nightlife: 60,
    schools: 80, jobMarket: 82, beachKm: 1, intlAirport: true,
  },
  {
    id: "bengaluru", name: "Bengaluru", country: "India", photo: PHOTO.bengaluru, region: "asia",
    climate: "warm", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 450, food: 220, transport: 45, healthcare: 60, education: 400, internet: 20, entertainment: 190,
    avgSalary: 600, taxRate: 20,
    safety: 58, healthcareScore: 60, qualityOfLife: 60, purchasingPower: 30, walkability: 54, publicTransport: 52,
    airQuality: 40, greenSpaces: 66, internetSpeed: 100, englishFriendly: 86, remoteWork: 84, nightlife: 78,
    schools: 72, jobMarket: 86, beachKm: 300, intlAirport: true,
  },
  {
    id: "chiangmai", name: "Chiang Mai", country: "Tailandia", photo: PHOTO.chiangmai, region: "asia",
    climate: "warm", climateLabelEs: "Tropical de montaña", climateLabelEn: "Mountain tropical",
    housing: 380, food: 240, transport: 40, healthcare: 70, education: 350, internet: 20, entertainment: 190,
    avgSalary: 450, taxRate: 10,
    safety: 74, healthcareScore: 66, qualityOfLife: 74, purchasingPower: 26, walkability: 62, publicTransport: 42,
    airQuality: 34, greenSpaces: 78, internetSpeed: 120, englishFriendly: 58, remoteWork: 94, nightlife: 68,
    schools: 58, jobMarket: 40, beachKm: 650, intlAirport: true,
  },
  {
    id: "brisbane", name: "Brisbane", country: "Australia", photo: PHOTO.brisbane, region: "asia",
    climate: "warm", climateLabelEs: "Subtropical soleado", climateLabelEn: "Sunny subtropical",
    housing: 1750, food: 560, transport: 120, healthcare: 120, education: 700, internet: 55, entertainment: 420,
    avgSalary: 3900, taxRate: 28,
    safety: 80, healthcareScore: 86, qualityOfLife: 86, purchasingPower: 70, walkability: 72, publicTransport: 70,
    airQuality: 86, greenSpaces: 82, internetSpeed: 120, englishFriendly: 100, remoteWork: 84, nightlife: 74,
    schools: 84, jobMarket: 80, beachKm: 20, intlAirport: true,
  },
  {
    id: "accra", name: "Accra", country: "Ghana", photo: PHOTO.accra, region: "africa",
    climate: "warm", climateLabelEs: "Tropical costero", climateLabelEn: "Coastal tropical",
    housing: 700, food: 280, transport: 50, healthcare: 80, education: 450, internet: 40, entertainment: 200,
    avgSalary: 400, taxRate: 20,
    safety: 58, healthcareScore: 50, qualityOfLife: 58, purchasingPower: 20, walkability: 50, publicTransport: 40,
    airQuality: 44, greenSpaces: 48, internetSpeed: 60, englishFriendly: 96, remoteWork: 72, nightlife: 76,
    schools: 52, jobMarket: 48, beachKm: 0, intlAirport: true,
  },
  {
    id: "lagos", name: "Lagos", country: "Nigeria", photo: PHOTO.lagos, region: "africa",
    climate: "warm", climateLabelEs: "Tropical húmedo", climateLabelEn: "Humid tropical",
    housing: 800, food: 300, transport: 60, healthcare: 90, education: 500, internet: 50, entertainment: 220,
    avgSalary: 380, taxRate: 21,
    safety: 32, healthcareScore: 44, qualityOfLife: 48, purchasingPower: 18, walkability: 44, publicTransport: 34,
    airQuality: 32, greenSpaces: 40, internetSpeed: 50, englishFriendly: 96, remoteWork: 64, nightlife: 84,
    schools: 48, jobMarket: 56, beachKm: 0, intlAirport: true,
  },
  {
    id: "kigali", name: "Kigali", country: "Ruanda", photo: PHOTO.kigali, region: "africa",
    climate: "temperate", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 450, food: 220, transport: 35, healthcare: 60, education: 380, internet: 35, entertainment: 160,
    avgSalary: 320, taxRate: 25,
    safety: 78, healthcareScore: 54, qualityOfLife: 66, purchasingPower: 18, walkability: 56, publicTransport: 46,
    airQuality: 66, greenSpaces: 72, internetSpeed: 60, englishFriendly: 80, remoteWork: 74, nightlife: 52,
    schools: 54, jobMarket: 44, beachKm: 1200, intlAirport: true,
  },
  {
    id: "casablanca", name: "Casablanca", country: "Marruecos", photo: PHOTO.casablanca, region: "africa",
    climate: "beach", climateLabelEs: "Mediterráneo atlántico", climateLabelEn: "Atlantic Mediterranean",
    housing: 520, food: 260, transport: 35, healthcare: 60, education: 320, internet: 25, entertainment: 190,
    avgSalary: 480, taxRate: 22,
    safety: 60, healthcareScore: 58, qualityOfLife: 64, purchasingPower: 24, walkability: 66, publicTransport: 58,
    airQuality: 52, greenSpaces: 50, internetSpeed: 70, englishFriendly: 52, remoteWork: 74, nightlife: 62,
    schools: 58, jobMarket: 54, beachKm: 0, intlAirport: true,
  },
  {
    id: "hamburg", name: "Hamburgo", country: "Alemania", photo: PHOTO.hamburg, region: "europe",
    climate: "cold", climateLabelEs: "Oceánico frío", climateLabelEn: "Cold oceanic",
    housing: 1250, food: 470, transport: 60, healthcare: 110, education: 320, internet: 40, entertainment: 340,
    avgSalary: 3000, taxRate: 38,
    safety: 84, healthcareScore: 88, qualityOfLife: 88, purchasingPower: 68, walkability: 86, publicTransport: 90,
    airQuality: 78, greenSpaces: 82, internetSpeed: 160, englishFriendly: 78, remoteWork: 84, nightlife: 84,
    schools: 84, jobMarket: 84, beachKm: 90, intlAirport: true,
  },
  {
    id: "zagreb", name: "Zagreb", country: "Croacia", photo: PHOTO.zagreb, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 620, food: 320, transport: 30, healthcare: 70, education: 220, internet: 25, entertainment: 220,
    avgSalary: 1200, taxRate: 26,
    safety: 84, healthcareScore: 74, qualityOfLife: 78, purchasingPower: 44, walkability: 84, publicTransport: 78,
    airQuality: 66, greenSpaces: 76, internetSpeed: 140, englishFriendly: 70, remoteWork: 86, nightlife: 74,
    schools: 74, jobMarket: 58, beachKm: 120, intlAirport: true,
  },
  {
    id: "ljubljana", name: "Liubliana", country: "Eslovenia", photo: PHOTO.ljubljana, region: "europe",
    climate: "cold", climateLabelEs: "Alpino continental", climateLabelEn: "Continental alpine",
    housing: 750, food: 350, transport: 30, healthcare: 70, education: 240, internet: 30, entertainment: 240,
    avgSalary: 1500, taxRate: 30,
    safety: 90, healthcareScore: 80, qualityOfLife: 86, purchasingPower: 50, walkability: 88, publicTransport: 76,
    airQuality: 72, greenSpaces: 90, internetSpeed: 150, englishFriendly: 78, remoteWork: 84, nightlife: 68,
    schools: 80, jobMarket: 62, beachKm: 90, intlAirport: true,
  },
  {
    id: "tallinn", name: "Tallin", country: "Estonia", photo: PHOTO.tallinn, region: "europe",
    climate: "cold", climateLabelEs: "Báltico frío", climateLabelEn: "Cold Baltic",
    housing: 800, food: 360, transport: 30, healthcare: 60, education: 200, internet: 20, entertainment: 240,
    avgSalary: 1700, taxRate: 25,
    safety: 86, healthcareScore: 78, qualityOfLife: 84, purchasingPower: 54, walkability: 86, publicTransport: 82,
    airQuality: 84, greenSpaces: 80, internetSpeed: 240, englishFriendly: 80, remoteWork: 92, nightlife: 70,
    schools: 82, jobMarket: 70, beachKm: 1, intlAirport: true,
  },
  {
    id: "riga", name: "Riga", country: "Letonia", photo: PHOTO.riga, region: "europe",
    climate: "cold", climateLabelEs: "Báltico frío", climateLabelEn: "Cold Baltic",
    housing: 650, food: 330, transport: 25, healthcare: 60, education: 200, internet: 20, entertainment: 210,
    avgSalary: 1350, taxRate: 26,
    safety: 80, healthcareScore: 74, qualityOfLife: 78, purchasingPower: 46, walkability: 86, publicTransport: 84,
    airQuality: 80, greenSpaces: 80, internetSpeed: 220, englishFriendly: 76, remoteWork: 88, nightlife: 76,
    schools: 76, jobMarket: 60, beachKm: 10, intlAirport: true,
  },
  {
    id: "vilnius", name: "Vilna", country: "Lituania", photo: PHOTO.vilnius, region: "europe",
    climate: "cold", climateLabelEs: "Báltico frío", climateLabelEn: "Cold Baltic",
    housing: 700, food: 330, transport: 25, healthcare: 60, education: 200, internet: 20, entertainment: 210,
    avgSalary: 1450, taxRate: 26,
    safety: 84, healthcareScore: 76, qualityOfLife: 80, purchasingPower: 50, walkability: 84, publicTransport: 80,
    airQuality: 78, greenSpaces: 84, internetSpeed: 230, englishFriendly: 74, remoteWork: 90, nightlife: 74,
    schools: 78, jobMarket: 66, beachKm: 300, intlAirport: true,
  },
  {
    id: "bucharest", name: "Bucarest", country: "Rumanía", photo: PHOTO.bucharest, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 550, food: 300, transport: 25, healthcare: 60, education: 220, internet: 15, entertainment: 210,
    avgSalary: 1150, taxRate: 20,
    safety: 74, healthcareScore: 70, qualityOfLife: 72, purchasingPower: 44, walkability: 78, publicTransport: 80,
    airQuality: 58, greenSpaces: 66, internetSpeed: 300, englishFriendly: 70, remoteWork: 88, nightlife: 84,
    schools: 72, jobMarket: 64, beachKm: 220, intlAirport: true,
  },
  {
    id: "sofia", name: "Sofía", country: "Bulgaria", photo: PHOTO.sofia, region: "europe",
    climate: "cold", climateLabelEs: "Continental de montaña", climateLabelEn: "Mountain continental",
    housing: 500, food: 280, transport: 25, healthcare: 55, education: 200, internet: 15, entertainment: 190,
    avgSalary: 1050, taxRate: 20,
    safety: 74, healthcareScore: 68, qualityOfLife: 72, purchasingPower: 42, walkability: 80, publicTransport: 78,
    airQuality: 54, greenSpaces: 74, internetSpeed: 220, englishFriendly: 66, remoteWork: 88, nightlife: 78,
    schools: 70, jobMarket: 58, beachKm: 300, intlAirport: true,
  },
  {
    id: "malaga", name: "Málaga", country: "España", photo: PHOTO.malaga, region: "europe",
    climate: "beach", climateLabelEs: "Mediterráneo cálido", climateLabelEn: "Warm Mediterranean",
    housing: 1100, food: 420, transport: 45, healthcare: 80, education: 240, internet: 32, entertainment: 300,
    avgSalary: 1900, taxRate: 30,
    safety: 80, healthcareScore: 86, qualityOfLife: 86, purchasingPower: 58, walkability: 86, publicTransport: 74,
    airQuality: 78, greenSpaces: 72, internetSpeed: 180, englishFriendly: 66, remoteWork: 90, nightlife: 82,
    schools: 78, jobMarket: 60, beachKm: 0, intlAirport: true,
  },
  {
    id: "seville", name: "Sevilla", country: "España", photo: PHOTO.seville, region: "europe",
    climate: "warm", climateLabelEs: "Mediterráneo seco", climateLabelEn: "Dry Mediterranean",
    housing: 850, food: 390, transport: 40, healthcare: 80, education: 230, internet: 30, entertainment: 280,
    avgSalary: 1750, taxRate: 30,
    safety: 80, healthcareScore: 86, qualityOfLife: 84, purchasingPower: 56, walkability: 88, publicTransport: 76,
    airQuality: 76, greenSpaces: 70, internetSpeed: 170, englishFriendly: 58, remoteWork: 86, nightlife: 86,
    schools: 76, jobMarket: 56, beachKm: 90, intlAirport: true,
  },
  {
    id: "nice", name: "Niza", country: "Francia", photo: PHOTO.nice, region: "europe",
    climate: "beach", climateLabelEs: "Mediterráneo", climateLabelEn: "Mediterranean",
    housing: 1500, food: 500, transport: 50, healthcare: 90, education: 320, internet: 35, entertainment: 360,
    avgSalary: 2400, taxRate: 33,
    safety: 74, healthcareScore: 88, qualityOfLife: 84, purchasingPower: 58, walkability: 86, publicTransport: 78,
    airQuality: 80, greenSpaces: 74, internetSpeed: 160, englishFriendly: 66, remoteWork: 84, nightlife: 74,
    schools: 80, jobMarket: 64, beachKm: 0, intlAirport: true,
  },
  {
    id: "florence", name: "Florencia", country: "Italia", photo: PHOTO.florence, region: "europe",
    climate: "temperate", climateLabelEs: "Mediterráneo interior", climateLabelEn: "Inland Mediterranean",
    housing: 1200, food: 450, transport: 45, healthcare: 80, education: 300, internet: 32, entertainment: 320,
    avgSalary: 1900, taxRate: 36,
    safety: 80, healthcareScore: 84, qualityOfLife: 84, purchasingPower: 52, walkability: 90, publicTransport: 74,
    airQuality: 68, greenSpaces: 70, internetSpeed: 140, englishFriendly: 64, remoteWork: 82, nightlife: 74,
    schools: 78, jobMarket: 58, beachKm: 80, intlAirport: true,
  },
  {
    id: "calgary", name: "Calgary", country: "Canadá", photo: PHOTO.calgary, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental seco", climateLabelEn: "Dry continental",
    housing: 1350, food: 500, transport: 100, healthcare: 80, education: 420, internet: 60, entertainment: 340,
    avgSalary: 3200, taxRate: 29,
    safety: 80, healthcareScore: 84, qualityOfLife: 84, purchasingPower: 66, walkability: 64, publicTransport: 64,
    airQuality: 84, greenSpaces: 80, internetSpeed: 190, englishFriendly: 96, remoteWork: 84, nightlife: 70,
    schools: 84, jobMarket: 78, beachKm: 1000, intlAirport: true,
  },
  {
    id: "nashville", name: "Nashville", country: "Estados Unidos", photo: PHOTO.nashville, region: "northamerica",
    climate: "warm", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 1600, food: 540, transport: 180, healthcare: 400, education: 780, internet: 65, entertainment: 420,
    avgSalary: 4200, taxRate: 24,
    safety: 60, healthcareScore: 76, qualityOfLife: 78, purchasingPower: 78, walkability: 58, publicTransport: 44,
    airQuality: 76, greenSpaces: 74, internetSpeed: 240, englishFriendly: 100, remoteWork: 86, nightlife: 92,
    schools: 76, jobMarket: 84, beachKm: 600, intlAirport: true,
  },
  {
    id: "phoenix", name: "Phoenix", country: "Estados Unidos", photo: PHOTO.phoenix, region: "northamerica",
    climate: "warm", climateLabelEs: "Desértico", climateLabelEn: "Desert",
    housing: 1550, food: 520, transport: 190, healthcare: 400, education: 760, internet: 65, entertainment: 400,
    avgSalary: 4300, taxRate: 26,
    safety: 58, healthcareScore: 76, qualityOfLife: 74, purchasingPower: 78, walkability: 50, publicTransport: 40,
    airQuality: 62, greenSpaces: 58, internetSpeed: 240, englishFriendly: 100, remoteWork: 84, nightlife: 74,
    schools: 74, jobMarket: 82, beachKm: 500, intlAirport: true,
  },
  {
    id: "raleigh", name: "Raleigh", country: "Estados Unidos", photo: PHOTO.raleigh, region: "northamerica",
    climate: "warm", climateLabelEs: "Subtropical templado", climateLabelEn: "Mild subtropical",
    housing: 1500, food: 520, transport: 180, healthcare: 400, education: 780, internet: 65, entertainment: 380,
    avgSalary: 4400, taxRate: 26,
    safety: 72, healthcareScore: 80, qualityOfLife: 82, purchasingPower: 80, walkability: 54, publicTransport: 44,
    airQuality: 80, greenSpaces: 84, internetSpeed: 250, englishFriendly: 100, remoteWork: 88, nightlife: 68,
    schools: 86, jobMarket: 86, beachKm: 200, intlAirport: true,
  },
  {
    id: "monterrey", name: "Monterrey", country: "México", photo: PHOTO.monterrey, region: "latam",
    climate: "warm", climateLabelEs: "Semiárido cálido", climateLabelEn: "Warm semi-arid",
    housing: 680, food: 320, transport: 60, healthcare: 90, education: 380, internet: 30, entertainment: 250,
    avgSalary: 950, taxRate: 22,
    safety: 48, healthcareScore: 66, qualityOfLife: 70, purchasingPower: 36, walkability: 58, publicTransport: 54,
    airQuality: 48, greenSpaces: 58, internetSpeed: 150, englishFriendly: 48, remoteWork: 80, nightlife: 80,
    schools: 70, jobMarket: 76, beachKm: 300, intlAirport: true,
  },
  {
    id: "cancun", name: "Cancún", country: "México", photo: PHOTO.cancun, region: "latam",
    climate: "beach", climateLabelEs: "Tropical caribeño", climateLabelEn: "Caribbean tropical",
    housing: 750, food: 340, transport: 50, healthcare: 90, education: 350, internet: 30, entertainment: 280,
    avgSalary: 750, taxRate: 20,
    safety: 54, healthcareScore: 62, qualityOfLife: 72, purchasingPower: 30, walkability: 60, publicTransport: 48,
    airQuality: 74, greenSpaces: 64, internetSpeed: 120, englishFriendly: 60, remoteWork: 84, nightlife: 90,
    schools: 62, jobMarket: 58, beachKm: 0, intlAirport: true,
  },
  {
    id: "florianopolis", name: "Florianópolis", country: "Brasil", photo: PHOTO.florianopolis, region: "latam",
    climate: "beach", climateLabelEs: "Subtropical costero", climateLabelEn: "Coastal subtropical",
    housing: 750, food: 350, transport: 55, healthcare: 100, education: 400, internet: 30, entertainment: 270,
    avgSalary: 900, taxRate: 23,
    safety: 60, healthcareScore: 70, qualityOfLife: 78, purchasingPower: 32, walkability: 66, publicTransport: 52,
    airQuality: 80, greenSpaces: 80, internetSpeed: 150, englishFriendly: 42, remoteWork: 84, nightlife: 78,
    schools: 70, jobMarket: 58, beachKm: 0, intlAirport: true,
  },
  {
    id: "cordoba_ar", name: "Córdoba", country: "Argentina", photo: PHOTO.cordoba_ar, region: "latam",
    climate: "temperate", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 420, food: 260, transport: 35, healthcare: 70, education: 260, internet: 25, entertainment: 200,
    avgSalary: 600, taxRate: 25,
    safety: 56, healthcareScore: 72, qualityOfLife: 70, purchasingPower: 30, walkability: 74, publicTransport: 64,
    airQuality: 64, greenSpaces: 70, internetSpeed: 130, englishFriendly: 40, remoteWork: 80, nightlife: 84,
    schools: 70, jobMarket: 54, beachKm: 700, intlAirport: true,
  },
  {
    id: "laspaz", name: "La Paz", country: "Bolivia", photo: PHOTO.laspaz, region: "latam",
    climate: "cold", climateLabelEs: "Andino de altura", climateLabelEn: "High Andean",
    housing: 380, food: 220, transport: 30, healthcare: 60, education: 240, internet: 25, entertainment: 170,
    avgSalary: 450, taxRate: 15,
    safety: 52, healthcareScore: 56, qualityOfLife: 62, purchasingPower: 24, walkability: 66, publicTransport: 62,
    airQuality: 58, greenSpaces: 54, internetSpeed: 70, englishFriendly: 34, remoteWork: 72, nightlife: 62,
    schools: 56, jobMarket: 44, beachKm: 1000, intlAirport: true,
  },
  {
    id: "punta", name: "Punta del Este", country: "Uruguay", photo: PHOTO.punta, region: "latam",
    climate: "beach", climateLabelEs: "Atlántico templado", climateLabelEn: "Temperate Atlantic",
    housing: 900, food: 380, transport: 45, healthcare: 110, education: 360, internet: 35, entertainment: 300,
    avgSalary: 1100, taxRate: 26,
    safety: 74, healthcareScore: 76, qualityOfLife: 80, purchasingPower: 36, walkability: 72, publicTransport: 50,
    airQuality: 88, greenSpaces: 80, internetSpeed: 120, englishFriendly: 52, remoteWork: 80, nightlife: 72,
    schools: 72, jobMarket: 46, beachKm: 0, intlAirport: true,
  },
  {
    id: "hongkong", name: "Hong Kong", country: "China", photo: PHOTO.hongkong, region: "asia",
    climate: "warm", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 2400, food: 620, transport: 60, healthcare: 150, education: 900, internet: 45, entertainment: 460,
    avgSalary: 3600, taxRate: 15,
    safety: 88, healthcareScore: 86, qualityOfLife: 80, purchasingPower: 62, walkability: 92, publicTransport: 98,
    airQuality: 58, greenSpaces: 72, internetSpeed: 260, englishFriendly: 84, remoteWork: 84, nightlife: 86,
    schools: 86, jobMarket: 90, beachKm: 2, intlAirport: true,
  },
  {
    id: "shanghai", name: "Shanghái", country: "China", photo: PHOTO.shanghai, region: "asia",
    climate: "temperate", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 1200, food: 420, transport: 45, healthcare: 110, education: 700, internet: 20, entertainment: 320,
    avgSalary: 1900, taxRate: 20,
    safety: 86, healthcareScore: 76, qualityOfLife: 74, purchasingPower: 50, walkability: 84, publicTransport: 96,
    airQuality: 44, greenSpaces: 64, internetSpeed: 220, englishFriendly: 42, remoteWork: 72, nightlife: 84,
    schools: 78, jobMarket: 86, beachKm: 30, intlAirport: true,
  },
  {
    id: "phuket", name: "Phuket", country: "Tailandia", photo: PHOTO.phuket, region: "asia",
    climate: "beach", climateLabelEs: "Tropical isleño", climateLabelEn: "Island tropical",
    housing: 600, food: 280, transport: 60, healthcare: 80, education: 500, internet: 25, entertainment: 250,
    avgSalary: 500, taxRate: 10,
    safety: 72, healthcareScore: 64, qualityOfLife: 74, purchasingPower: 26, walkability: 48, publicTransport: 36,
    airQuality: 72, greenSpaces: 74, internetSpeed: 110, englishFriendly: 62, remoteWork: 90, nightlife: 86,
    schools: 54, jobMarket: 42, beachKm: 0, intlAirport: true,
  },
  {
    id: "danang", name: "Da Nang", country: "Vietnam", photo: PHOTO.danang, region: "asia",
    climate: "beach", climateLabelEs: "Tropical costero", climateLabelEn: "Coastal tropical",
    housing: 420, food: 240, transport: 40, healthcare: 70, education: 400, internet: 20, entertainment: 180,
    avgSalary: 480, taxRate: 14,
    safety: 76, healthcareScore: 58, qualityOfLife: 70, purchasingPower: 26, walkability: 60, publicTransport: 42,
    airQuality: 58, greenSpaces: 66, internetSpeed: 140, englishFriendly: 44, remoteWork: 90, nightlife: 72,
    schools: 56, jobMarket: 50, beachKm: 0, intlAirport: true,
  },
  {
    id: "tbilisi", name: "Tiflis", country: "Georgia", photo: PHOTO.tbilisi, region: "asia",
    climate: "temperate", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 520, food: 280, transport: 25, healthcare: 60, education: 300, internet: 20, entertainment: 200,
    avgSalary: 600, taxRate: 20,
    safety: 76, healthcareScore: 60, qualityOfLife: 70, purchasingPower: 34, walkability: 76, publicTransport: 64,
    airQuality: 56, greenSpaces: 66, internetSpeed: 120, englishFriendly: 56, remoteWork: 88, nightlife: 80,
    schools: 62, jobMarket: 52, beachKm: 300, intlAirport: true,
  },
  {
    id: "istanbul", name: "Estambul", country: "Turquía", photo: PHOTO.istanbul, region: "asia",
    climate: "temperate", climateLabelEs: "Mediterráneo templado", climateLabelEn: "Mild Mediterranean",
    housing: 600, food: 300, transport: 35, healthcare: 70, education: 400, internet: 20, entertainment: 240,
    avgSalary: 700, taxRate: 25,
    safety: 58, healthcareScore: 68, qualityOfLife: 68, purchasingPower: 34, walkability: 80, publicTransport: 84,
    airQuality: 48, greenSpaces: 60, internetSpeed: 90, englishFriendly: 44, remoteWork: 80, nightlife: 86,
    schools: 68, jobMarket: 66, beachKm: 1, intlAirport: true,
  },
  {
    id: "doha", name: "Doha", country: "Catar", photo: PHOTO.doha, region: "asia",
    climate: "warm", climateLabelEs: "Desértico", climateLabelEn: "Desert",
    housing: 1600, food: 480, transport: 140, healthcare: 140, education: 750, internet: 60, entertainment: 380,
    avgSalary: 4500, taxRate: 0,
    safety: 90, healthcareScore: 80, qualityOfLife: 80, purchasingPower: 80, walkability: 46, publicTransport: 50,
    airQuality: 54, greenSpaces: 50, internetSpeed: 200, englishFriendly: 86, remoteWork: 82, nightlife: 54,
    schools: 80, jobMarket: 84, beachKm: 1, intlAirport: true,
  },
  {
    id: "perth", name: "Perth", country: "Australia", photo: PHOTO.perth, region: "asia",
    climate: "beach", climateLabelEs: "Mediterráneo cálido", climateLabelEn: "Warm Mediterranean",
    housing: 1650, food: 560, transport: 120, healthcare: 120, education: 700, internet: 55, entertainment: 400,
    avgSalary: 3800, taxRate: 28,
    safety: 82, healthcareScore: 86, qualityOfLife: 86, purchasingPower: 70, walkability: 68, publicTransport: 64,
    airQuality: 92, greenSpaces: 84, internetSpeed: 110, englishFriendly: 100, remoteWork: 80, nightlife: 70,
    schools: 84, jobMarket: 78, beachKm: 0, intlAirport: true,
  },
  {
    id: "wellington", name: "Wellington", country: "Nueva Zelanda", photo: PHOTO.wellington, region: "asia",
    climate: "temperate", climateLabelEs: "Oceánico ventoso", climateLabelEn: "Windy oceanic",
    housing: 1400, food: 520, transport: 90, healthcare: 90, education: 500, internet: 50, entertainment: 340,
    avgSalary: 3000, taxRate: 30,
    safety: 86, healthcareScore: 84, qualityOfLife: 86, purchasingPower: 64, walkability: 86, publicTransport: 76,
    airQuality: 96, greenSpaces: 88, internetSpeed: 140, englishFriendly: 100, remoteWork: 84, nightlife: 70,
    schools: 86, jobMarket: 72, beachKm: 0, intlAirport: true,
  },
  {
    id: "durban", name: "Durban", country: "Sudáfrica", photo: PHOTO.durban, region: "africa",
    climate: "beach", climateLabelEs: "Subtropical costero", climateLabelEn: "Coastal subtropical",
    housing: 600, food: 300, transport: 60, healthcare: 120, education: 400, internet: 40, entertainment: 220,
    avgSalary: 700, taxRate: 26,
    safety: 38, healthcareScore: 62, qualityOfLife: 64, purchasingPower: 26, walkability: 54, publicTransport: 42,
    airQuality: 66, greenSpaces: 66, internetSpeed: 60, englishFriendly: 92, remoteWork: 74, nightlife: 72,
    schools: 62, jobMarket: 52, beachKm: 0, intlAirport: true,
  },
  {
    id: "dakar", name: "Dakar", country: "Senegal", photo: PHOTO.dakar, region: "africa",
    climate: "beach", climateLabelEs: "Sahariano costero", climateLabelEn: "Coastal Sahel",
    housing: 620, food: 280, transport: 50, healthcare: 80, education: 420, internet: 45, entertainment: 200,
    avgSalary: 420, taxRate: 20,
    safety: 58, healthcareScore: 50, qualityOfLife: 58, purchasingPower: 20, walkability: 56, publicTransport: 42,
    airQuality: 56, greenSpaces: 50, internetSpeed: 50, englishFriendly: 40, remoteWork: 70, nightlife: 70,
    schools: 52, jobMarket: 46, beachKm: 0, intlAirport: true,
  },
  {
    id: "zanzibar", name: "Zanzíbar", country: "Tanzania", photo: PHOTO.zanzibar, region: "africa",
    climate: "beach", climateLabelEs: "Tropical isleño", climateLabelEn: "Island tropical",
    housing: 480, food: 250, transport: 40, healthcare: 70, education: 380, internet: 45, entertainment: 200,
    avgSalary: 350, taxRate: 18,
    safety: 66, healthcareScore: 48, qualityOfLife: 64, purchasingPower: 18, walkability: 58, publicTransport: 36,
    airQuality: 76, greenSpaces: 72, internetSpeed: 40, englishFriendly: 72, remoteWork: 76, nightlife: 60,
    schools: 48, jobMarket: 40, beachKm: 0, intlAirport: true,
  },
];
