/**
 * Ciudades adicionales del Lifestyle Simulator.
 * Mismas fuentes y criterios que `lifestyle-cities.ts`.
 */
import type { CityData } from "./lifestyle-cities";
const PHOTO = {
  vienna: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Wien_-_Schloss_Sch%C3%B6nbrunn.JPG/1920px-Wien_-_Schloss_Sch%C3%B6nbrunn.JPG",
  munich: "https://upload.wikimedia.org/wikipedia/commons/7/73/Rathaus_and_Marienplatz_from_Peterskirche_-_August_2006.jpg",
  stockholm: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Gamla_stan_September_2014_01.jpg/1920px-Gamla_stan_September_2014_01.jpg",
  oslo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Oslo_Opera_House_-_2025.jpg/1920px-Oslo_Opera_House_-_2025.jpg",
  dublin: "https://upload.wikimedia.org/wikipedia/commons/5/53/HalfPennyBridge.jpg",
  budapest: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Hungarian_Parliament_Building_from_across_the_Danube%2C_2025-01-11.jpg/1920px-Hungarian_Parliament_Building_from_across_the_Danube%2C_2025-01-11.jpg",
  brussels: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Grand-Place%2C_Brussels_-_panorama%2C_June_2018.jpg/1920px-Grand-Place%2C_Brussels_-_panorama%2C_June_2018.jpg",
  edinburgh: "https://upload.wikimedia.org/wikipedia/commons/5/59/City_of_Edinburgh_-_Edinburgh_Castle_-_20140421004403.jpg",
  helsinki: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Kirkko3.png",
  geneva: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Jet_d%27eau_de_Gen%C3%A8ve_%28swiss%29.jpg/1920px-Jet_d%27eau_de_Gen%C3%A8ve_%28swiss%29.jpg",
  seattle: "https://upload.wikimedia.org/wikipedia/commons/2/23/Space_Needle_2011-07-04.jpg",
  boston: "https://upload.wikimedia.org/wikipedia/commons/9/96/ISH_WC_Boston4.jpg",
  sandiego: "https://upload.wikimedia.org/wikipedia/commons/e/ea/La_Jolla_Shores_view_%28cropped%29.jpg",
  montreal: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Montreal%2C_Quebec_skyline.jpg/1920px-Montreal%2C_Quebec_skyline.jpg",
  losangeles: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hollywood_sign_%288485145044%29.jpg/1920px-Hollywood_sign_%288485145044%29.jpg",
  denver: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Denver%2C_Colorado_skyline_%28cropped%29.jpg/1920px-Denver%2C_Colorado_skyline_%28cropped%29.jpg",
  guadalajara: "https://upload.wikimedia.org/wikipedia/commons/3/38/Panor%C3%A1mica_Guadalajara_desde_edificio_Bansi_hacia_norte_%28cropped%29.jpg",
  sanjose_cr: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Ciudad_de_San_Jos%C3%A9.png",
  cartagena: "https://upload.wikimedia.org/wikipedia/commons/3/30/Museo_Naval_del_Caribe.JPG",
  quito: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/FACHADA_ASAMBLEA_NACIONAL._QUITO%2C_20_DE_FEBRERO_2020._01.jpg/1920px-FACHADA_ASAMBLEA_NACIONAL._QUITO%2C_20_DE_FEBRERO_2020._01.jpg",
  asuncion: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Palacio_de_Gobierno2.jpg",
  osaka: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Osaka_Castle_03bs3200.jpg",
  hanoi: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Hanoi_skyline_with_Ba_Vi_Mountain.jpg",
  manila: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cityscape_of_Manila%2C_2025_%2801%29.jpg/1920px-Cityscape_of_Manila%2C_2025_%2801%29.jpg",
  telaviv: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Sarona_CBD_01_%28cropped%29.jpg/1920px-Sarona_CBD_01_%28cropped%29.jpg",
  abudhabi: "https://upload.wikimedia.org/wikipedia/en/7/7d/Sheikh_Zayed_Mosque_view.jpg",
  bengaluru: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/View_from_Visvesvaraya_Industrial_and_Technological_Museum_%282025%29_02.jpg/1920px-View_from_Visvesvaraya_Industrial_and_Technological_Museum_%282025%29_02.jpg",
  chiangmai: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/0020-%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%AA%E0%B8%B4%E0%B8%87%E0%B8%AB%E0%B9%8C%E0%B8%A7%E0%B8%A3%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A7%E0%B8%B4%E0%B8%AB%E0%B8%B2%E0%B8%A3.jpg/1920px-0020-%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%AA%E0%B8%B4%E0%B8%87%E0%B8%AB%E0%B9%8C%E0%B8%A7%E0%B8%A3%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A7%E0%B8%B4%E0%B8%AB%E0%B8%B2%E0%B8%A3.jpg",
  brisbane: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Brisbane_CBD_seen_from_Kangaroo_Point%2C_2024%2C_01_%282%29.jpg/1920px-Brisbane_CBD_seen_from_Kangaroo_Point%2C_2024%2C_01_%282%29.jpg",
  accra: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Acca.jpg",
  lagos: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Tafa_Balewa_Square_%28Onikan%29_in_Lagos._Nigeria.jpg",
  kigali: "https://upload.wikimedia.org/wikipedia/commons/2/2d/High_Angle_View_Of_Kigali_City_Street_on_November_29%2C_2018._Emmanuel_Kwizera.jpg",
  casablanca: "https://upload.wikimedia.org/wikipedia/en/c/ce/Hassan_II_mosque%2C_Casablanca_2.jpg",
};
export const extraCities: CityData[] = [
  {
    id: "vienna", name: "Viena", country: "Austria", photo: PHOTO.vienna, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 1150, food: 470, transport: 45, healthcare: 90, education: 300, internet: 35, entertainment: 340,
    avgSalary: 2700, taxRate: 34,
    safety: 88, healthcareScore: 90, qualityOfLife: 92, purchasingPower: 66, walkability: 90, publicTransport: 96,
    airQuality: 78, greenSpaces: 86, internetSpeed: 180, englishFriendly: 78, remoteWork: 88, nightlife: 80,
    schools: 88, jobMarket: 78, beachKm: 300, intlAirport: true,
  },
  {
    id: "munich", name: "Múnich", country: "Alemania", photo: PHOTO.munich, region: "europe",
    climate: "cold", climateLabelEs: "Continental alpino", climateLabelEn: "Alpine continental",
    housing: 1600, food: 520, transport: 60, healthcare: 120, education: 350, internet: 40, entertainment: 380,
    avgSalary: 3300, taxRate: 38,
    safety: 86, healthcareScore: 88, qualityOfLife: 90, purchasingPower: 68, walkability: 86, publicTransport: 92,
    airQuality: 76, greenSpaces: 82, internetSpeed: 150, englishFriendly: 80, remoteWork: 86, nightlife: 78,
    schools: 86, jobMarket: 88, beachKm: 450, intlAirport: true,
  },
  {
    id: "stockholm", name: "Estocolmo", country: "Suecia", photo: PHOTO.stockholm, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1500, food: 540, transport: 80, healthcare: 60, education: 200, internet: 40, entertainment: 400,
    avgSalary: 3100, taxRate: 33,
    safety: 82, healthcareScore: 88, qualityOfLife: 88, purchasingPower: 66, walkability: 88, publicTransport: 92,
    airQuality: 88, greenSpaces: 84, internetSpeed: 220, englishFriendly: 92, remoteWork: 88, nightlife: 74,
    schools: 86, jobMarket: 82, beachKm: 1, intlAirport: true,
  },
  {
    id: "oslo", name: "Oslo", country: "Noruega", photo: PHOTO.oslo, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1700, food: 650, transport: 85, healthcare: 70, education: 180, internet: 45, entertainment: 450,
    avgSalary: 3900, taxRate: 32,
    safety: 86, healthcareScore: 90, qualityOfLife: 90, purchasingPower: 70, walkability: 84, publicTransport: 88,
    airQuality: 90, greenSpaces: 88, internetSpeed: 230, englishFriendly: 92, remoteWork: 86, nightlife: 70,
    schools: 86, jobMarket: 84, beachKm: 1, intlAirport: true,
  },
  {
    id: "dublin", name: "Dublín", country: "Irlanda", photo: PHOTO.dublin, region: "europe",
    climate: "temperate", climateLabelEs: "Oceánico lluvioso", climateLabelEn: "Rainy oceanic",
    housing: 2000, food: 560, transport: 90, healthcare: 110, education: 450, internet: 45, entertainment: 420,
    avgSalary: 3300, taxRate: 30,
    safety: 72, healthcareScore: 76, qualityOfLife: 80, purchasingPower: 64, walkability: 84, publicTransport: 72,
    airQuality: 80, greenSpaces: 74, internetSpeed: 150, englishFriendly: 100, remoteWork: 88, nightlife: 86,
    schools: 80, jobMarket: 88, beachKm: 5, intlAirport: true,
  },
  {
    id: "budapest", name: "Budapest", country: "Hungría", photo: PHOTO.budapest, region: "europe",
    climate: "cold", climateLabelEs: "Continental templado", climateLabelEn: "Mild continental",
    housing: 750, food: 340, transport: 30, healthcare: 70, education: 220, internet: 20, entertainment: 240,
    avgSalary: 1350, taxRate: 28,
    safety: 80, healthcareScore: 72, qualityOfLife: 78, purchasingPower: 48, walkability: 88, publicTransport: 90,
    airQuality: 62, greenSpaces: 72, internetSpeed: 220, englishFriendly: 68, remoteWork: 88, nightlife: 88,
    schools: 74, jobMarket: 64, beachKm: 300, intlAirport: true,
  },
  {
    id: "brussels", name: "Bruselas", country: "Bélgica", photo: PHOTO.brussels, region: "europe",
    climate: "temperate", climateLabelEs: "Oceánico fresco", climateLabelEn: "Cool oceanic",
    housing: 1100, food: 470, transport: 55, healthcare: 90, education: 320, internet: 40, entertainment: 340,
    avgSalary: 2800, taxRate: 40,
    safety: 66, healthcareScore: 86, qualityOfLife: 80, purchasingPower: 62, walkability: 84, publicTransport: 86,
    airQuality: 70, greenSpaces: 76, internetSpeed: 160, englishFriendly: 84, remoteWork: 84, nightlife: 76,
    schools: 82, jobMarket: 80, beachKm: 110, intlAirport: true,
  },
  {
    id: "edinburgh", name: "Edimburgo", country: "Reino Unido", photo: PHOTO.edinburgh, region: "europe",
    climate: "cold", climateLabelEs: "Oceánico frío", climateLabelEn: "Cold oceanic",
    housing: 1250, food: 470, transport: 70, healthcare: 60, education: 380, internet: 35, entertainment: 340,
    avgSalary: 2600, taxRate: 32,
    safety: 84, healthcareScore: 82, qualityOfLife: 86, purchasingPower: 60, walkability: 90, publicTransport: 80,
    airQuality: 84, greenSpaces: 84, internetSpeed: 140, englishFriendly: 100, remoteWork: 84, nightlife: 80,
    schools: 84, jobMarket: 74, beachKm: 3, intlAirport: true,
  },
  {
    id: "helsinki", name: "Helsinki", country: "Finlandia", photo: PHOTO.helsinki, region: "europe",
    climate: "cold", climateLabelEs: "Nórdico frío", climateLabelEn: "Cold Nordic",
    housing: 1300, food: 500, transport: 70, healthcare: 60, education: 150, internet: 35, entertainment: 350,
    avgSalary: 2900, taxRate: 32,
    safety: 90, healthcareScore: 90, qualityOfLife: 90, purchasingPower: 66, walkability: 86, publicTransport: 90,
    airQuality: 92, greenSpaces: 86, internetSpeed: 200, englishFriendly: 90, remoteWork: 86, nightlife: 68,
    schools: 92, jobMarket: 78, beachKm: 1, intlAirport: true,
  },
  {
    id: "geneva", name: "Ginebra", country: "Suiza", photo: PHOTO.geneva, region: "europe",
    climate: "temperate", climateLabelEs: "Alpino templado", climateLabelEn: "Temperate alpine",
    housing: 2400, food: 750, transport: 80, healthcare: 420, education: 900, internet: 55, entertainment: 520,
    avgSalary: 6200, taxRate: 22,
    safety: 90, healthcareScore: 94, qualityOfLife: 90, purchasingPower: 84, walkability: 86, publicTransport: 92,
    airQuality: 86, greenSpaces: 88, internetSpeed: 220, englishFriendly: 86, remoteWork: 86, nightlife: 62,
    schools: 90, jobMarket: 86, beachKm: 300, intlAirport: true,
  },
  {
    id: "seattle", name: "Seattle", country: "Estados Unidos", photo: PHOTO.seattle, region: "northamerica",
    climate: "temperate", climateLabelEs: "Oceánico lluvioso", climateLabelEn: "Rainy oceanic",
    housing: 2200, food: 620, transport: 110, healthcare: 430, education: 900, internet: 70, entertainment: 450,
    avgSalary: 5600, taxRate: 28,
    safety: 58, healthcareScore: 80, qualityOfLife: 80, purchasingPower: 84, walkability: 80, publicTransport: 72,
    airQuality: 82, greenSpaces: 84, internetSpeed: 260, englishFriendly: 100, remoteWork: 90, nightlife: 80,
    schools: 82, jobMarket: 92, beachKm: 1, intlAirport: true,
  },
  {
    id: "boston", name: "Boston", country: "Estados Unidos", photo: PHOTO.boston, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental frío", climateLabelEn: "Cold continental",
    housing: 2600, food: 640, transport: 100, healthcare: 450, education: 1000, internet: 70, entertainment: 460,
    avgSalary: 5400, taxRate: 32,
    safety: 72, healthcareScore: 90, qualityOfLife: 82, purchasingPower: 80, walkability: 88, publicTransport: 82,
    airQuality: 80, greenSpaces: 74, internetSpeed: 250, englishFriendly: 100, remoteWork: 86, nightlife: 84,
    schools: 92, jobMarket: 90, beachKm: 2, intlAirport: true,
  },
  {
    id: "sandiego", name: "San Diego", country: "Estados Unidos", photo: PHOTO.sandiego, region: "northamerica",
    climate: "beach", climateLabelEs: "Mediterráneo costero", climateLabelEn: "Coastal Mediterranean",
    housing: 2400, food: 600, transport: 180, healthcare: 430, education: 900, internet: 70, entertainment: 440,
    avgSalary: 4900, taxRate: 30,
    safety: 72, healthcareScore: 80, qualityOfLife: 86, purchasingPower: 80, walkability: 66, publicTransport: 52,
    airQuality: 82, greenSpaces: 76, internetSpeed: 240, englishFriendly: 100, remoteWork: 88, nightlife: 78,
    schools: 82, jobMarket: 80, beachKm: 0, intlAirport: true,
  },
  {
    id: "montreal", name: "Montreal", country: "Canadá", photo: PHOTO.montreal, region: "northamerica",
    climate: "cold", climateLabelEs: "Continental frío", climateLabelEn: "Cold continental",
    housing: 1250, food: 480, transport: 90, healthcare: 80, education: 400, internet: 55, entertainment: 340,
    avgSalary: 2800, taxRate: 31,
    safety: 80, healthcareScore: 84, qualityOfLife: 84, purchasingPower: 62, walkability: 88, publicTransport: 86,
    airQuality: 80, greenSpaces: 78, internetSpeed: 190, englishFriendly: 80, remoteWork: 86, nightlife: 86,
    schools: 84, jobMarket: 78, beachKm: 1, intlAirport: true,
  },
  {
    id: "losangeles", name: "Los Ángeles", country: "Estados Unidos", photo: PHOTO.losangeles, region: "northamerica",
    climate: "warm", climateLabelEs: "Mediterráneo seco", climateLabelEn: "Dry Mediterranean",
    housing: 2500, food: 640, transport: 220, healthcare: 440, education: 950, internet: 70, entertainment: 520,
    avgSalary: 5200, taxRate: 32,
    safety: 52, healthcareScore: 78, qualityOfLife: 74, purchasingPower: 78, walkability: 58, publicTransport: 48,
    airQuality: 50, greenSpaces: 66, internetSpeed: 240, englishFriendly: 100, remoteWork: 86, nightlife: 90,
    schools: 74, jobMarket: 88, beachKm: 0, intlAirport: true,
  },
  {
    id: "denver", name: "Denver", country: "Estados Unidos", photo: PHOTO.denver, region: "northamerica",
    climate: "cold", climateLabelEs: "Semiárido de montaña", climateLabelEn: "Mountain semi-arid",
    housing: 1700, food: 540, transport: 180, healthcare: 410, education: 820, internet: 65, entertainment: 400,
    avgSalary: 4600, taxRate: 26,
    safety: 66, healthcareScore: 80, qualityOfLife: 82, purchasingPower: 82, walkability: 64, publicTransport: 58,
    airQuality: 76, greenSpaces: 84, internetSpeed: 250, englishFriendly: 100, remoteWork: 88, nightlife: 76,
    schools: 80, jobMarket: 84, beachKm: 1500, intlAirport: true,
  },
  {
    id: "guadalajara", name: "Guadalajara", country: "México", photo: PHOTO.guadalajara, region: "latam",
    climate: "warm", climateLabelEs: "Subtropical templado", climateLabelEn: "Mild subtropical",
    housing: 620, food: 300, transport: 45, healthcare: 90, education: 320, internet: 25, entertainment: 230,
    avgSalary: 780, taxRate: 22,
    safety: 50, healthcareScore: 62, qualityOfLife: 70, purchasingPower: 32, walkability: 68, publicTransport: 60,
    airQuality: 54, greenSpaces: 62, internetSpeed: 140, englishFriendly: 42, remoteWork: 80, nightlife: 84,
    schools: 66, jobMarket: 64, beachKm: 300, intlAirport: true,
  },
  {
    id: "sanjose_cr", name: "San José", country: "Costa Rica", photo: PHOTO.sanjose_cr, region: "latam",
    climate: "warm", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 780, food: 340, transport: 60, healthcare: 100, education: 420, internet: 35, entertainment: 260,
    avgSalary: 950, taxRate: 20,
    safety: 58, healthcareScore: 74, qualityOfLife: 78, purchasingPower: 36, walkability: 62, publicTransport: 56,
    airQuality: 72, greenSpaces: 86, internetSpeed: 90, englishFriendly: 58, remoteWork: 82, nightlife: 68,
    schools: 72, jobMarket: 58, beachKm: 90, intlAirport: true,
  },
  {
    id: "cartagena", name: "Cartagena", country: "Colombia", photo: PHOTO.cartagena, region: "latam",
    climate: "beach", climateLabelEs: "Tropical caribeño", climateLabelEn: "Caribbean tropical",
    housing: 600, food: 300, transport: 40, healthcare: 80, education: 300, internet: 25, entertainment: 240,
    avgSalary: 620, taxRate: 19,
    safety: 52, healthcareScore: 64, qualityOfLife: 70, purchasingPower: 28, walkability: 66, publicTransport: 48,
    airQuality: 70, greenSpaces: 58, internetSpeed: 90, englishFriendly: 44, remoteWork: 74, nightlife: 84,
    schools: 60, jobMarket: 50, beachKm: 0, intlAirport: true,
  },
  {
    id: "quito", name: "Quito", country: "Ecuador", photo: PHOTO.quito, region: "latam",
    climate: "temperate", climateLabelEs: "Andino templado", climateLabelEn: "Temperate Andean",
    housing: 520, food: 260, transport: 35, healthcare: 80, education: 280, internet: 25, entertainment: 200,
    avgSalary: 650, taxRate: 20,
    safety: 50, healthcareScore: 66, qualityOfLife: 68, purchasingPower: 28, walkability: 68, publicTransport: 62,
    airQuality: 60, greenSpaces: 72, internetSpeed: 80, englishFriendly: 40, remoteWork: 76, nightlife: 66,
    schools: 64, jobMarket: 50, beachKm: 200, intlAirport: true,
  },
  {
    id: "asuncion", name: "Asunción", country: "Paraguay", photo: PHOTO.asuncion, region: "latam",
    climate: "warm", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 480, food: 260, transport: 35, healthcare: 70, education: 260, internet: 25, entertainment: 190,
    avgSalary: 700, taxRate: 15,
    safety: 56, healthcareScore: 60, qualityOfLife: 66, purchasingPower: 32, walkability: 58, publicTransport: 48,
    airQuality: 64, greenSpaces: 60, internetSpeed: 90, englishFriendly: 36, remoteWork: 74, nightlife: 64,
    schools: 58, jobMarket: 52, beachKm: 1000, intlAirport: true,
  },
  {
    id: "osaka", name: "Osaka", country: "Japón", photo: PHOTO.osaka, region: "asia",
    climate: "temperate", climateLabelEs: "Subtropical húmedo", climateLabelEn: "Humid subtropical",
    housing: 900, food: 420, transport: 60, healthcare: 90, education: 350, internet: 35, entertainment: 320,
    avgSalary: 2300, taxRate: 26,
    safety: 94, healthcareScore: 90, qualityOfLife: 86, purchasingPower: 58, walkability: 88, publicTransport: 96,
    airQuality: 74, greenSpaces: 64, internetSpeed: 240, englishFriendly: 40, remoteWork: 78, nightlife: 88,
    schools: 84, jobMarket: 80, beachKm: 20, intlAirport: true,
  },
  {
    id: "hanoi", name: "Hanói", country: "Vietnam", photo: PHOTO.hanoi, region: "asia",
    climate: "warm", climateLabelEs: "Tropical monzónico", climateLabelEn: "Monsoon tropical",
    housing: 480, food: 250, transport: 40, healthcare: 70, education: 400, internet: 20, entertainment: 190,
    avgSalary: 520, taxRate: 14,
    safety: 72, healthcareScore: 58, qualityOfLife: 62, purchasingPower: 28, walkability: 66, publicTransport: 50,
    airQuality: 32, greenSpaces: 54, internetSpeed: 120, englishFriendly: 42, remoteWork: 86, nightlife: 78,
    schools: 58, jobMarket: 54, beachKm: 120, intlAirport: true,
  },
  {
    id: "manila", name: "Manila", country: "Filipinas", photo: PHOTO.manila, region: "asia",
    climate: "warm", climateLabelEs: "Tropical húmedo", climateLabelEn: "Humid tropical",
    housing: 620, food: 300, transport: 60, healthcare: 80, education: 450, internet: 35, entertainment: 230,
    avgSalary: 480, taxRate: 20,
    safety: 44, healthcareScore: 56, qualityOfLife: 56, purchasingPower: 24, walkability: 52, publicTransport: 44,
    airQuality: 38, greenSpaces: 42, internetSpeed: 90, englishFriendly: 86, remoteWork: 80, nightlife: 80,
    schools: 60, jobMarket: 54, beachKm: 5, intlAirport: true,
  },
  {
    id: "telaviv", name: "Tel Aviv", country: "Israel", photo: PHOTO.telaviv, region: "asia",
    climate: "beach", climateLabelEs: "Mediterráneo cálido", climateLabelEn: "Warm Mediterranean",
    housing: 2200, food: 620, transport: 70, healthcare: 110, education: 600, internet: 35, entertainment: 460,
    avgSalary: 3300, taxRate: 28,
    safety: 62, healthcareScore: 84, qualityOfLife: 80, purchasingPower: 58, walkability: 88, publicTransport: 74,
    airQuality: 66, greenSpaces: 64, internetSpeed: 180, englishFriendly: 88, remoteWork: 88, nightlife: 92,
    schools: 80, jobMarket: 86, beachKm: 0, intlAirport: true,
  },
  {
    id: "abudhabi", name: "Abu Dabi", country: "Emiratos Árabes", photo: PHOTO.abudhabi, region: "asia",
    climate: "warm", climateLabelEs: "Desértico", climateLabelEn: "Desert",
    housing: 1700, food: 500, transport: 150, healthcare: 150, education: 700, internet: 60, entertainment: 400,
    avgSalary: 4200, taxRate: 0,
    safety: 90, healthcareScore: 82, qualityOfLife: 82, purchasingPower: 80, walkability: 50, publicTransport: 52,
    airQuality: 58, greenSpaces: 54, internetSpeed: 220, englishFriendly: 90, remoteWork: 86, nightlife: 60,
    schools: 80, jobMarket: 82, beachKm: 1, intlAirport: true,
  },
  {
    id: "bengaluru", name: "Bengaluru", country: "India", photo: PHOTO.bengaluru, region: "asia",
    climate: "warm", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 450, food: 220, transport: 45, healthcare: 60, education: 400, internet: 20, entertainment: 190,
    avgSalary: 600, taxRate: 20,
    safety: 58, healthcareScore: 60, qualityOfLife: 60, purchasingPower: 30, walkability: 54, publicTransport: 52,
    airQuality: 40, greenSpaces: 66, internetSpeed: 100, englishFriendly: 86, remoteWork: 84, nightlife: 78,
    schools: 72, jobMarket: 86, beachKm: 300, intlAirport: true,
  },
  {
    id: "chiangmai", name: "Chiang Mai", country: "Tailandia", photo: PHOTO.chiangmai, region: "asia",
    climate: "warm", climateLabelEs: "Tropical de montaña", climateLabelEn: "Mountain tropical",
    housing: 380, food: 240, transport: 40, healthcare: 70, education: 350, internet: 20, entertainment: 190,
    avgSalary: 450, taxRate: 10,
    safety: 74, healthcareScore: 66, qualityOfLife: 74, purchasingPower: 26, walkability: 62, publicTransport: 42,
    airQuality: 34, greenSpaces: 78, internetSpeed: 120, englishFriendly: 58, remoteWork: 94, nightlife: 68,
    schools: 58, jobMarket: 40, beachKm: 650, intlAirport: true,
  },
  {
    id: "brisbane", name: "Brisbane", country: "Australia", photo: PHOTO.brisbane, region: "asia",
    climate: "warm", climateLabelEs: "Subtropical soleado", climateLabelEn: "Sunny subtropical",
    housing: 1750, food: 560, transport: 120, healthcare: 120, education: 700, internet: 55, entertainment: 420,
    avgSalary: 3900, taxRate: 28,
    safety: 80, healthcareScore: 86, qualityOfLife: 86, purchasingPower: 70, walkability: 72, publicTransport: 70,
    airQuality: 86, greenSpaces: 82, internetSpeed: 120, englishFriendly: 100, remoteWork: 84, nightlife: 74,
    schools: 84, jobMarket: 80, beachKm: 20, intlAirport: true,
  },
  {
    id: "accra", name: "Accra", country: "Ghana", photo: PHOTO.accra, region: "africa",
    climate: "warm", climateLabelEs: "Tropical costero", climateLabelEn: "Coastal tropical",
    housing: 700, food: 280, transport: 50, healthcare: 80, education: 450, internet: 40, entertainment: 200,
    avgSalary: 400, taxRate: 20,
    safety: 58, healthcareScore: 50, qualityOfLife: 58, purchasingPower: 20, walkability: 50, publicTransport: 40,
    airQuality: 44, greenSpaces: 48, internetSpeed: 60, englishFriendly: 96, remoteWork: 72, nightlife: 76,
    schools: 52, jobMarket: 48, beachKm: 0, intlAirport: true,
  },
  {
    id: "lagos", name: "Lagos", country: "Nigeria", photo: PHOTO.lagos, region: "africa",
    climate: "warm", climateLabelEs: "Tropical húmedo", climateLabelEn: "Humid tropical",
    housing: 800, food: 300, transport: 60, healthcare: 90, education: 500, internet: 50, entertainment: 220,
    avgSalary: 380, taxRate: 21,
    safety: 32, healthcareScore: 44, qualityOfLife: 48, purchasingPower: 18, walkability: 44, publicTransport: 34,
    airQuality: 32, greenSpaces: 40, internetSpeed: 50, englishFriendly: 96, remoteWork: 64, nightlife: 84,
    schools: 48, jobMarket: 56, beachKm: 0, intlAirport: true,
  },
  {
    id: "kigali", name: "Kigali", country: "Ruanda", photo: PHOTO.kigali, region: "africa",
    climate: "temperate", climateLabelEs: "Tropical de altura", climateLabelEn: "Highland tropical",
    housing: 450, food: 220, transport: 35, healthcare: 60, education: 380, internet: 35, entertainment: 160,
    avgSalary: 320, taxRate: 25,
    safety: 78, healthcareScore: 54, qualityOfLife: 66, purchasingPower: 18, walkability: 56, publicTransport: 46,
    airQuality: 66, greenSpaces: 72, internetSpeed: 60, englishFriendly: 80, remoteWork: 74, nightlife: 52,
    schools: 54, jobMarket: 44, beachKm: 1200, intlAirport: true,
  },
  {
    id: "casablanca", name: "Casablanca", country: "Marruecos", photo: PHOTO.casablanca, region: "africa",
    climate: "beach", climateLabelEs: "Mediterráneo atlántico", climateLabelEn: "Atlantic Mediterranean",
    housing: 520, food: 260, transport: 35, healthcare: 60, education: 320, internet: 25, entertainment: 190,
    avgSalary: 480, taxRate: 22,
    safety: 60, healthcareScore: 58, qualityOfLife: 64, purchasingPower: 24, walkability: 66, publicTransport: 58,
    airQuality: 52, greenSpaces: 50, internetSpeed: 70, englishFriendly: 52, remoteWork: 74, nightlife: 62,
    schools: 58, jobMarket: 54, beachKm: 0, intlAirport: true,
  },
];
