/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as CiudadesRouteImport } from './routes/ciudades'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as MiPerfilRouteImport } from './routes/mi-perfil'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as PortafolioRouteImport } from './routes/portafolio'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as RetiroRouteImport } from './routes/retiro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const CiudadesRoute = CiudadesRouteImport.update({
  id: '/ciudades',
  path: '/ciudades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPerfilRoute = MiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioRoute = PortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiroRoute = RetiroRouteImport.update({
  id: '/retiro',
  path: '/retiro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cash-flow': typeof CashFlowRoute
  '/ciudades': typeof CiudadesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gastos': typeof GastosRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/objetivos': typeof ObjetivosRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/portafolio': typeof PortafolioRoute
  '/precios': typeof PreciosRoute
  '/retiro': typeof RetiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cash-flow': typeof CashFlowRoute
  '/ciudades': typeof CiudadesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gastos': typeof GastosRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/objetivos': typeof ObjetivosRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/portafolio': typeof PortafolioRoute
  '/precios': typeof PreciosRoute
  '/retiro': typeof RetiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cash-flow': typeof CashFlowRoute
  '/ciudades': typeof CiudadesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gastos': typeof GastosRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/objetivos': typeof ObjetivosRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/portafolio': typeof PortafolioRoute
  '/precios': typeof PreciosRoute
  '/retiro': typeof RetiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/auth'
    | '/blog'
    | '/cash-flow'
    | '/ciudades'
    | '/configuracion'
    | '/dashboard'
    | '/demo'
    | '/gastos'
    | '/mi-perfil'
    | '/objetivos'
    | '/onboarding'
    | '/patrimonio'
    | '/portafolio'
    | '/precios'
    | '/retiro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/auth'
    | '/blog'
    | '/cash-flow'
    | '/ciudades'
    | '/configuracion'
    | '/dashboard'
    | '/demo'
    | '/gastos'
    | '/mi-perfil'
    | '/objetivos'
    | '/onboarding'
    | '/patrimonio'
    | '/portafolio'
    | '/precios'
    | '/retiro'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/auth'
    | '/blog'
    | '/cash-flow'
    | '/ciudades'
    | '/configuracion'
    | '/dashboard'
    | '/demo'
    | '/gastos'
    | '/mi-perfil'
    | '/objetivos'
    | '/onboarding'
    | '/patrimonio'
    | '/portafolio'
    | '/precios'
    | '/retiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CashFlowRoute: typeof CashFlowRoute
  CiudadesRoute: typeof CiudadesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  GastosRoute: typeof GastosRoute
  MiPerfilRoute: typeof MiPerfilRoute
  ObjetivosRoute: typeof ObjetivosRoute
  OnboardingRoute: typeof OnboardingRoute
  PatrimonioRoute: typeof PatrimonioRoute
  PortafolioRoute: typeof PortafolioRoute
  PreciosRoute: typeof PreciosRoute
  RetiroRoute: typeof RetiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciudades': {
      id: '/ciudades'
      path: '/ciudades'
      fullPath: '/ciudades'
      preLoaderRoute: typeof CiudadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-perfil': {
      id: '/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof MiPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio': {
      id: '/portafolio'
      path: '/portafolio'
      fullPath: '/portafolio'
      preLoaderRoute: typeof PortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiro': {
      id: '/retiro'
      path: '/retiro'
      fullPath: '/retiro'
      preLoaderRoute: typeof RetiroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CashFlowRoute: CashFlowRoute,
  CiudadesRoute: CiudadesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  GastosRoute: GastosRoute,
  MiPerfilRoute: MiPerfilRoute,
  ObjetivosRoute: ObjetivosRoute,
  OnboardingRoute: OnboardingRoute,
  PatrimonioRoute: PatrimonioRoute,
  PortafolioRoute: PortafolioRoute,
  PreciosRoute: PreciosRoute,
  RetiroRoute: RetiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
