/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as CiudadesRouteImport } from './routes/ciudades'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemoNinosRouteImport } from './routes/demo-ninos'
import { Route as ElegirRouteImport } from './routes/elegir'
import { Route as EnRouteImport } from './routes/en'
import { Route as FinanzasParaNinosRouteImport } from './routes/finanzas-para-ninos'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as HipotecaRouteImport } from './routes/hipoteca'
import { Route as LifePlannerRouteImport } from './routes/life-planner'
import { Route as MiPerfilRouteImport } from './routes/mi-perfil'
import { Route as NinosRouteRouteImport } from './routes/ninos/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as PortafolioRouteImport } from './routes/portafolio'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ReembolsosRouteImport } from './routes/reembolsos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RetiroRouteImport } from './routes/retiro'
import { Route as SuscripcionRouteImport } from './routes/suscripcion'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as EnBlogRouteImport } from './routes/en.blog'
import { Route as EnFinanzasParaNinosRouteImport } from './routes/en.finanzas-para-ninos'
import { Route as NinosIndexRouteImport } from './routes/ninos/index'
import { Route as NinosOnboardingRouteImport } from './routes/ninos/onboarding'
import { Route as NinosPadresRouteImport } from './routes/ninos/padres'
import { Route as ApiPublicRssRouteImport } from './routes/api/public/rss'
import { Route as EnBlogSlugRouteImport } from './routes/en.blog.$slug'
import { Route as NinosKidDatosRouteImport } from './routes/ninos/kid/datos'
import { Route as NinosKidDeseosRouteImport } from './routes/ninos/kid/deseos'
import { Route as NinosKidDineroRouteImport } from './routes/ninos/kid/dinero'
import { Route as NinosKidFuturoRouteImport } from './routes/ninos/kid/futuro'
import { Route as NinosKidNumeroRouteImport } from './routes/ninos/kid/numero'
import { Route as NinosKidTareasRouteImport } from './routes/ninos/kid/tareas'
import { Route as NinosKidUniversidadesRouteImport } from './routes/ninos/kid/universidades'
import { Route as ApiPublicLinkedinCallbackRouteImport } from './routes/api/public/linkedin/callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const CiudadesRoute = CiudadesRouteImport.update({
  id: '/ciudades',
  path: '/ciudades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNinosRoute = DemoNinosRouteImport.update({
  id: '/demo-ninos',
  path: '/demo-ninos',
  getParentRoute: () => rootRouteImport,
} as any)
const ElegirRoute = ElegirRouteImport.update({
  id: '/elegir',
  path: '/elegir',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasParaNinosRoute = FinanzasParaNinosRouteImport.update({
  id: '/finanzas-para-ninos',
  path: '/finanzas-para-ninos',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const HipotecaRoute = HipotecaRouteImport.update({
  id: '/hipoteca',
  path: '/hipoteca',
  getParentRoute: () => rootRouteImport,
} as any)
const LifePlannerRoute = LifePlannerRouteImport.update({
  id: '/life-planner',
  path: '/life-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPerfilRoute = MiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NinosRouteRoute = NinosRouteRouteImport.update({
  id: '/ninos',
  path: '/ninos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioRoute = PortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsosRoute = ReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiroRoute = RetiroRouteImport.update({
  id: '/retiro',
  path: '/retiro',
  getParentRoute: () => rootRouteImport,
} as any)
const SuscripcionRoute = SuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogRoute = EnBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => EnRoute,
} as any)
const EnFinanzasParaNinosRoute = EnFinanzasParaNinosRouteImport.update({
  id: '/finanzas-para-ninos',
  path: '/finanzas-para-ninos',
  getParentRoute: () => EnRoute,
} as any)
const NinosIndexRoute = NinosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NinosRouteRoute,
} as any)
const NinosOnboardingRoute = NinosOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => NinosRouteRoute,
} as any)
const NinosPadresRoute = NinosPadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => NinosRouteRoute,
} as any)
const ApiPublicRssRoute = ApiPublicRssRouteImport.update({
  id: '/api/public/rss',
  path: '/api/public/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnBlogRoute,
} as any)
const NinosKidDatosRoute = NinosKidDatosRouteImport.update({
  id: '/kid/datos',
  path: '/kid/datos',
  getParentRoute: () => NinosRouteRoute,
} as any)
const NinosKidDeseosRoute = NinosKidDeseosRouteImport.update({
  id: '/kid/deseos',
  path: '/kid/deseos',
  getParentRoute: () => NinosRouteRoute,
} as any)
const NinosKidDineroRoute = NinosKidDineroRouteImport.update({
  id: '/kid/dinero',
  path: '/kid/dinero',
  getParentRoute: () => NinosRouteRoute,
} as any)
const NinosKidFuturoRoute = NinosKidFuturoRouteImport.update({
  id: '/kid/futuro',
  path: '/kid/futuro',
  getParentRoute: () => NinosRouteRoute,
} as any)
const NinosKidNumeroRoute = NinosKidNumeroRouteImport.update({
  id: '/kid/numero',
  path: '/kid/numero',
  getParentRoute: () => NinosRouteRoute,
} as any)
const NinosKidTareasRoute = NinosKidTareasRouteImport.update({
  id: '/kid/tareas',
  path: '/kid/tareas',
  getParentRoute: () => NinosRouteRoute,
} as any)
const NinosKidUniversidadesRoute = NinosKidUniversidadesRouteImport.update({
  id: '/kid/universidades',
  path: '/kid/universidades',
  getParentRoute: () => NinosRouteRoute,
} as any)
const ApiPublicLinkedinCallbackRoute =
  ApiPublicLinkedinCallbackRouteImport.update({
    id: '/api/public/linkedin/callback',
    path: '/api/public/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ninos': typeof NinosRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/afiliados': typeof AfiliadosRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cash-flow': typeof CashFlowRoute
  '/ciudades': typeof CiudadesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-ninos': typeof DemoNinosRoute
  '/elegir': typeof ElegirRoute
  '/en': typeof EnRouteWithChildren
  '/finanzas-para-ninos': typeof FinanzasParaNinosRoute
  '/gastos': typeof GastosRoute
  '/hipoteca': typeof HipotecaRoute
  '/life-planner': typeof LifePlannerRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/portafolio': typeof PortafolioRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retiro': typeof RetiroRoute
  '/suscripcion': typeof SuscripcionRoute
  '/terminos': typeof TerminosRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/finanzas-para-ninos': typeof EnFinanzasParaNinosRoute
  '/ninos/onboarding': typeof NinosOnboardingRoute
  '/ninos/padres': typeof NinosPadresRoute
  '/ninos/': typeof NinosIndexRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/ninos/kid/datos': typeof NinosKidDatosRoute
  '/ninos/kid/deseos': typeof NinosKidDeseosRoute
  '/ninos/kid/dinero': typeof NinosKidDineroRoute
  '/ninos/kid/futuro': typeof NinosKidFuturoRoute
  '/ninos/kid/numero': typeof NinosKidNumeroRoute
  '/ninos/kid/tareas': typeof NinosKidTareasRoute
  '/ninos/kid/universidades': typeof NinosKidUniversidadesRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/afiliados': typeof AfiliadosRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cash-flow': typeof CashFlowRoute
  '/ciudades': typeof CiudadesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-ninos': typeof DemoNinosRoute
  '/elegir': typeof ElegirRoute
  '/en': typeof EnRouteWithChildren
  '/finanzas-para-ninos': typeof FinanzasParaNinosRoute
  '/gastos': typeof GastosRoute
  '/hipoteca': typeof HipotecaRoute
  '/life-planner': typeof LifePlannerRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/portafolio': typeof PortafolioRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retiro': typeof RetiroRoute
  '/suscripcion': typeof SuscripcionRoute
  '/terminos': typeof TerminosRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/finanzas-para-ninos': typeof EnFinanzasParaNinosRoute
  '/ninos/onboarding': typeof NinosOnboardingRoute
  '/ninos/padres': typeof NinosPadresRoute
  '/ninos': typeof NinosIndexRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/ninos/kid/datos': typeof NinosKidDatosRoute
  '/ninos/kid/deseos': typeof NinosKidDeseosRoute
  '/ninos/kid/dinero': typeof NinosKidDineroRoute
  '/ninos/kid/futuro': typeof NinosKidFuturoRoute
  '/ninos/kid/numero': typeof NinosKidNumeroRoute
  '/ninos/kid/tareas': typeof NinosKidTareasRoute
  '/ninos/kid/universidades': typeof NinosKidUniversidadesRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ninos': typeof NinosRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/afiliados': typeof AfiliadosRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cash-flow': typeof CashFlowRoute
  '/ciudades': typeof CiudadesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/demo-ninos': typeof DemoNinosRoute
  '/elegir': typeof ElegirRoute
  '/en': typeof EnRouteWithChildren
  '/finanzas-para-ninos': typeof FinanzasParaNinosRoute
  '/gastos': typeof GastosRoute
  '/hipoteca': typeof HipotecaRoute
  '/life-planner': typeof LifePlannerRoute
  '/mi-perfil': typeof MiPerfilRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/portafolio': typeof PortafolioRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reembolsos': typeof ReembolsosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retiro': typeof RetiroRoute
  '/suscripcion': typeof SuscripcionRoute
  '/terminos': typeof TerminosRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/en/finanzas-para-ninos': typeof EnFinanzasParaNinosRoute
  '/ninos/onboarding': typeof NinosOnboardingRoute
  '/ninos/padres': typeof NinosPadresRoute
  '/ninos/': typeof NinosIndexRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/ninos/kid/datos': typeof NinosKidDatosRoute
  '/ninos/kid/deseos': typeof NinosKidDeseosRoute
  '/ninos/kid/dinero': typeof NinosKidDineroRoute
  '/ninos/kid/futuro': typeof NinosKidFuturoRoute
  '/ninos/kid/numero': typeof NinosKidNumeroRoute
  '/ninos/kid/tareas': typeof NinosKidTareasRoute
  '/ninos/kid/universidades': typeof NinosKidUniversidadesRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ninos'
    | '/admin'
    | '/advisor'
    | '/afiliados'
    | '/auth'
    | '/blog'
    | '/cash-flow'
    | '/ciudades'
    | '/configuracion'
    | '/dashboard'
    | '/demo'
    | '/demo-ninos'
    | '/elegir'
    | '/en'
    | '/finanzas-para-ninos'
    | '/gastos'
    | '/hipoteca'
    | '/life-planner'
    | '/mi-perfil'
    | '/onboarding'
    | '/patrimonio'
    | '/portafolio'
    | '/precios'
    | '/privacidad'
    | '/reembolsos'
    | '/reset-password'
    | '/retiro'
    | '/suscripcion'
    | '/terminos'
    | '/admin/blog'
    | '/blog/$slug'
    | '/checkout/success'
    | '/en/blog'
    | '/en/finanzas-para-ninos'
    | '/ninos/onboarding'
    | '/ninos/padres'
    | '/ninos/'
    | '/api/public/rss'
    | '/en/blog/$slug'
    | '/ninos/kid/datos'
    | '/ninos/kid/deseos'
    | '/ninos/kid/dinero'
    | '/ninos/kid/futuro'
    | '/ninos/kid/numero'
    | '/ninos/kid/tareas'
    | '/ninos/kid/universidades'
    | '/api/public/linkedin/callback'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisor'
    | '/afiliados'
    | '/auth'
    | '/blog'
    | '/cash-flow'
    | '/ciudades'
    | '/configuracion'
    | '/dashboard'
    | '/demo'
    | '/demo-ninos'
    | '/elegir'
    | '/en'
    | '/finanzas-para-ninos'
    | '/gastos'
    | '/hipoteca'
    | '/life-planner'
    | '/mi-perfil'
    | '/onboarding'
    | '/patrimonio'
    | '/portafolio'
    | '/precios'
    | '/privacidad'
    | '/reembolsos'
    | '/reset-password'
    | '/retiro'
    | '/suscripcion'
    | '/terminos'
    | '/admin/blog'
    | '/blog/$slug'
    | '/checkout/success'
    | '/en/blog'
    | '/en/finanzas-para-ninos'
    | '/ninos/onboarding'
    | '/ninos/padres'
    | '/ninos'
    | '/api/public/rss'
    | '/en/blog/$slug'
    | '/ninos/kid/datos'
    | '/ninos/kid/deseos'
    | '/ninos/kid/dinero'
    | '/ninos/kid/futuro'
    | '/ninos/kid/numero'
    | '/ninos/kid/tareas'
    | '/ninos/kid/universidades'
    | '/api/public/linkedin/callback'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/ninos'
    | '/admin'
    | '/advisor'
    | '/afiliados'
    | '/auth'
    | '/blog'
    | '/cash-flow'
    | '/ciudades'
    | '/configuracion'
    | '/dashboard'
    | '/demo'
    | '/demo-ninos'
    | '/elegir'
    | '/en'
    | '/finanzas-para-ninos'
    | '/gastos'
    | '/hipoteca'
    | '/life-planner'
    | '/mi-perfil'
    | '/onboarding'
    | '/patrimonio'
    | '/portafolio'
    | '/precios'
    | '/privacidad'
    | '/reembolsos'
    | '/reset-password'
    | '/retiro'
    | '/suscripcion'
    | '/terminos'
    | '/admin/blog'
    | '/blog/$slug'
    | '/checkout/success'
    | '/en/blog'
    | '/en/finanzas-para-ninos'
    | '/ninos/onboarding'
    | '/ninos/padres'
    | '/ninos/'
    | '/api/public/rss'
    | '/en/blog/$slug'
    | '/ninos/kid/datos'
    | '/ninos/kid/deseos'
    | '/ninos/kid/dinero'
    | '/ninos/kid/futuro'
    | '/ninos/kid/numero'
    | '/ninos/kid/tareas'
    | '/ninos/kid/universidades'
    | '/api/public/linkedin/callback'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NinosRouteRoute: typeof NinosRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdvisorRoute: typeof AdvisorRoute
  AfiliadosRoute: typeof AfiliadosRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CashFlowRoute: typeof CashFlowRoute
  CiudadesRoute: typeof CiudadesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DemoNinosRoute: typeof DemoNinosRoute
  ElegirRoute: typeof ElegirRoute
  EnRoute: typeof EnRouteWithChildren
  FinanzasParaNinosRoute: typeof FinanzasParaNinosRoute
  GastosRoute: typeof GastosRoute
  HipotecaRoute: typeof HipotecaRoute
  LifePlannerRoute: typeof LifePlannerRoute
  MiPerfilRoute: typeof MiPerfilRoute
  OnboardingRoute: typeof OnboardingRoute
  PatrimonioRoute: typeof PatrimonioRoute
  PortafolioRoute: typeof PortafolioRoute
  PreciosRoute: typeof PreciosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ReembolsosRoute: typeof ReembolsosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RetiroRoute: typeof RetiroRoute
  SuscripcionRoute: typeof SuscripcionRoute
  TerminosRoute: typeof TerminosRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiPublicRssRoute: typeof ApiPublicRssRoute
  ApiPublicLinkedinCallbackRoute: typeof ApiPublicLinkedinCallbackRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciudades': {
      id: '/ciudades'
      path: '/ciudades'
      fullPath: '/ciudades'
      preLoaderRoute: typeof CiudadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-ninos': {
      id: '/demo-ninos'
      path: '/demo-ninos'
      fullPath: '/demo-ninos'
      preLoaderRoute: typeof DemoNinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elegir': {
      id: '/elegir'
      path: '/elegir'
      fullPath: '/elegir'
      preLoaderRoute: typeof ElegirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas-para-ninos': {
      id: '/finanzas-para-ninos'
      path: '/finanzas-para-ninos'
      fullPath: '/finanzas-para-ninos'
      preLoaderRoute: typeof FinanzasParaNinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipoteca': {
      id: '/hipoteca'
      path: '/hipoteca'
      fullPath: '/hipoteca'
      preLoaderRoute: typeof HipotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-planner': {
      id: '/life-planner'
      path: '/life-planner'
      fullPath: '/life-planner'
      preLoaderRoute: typeof LifePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-perfil': {
      id: '/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof MiPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ninos': {
      id: '/ninos'
      path: '/ninos'
      fullPath: '/ninos'
      preLoaderRoute: typeof NinosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio': {
      id: '/portafolio'
      path: '/portafolio'
      fullPath: '/portafolio'
      preLoaderRoute: typeof PortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolsos': {
      id: '/reembolsos'
      path: '/reembolsos'
      fullPath: '/reembolsos'
      preLoaderRoute: typeof ReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiro': {
      id: '/retiro'
      path: '/retiro'
      fullPath: '/retiro'
      preLoaderRoute: typeof RetiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suscripcion': {
      id: '/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof SuscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog': {
      id: '/en/blog'
      path: '/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof EnBlogRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/finanzas-para-ninos': {
      id: '/en/finanzas-para-ninos'
      path: '/finanzas-para-ninos'
      fullPath: '/en/finanzas-para-ninos'
      preLoaderRoute: typeof EnFinanzasParaNinosRouteImport
      parentRoute: typeof EnRoute
    }
    '/ninos/': {
      id: '/ninos/'
      path: '/'
      fullPath: '/ninos/'
      preLoaderRoute: typeof NinosIndexRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/ninos/onboarding': {
      id: '/ninos/onboarding'
      path: '/onboarding'
      fullPath: '/ninos/onboarding'
      preLoaderRoute: typeof NinosOnboardingRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/ninos/padres': {
      id: '/ninos/padres'
      path: '/padres'
      fullPath: '/ninos/padres'
      preLoaderRoute: typeof NinosPadresRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/api/public/rss': {
      id: '/api/public/rss'
      path: '/api/public/rss'
      fullPath: '/api/public/rss'
      preLoaderRoute: typeof ApiPublicRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof EnBlogRoute
    }
    '/ninos/kid/datos': {
      id: '/ninos/kid/datos'
      path: '/kid/datos'
      fullPath: '/ninos/kid/datos'
      preLoaderRoute: typeof NinosKidDatosRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/ninos/kid/deseos': {
      id: '/ninos/kid/deseos'
      path: '/kid/deseos'
      fullPath: '/ninos/kid/deseos'
      preLoaderRoute: typeof NinosKidDeseosRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/ninos/kid/dinero': {
      id: '/ninos/kid/dinero'
      path: '/kid/dinero'
      fullPath: '/ninos/kid/dinero'
      preLoaderRoute: typeof NinosKidDineroRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/ninos/kid/futuro': {
      id: '/ninos/kid/futuro'
      path: '/kid/futuro'
      fullPath: '/ninos/kid/futuro'
      preLoaderRoute: typeof NinosKidFuturoRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/ninos/kid/numero': {
      id: '/ninos/kid/numero'
      path: '/kid/numero'
      fullPath: '/ninos/kid/numero'
      preLoaderRoute: typeof NinosKidNumeroRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/ninos/kid/tareas': {
      id: '/ninos/kid/tareas'
      path: '/kid/tareas'
      fullPath: '/ninos/kid/tareas'
      preLoaderRoute: typeof NinosKidTareasRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/ninos/kid/universidades': {
      id: '/ninos/kid/universidades'
      path: '/kid/universidades'
      fullPath: '/ninos/kid/universidades'
      preLoaderRoute: typeof NinosKidUniversidadesRouteImport
      parentRoute: typeof NinosRouteRoute
    }
    '/api/public/linkedin/callback': {
      id: '/api/public/linkedin/callback'
      path: '/api/public/linkedin/callback'
      fullPath: '/api/public/linkedin/callback'
      preLoaderRoute: typeof ApiPublicLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NinosRouteRouteChildren {
  NinosOnboardingRoute: typeof NinosOnboardingRoute
  NinosPadresRoute: typeof NinosPadresRoute
  NinosIndexRoute: typeof NinosIndexRoute
  NinosKidDatosRoute: typeof NinosKidDatosRoute
  NinosKidDeseosRoute: typeof NinosKidDeseosRoute
  NinosKidDineroRoute: typeof NinosKidDineroRoute
  NinosKidFuturoRoute: typeof NinosKidFuturoRoute
  NinosKidNumeroRoute: typeof NinosKidNumeroRoute
  NinosKidTareasRoute: typeof NinosKidTareasRoute
  NinosKidUniversidadesRoute: typeof NinosKidUniversidadesRoute
}

const NinosRouteRouteChildren: NinosRouteRouteChildren = {
  NinosOnboardingRoute: NinosOnboardingRoute,
  NinosPadresRoute: NinosPadresRoute,
  NinosIndexRoute: NinosIndexRoute,
  NinosKidDatosRoute: NinosKidDatosRoute,
  NinosKidDeseosRoute: NinosKidDeseosRoute,
  NinosKidDineroRoute: NinosKidDineroRoute,
  NinosKidFuturoRoute: NinosKidFuturoRoute,
  NinosKidNumeroRoute: NinosKidNumeroRoute,
  NinosKidTareasRoute: NinosKidTareasRoute,
  NinosKidUniversidadesRoute: NinosKidUniversidadesRoute,
}

const NinosRouteRouteWithChildren = NinosRouteRoute._addFileChildren(
  NinosRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EnBlogRouteChildren {
  EnBlogSlugRoute: typeof EnBlogSlugRoute
}

const EnBlogRouteChildren: EnBlogRouteChildren = {
  EnBlogSlugRoute: EnBlogSlugRoute,
}

const EnBlogRouteWithChildren =
  EnBlogRoute._addFileChildren(EnBlogRouteChildren)

interface EnRouteChildren {
  EnBlogRoute: typeof EnBlogRouteWithChildren
  EnFinanzasParaNinosRoute: typeof EnFinanzasParaNinosRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnBlogRoute: EnBlogRouteWithChildren,
  EnFinanzasParaNinosRoute: EnFinanzasParaNinosRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NinosRouteRoute: NinosRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdvisorRoute: AdvisorRoute,
  AfiliadosRoute: AfiliadosRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CashFlowRoute: CashFlowRoute,
  CiudadesRoute: CiudadesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DemoNinosRoute: DemoNinosRoute,
  ElegirRoute: ElegirRoute,
  EnRoute: EnRouteWithChildren,
  FinanzasParaNinosRoute: FinanzasParaNinosRoute,
  GastosRoute: GastosRoute,
  HipotecaRoute: HipotecaRoute,
  LifePlannerRoute: LifePlannerRoute,
  MiPerfilRoute: MiPerfilRoute,
  OnboardingRoute: OnboardingRoute,
  PatrimonioRoute: PatrimonioRoute,
  PortafolioRoute: PortafolioRoute,
  PreciosRoute: PreciosRoute,
  PrivacidadRoute: PrivacidadRoute,
  ReembolsosRoute: ReembolsosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RetiroRoute: RetiroRoute,
  SuscripcionRoute: SuscripcionRoute,
  TerminosRoute: TerminosRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiPublicRssRoute: ApiPublicRssRoute,
  ApiPublicLinkedinCallbackRoute: ApiPublicLinkedinCallbackRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
