/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gastos' | '/patrimonio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gastos' | '/patrimonio'
  id: '__root__' | '/' | '/gastos' | '/patrimonio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GastosRoute: typeof GastosRoute
  PatrimonioRoute: typeof PatrimonioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GastosRoute: GastosRoute,
  PatrimonioRoute: PatrimonioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
